### ISSUE TITLE
Adding parameter to organize sub folders

### ISSUE THREAD

**Issue by campa** [yeoman/generator-angular#1001]
yo angular:route thing __[--basePath=base_path/thing]__

    This will create:
        app/scripts/controllers/base_path/thing.js
        app/base_path/thing.html
    And add routing ( with uri  base_path/thing.html ) to:
        app.js

**Comment by eddiemonge** [comment]
Is this a feature request or a question or ... ?

**Comment by campa** [comment]
Feature request .
Bye

**Comment by eddiemonge** [comment]
you can organize by uri: https://github.com/yeoman/generator-angular#route
For subfolders, this is already on the roadmap
