### ISSUE TITLE
Error about compass when using grunt

### ISSUE THREAD

**Issue by Elzean** [yeoman/generator-angular#1002]
Hi,

i have a problem when starting "grunt" on a new install with "yo angular" : 

>Running "concurrent:test" (concurrent) task
>    Warning: Running "compass:dist" (compass) task
>directory .tmp/styles/
>       create .tmp/styles/main.css (0.806s)
>    Compilation took 0.888s

Running "compass:server" (compass) task
Error: invalid option: --sourcemap

Shouldnt i use sass or bootstrap-sass in the option when installing ? Is this a problem on my end that i can fix ?

I am not used to all those tools (yeoman, bower, grunt, ...), thanks for your help !

**Comment by sindresorhus** [comment]
Upgrade Compass.
