### ISSUE TITLE
Yo angular keeps creating project on /home

### ISSUE THREAD

**Issue by sebastialonso** [yeoman/generator-angular#1003]
I've followed the Tutorial on Yeoman's webpage, also the one in [SitePoint](http://www.sitepoint.com/kickstart-your-angularjs-development-with-yeoman-grunt-and-bower/). 

I create a new folder for my project, I cd into it, run the super cool command `yo angular` but the project's files and folders are created in my /home folder, which is annoying to say the least. Am I missing some configuration?

**Comment by eddiemonge** [comment]
Do you have a `.yo-rc.json` file in your `/home` directory or any child directory of that?

**Comment by sebastialonso** [comment]
Yes, I do!

**Comment by eddiemonge** [comment]
yo treats where ever that is as the project root and creates the project there.
