### ISSUE TITLE
grunt-ng-annotate throws error on new project

### ISSUE THREAD

**Issue by drmyersii** [yeoman/generator-angular#1007]
I just created a new project with ```yo angular``` and I said no to using sass. I get this error when running the ```grunt``` or ```grunt build``` commands: 

```bash
Running "ngAnnotate:dist" (ngAnnotate) task
Warning: Cannot assign to read only property '$methodName' of false Use --force
to continue.

Aborted due to warnings.
```

I have also tried updating grunt-ng-annotate to see if that fixed the issue, but it does not. Thanks for the help!

**Comment by eddiemonge** [comment]
duplicate of #1006 

Please use version 0.11.1 as it should be fixed in there. Also make sure you have updated yo

**Comment by ratshili** [comment]
@eddiemonge I also have the same problem, I have no idea what to do. please help. If possible explain in details

**Comment by ratshili** [comment]
Hi @eddiemonge, i got it working. All i did was  npm update --all
