### ISSUE TITLE
Update grunt-ng-annotate to 0.9.2 to be compatible with newest NodeJS

### ISSUE THREAD

**Issue by hanfeisun** [yeoman/generator-angular#1009]
I'm using latest nodeJS

    $ node -v
    v0.12.0

I found ngAnnotate:dist will throw errors 

    $ grunt ngAnnotate:dist
    Running "ngAnnotate:dist" (ngAnnotate) task
    Warning: Cannot assign to read only property '$methodName' of false Use --force to continue.

it is solved when `grunt-ng-annoate` is upgraded in `package.json`...
    "grunt-ng-annotate": "^0.9.2",

**Comment by eddiemonge** [comment]
already in https://github.com/yeoman/generator-angular/commit/f4e7d94aaffa385b9638e53b51c49c2fa39bfbcf and released as [0.11.1](https://github.com/yeoman/generator-angular/releases/tag/v0.11.1)
