### ISSUE TITLE
angular:view ... it should include its own .js file, not just the .html

### ISSUE THREAD

**Issue by Silverium** [yeoman/generator-angular#1013]
I think "yo angular:view page" should create a new view, with it's page.html and page.js and to be in the nav-bar, and of course with its corresponding link.

**Comment by cebor** [comment]
`yo angular:routes" does this, except adding the link to the nav

**Comment by eddiemonge** [comment]
Yup ^^. Not adding it to the nav bar is a feature as not all routes will be a main nav.
