### ISSUE TITLE
Generation causes stacktraces

### ISSUE THREAD

**Issue by villesau** [yeoman/generator-angular#1014]
Hi!

I'm using node 0.10.36, npm 2.5.1 and osX 10.9.5.
i get following stacktraces when i'm generating an app with all features included:

   create             app/scripts/controllers/about.js

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
npm WARN optional dep failed, continuing imagemin-gifsicle@4.1.0
npm WARN optional dep failed, continuing imagemin-jpegtran@4.1.0
npm WARN optional dep failed, continuing imagemin-optipng@4.2.0
npm WARN optional dep failed, continuing imagemin-pngquant@4.0.0
npm ERR! cb() never called

**Comment by villesau** [comment]
The reason for this was that i didn't have bower installed. So the fix is to install bower globally. Case closed. There is nothing to see here. Disperse!

**Comment by eddiemonge** [comment]
You should have received an error saying bower wasn't installed when `bower install` was automatically run.
