### ISSUE TITLE
When running grunt serve I can't find module browserslist

### ISSUE THREAD

**Issue by sdbeng** [yeoman/generator-angular#1017]
Hi, 
I'm trying to work with the generator-angular and I get this error that prevents opening the app in the browser. 
-It runs wiredeep ok,
karma-jasmine@0.3.5 node_modules/karma-jasmine
Loading "jshint.js" tasks...ERROR
>> Error: Cannot find module 'hooker'

Running "wiredep:app" (wiredep) task

Running "wiredep:test" (wiredep) task

Done, without errors.

-then I get this:

Loading "autoprefixer.js" tasks...ERROR
>> Error: Cannot find module 'browserslist'
Loading "jshint.js" tasks...ERROR
>> Error: Cannot find module 'hooker'

Running "serve" task
Warning: Task "autoprefixer:server" not found. Use --force to continue.

Aborted due to warnings.

Do I need to modify the Gruntfile.js file? I'm running node 0.12.0.

**Comment by eddiemonge** [comment]
Try running `npm install && bower install`

**Comment by sdbeng** [comment]
I tried it, then run grunt serve and got the same error message. Anything else I can try so this app can run? I did try yo angular generator a few months ago and it worked. Thank you for the advice.

**Comment by eddiemonge** [comment]
What is your output from running the install commands?

**Comment by sdbeng** [comment]
Once they get executed, there is no output.

**Comment by eddiemonge** [comment]
nothing at all? that seems odd.

**Comment by Thiemo-Mueller** [comment]
Any updates on this one? I'm having the exact same issue after cloning a repo with code from angular generator and running the install commands. Thanks!

**Comment by eddiemonge** [comment]
try running `npm install grunt-autoprefixer`
