### ISSUE TITLE
Part of the css file is lost during minification

### ISSUE THREAD

**Issue by skylve** [yeoman/generator-angular#1018]
I've tried to find where the issue come from, but could not find anything.

I've created an example repo here : https://github.com/skylve/AngularGeneratorCSSMinBug
The style 'inspinia.css' is almost totally lost during minification.

Thanks

**Comment by eddiemonge** [comment]
Its grabbing from around line 4740 and discarding everything before it. thats weird

**Comment by eddiemonge** [comment]
Your grunt-contrib-cssmin is old. Update it and itll fix the problem. I tested with 0.12.2 on your project and it fixes it
