### ISSUE TITLE
Loadtime on Amazon EC2 is huge

### ISSUE THREAD

**Issue by Talamantez** [yeoman/generator-angular#1019]
Hi, thanks for providing this awesome generator. I'm trying out a clone of generator-angular on Amazon EC2.  When I go to the ip, it takes 5 minutes to load the page. Once loaded, however, POST commands and socket.io updates do occur in real time.  Do you have any advice on diagnosing this issue?

Thanks!

**Comment by eddiemonge** [comment]
That sounds like a Amazon EC2 problem since this generates a static page. Try asking Amazon for help (if that exists) or on stackoverflow.

**Comment by deveshsinghal22** [comment]
I have a suggestion for this. 
open 35729 port on your EC2 instance in inbound and outbound.
