### ISSUE TITLE
Compass import being removed from main.scss

### ISSUE THREAD

**Issue by westlywright** [yeoman/generator-angular#1021]
Im having an issue with adding compass to the main.scss file like so

`@import "compass";`

If I add this after the grunt server is running I dont have any issue but the next time I run grunt server the line mentioned above is removed from main.scss. I'm not quite understand this and i've never had this issue before. 
I'm on Yo 1.4.5, Mac os X 10.10 (latest).

**Comment by eddiemonge** [comment]
it should not remove it from app/styles/main.scss. Is that the file you are editing?

**Comment by westlywright** [comment]
Correct, the file that I am editing is app/styles/main.scss. I have not changed the grunt file, I did downgrade the version of Angular in my package.json for my specific project, though I would not see that causing a problem.

**Comment by eddiemonge** [comment]
I don't know what to tell you. There is nothing that I know of that would cause that unless you have changed the Gruntfile to write to that file somehow.

**Comment by westlywright** [comment]
I am curious if anyone else can reproduce this. I just created a test app with the generator. I opened app/styles/main.scss and added @import "compass"; after line 3. I run grunt serve and the import compass line is remove. I have updated my generators and yo. I have not modified this new test repo in anyway besides adding that new line. Can some one see if they can repro this?

**Comment by Maninacan** [comment]
I am having the same issue.  It affects every @import statement that I add to it.  For some reason it doesn't remove the existing @import for bootstrap, but anything I add is removed when I build the project.

**Comment by Maninacan** [comment]
I think I may have discovered the issue.  I was putting the @import statements inside of the bower tags:

// bower:scss
@import "bootstrap-sass-official/assets/stylesheets/_bootstrap.scss";
// I was putting stuff here.
// endbower
// All of the @import statements should be out here

**Comment by eddiemonge** [comment]
So is this fixed then? If not, let me know.
