### ISSUE TITLE
ability to use gulp instead of grunt

### ISSUE THREAD

**Issue by jonathanobino** [yeoman/generator-angular#1023]
are you going to implement the choice of using gulp instead of grunt?

**Comment by eddiemonge** [comment]
yes at some point.

**Comment by abdulklarapl** [comment]
Hi there.

As I can see, there is a commit with this feature:
https://github.com/yeoman/generator-angular/commit/9ad4d74f40b91b891712ddf44eb35c278d1ecb61

But when I'm generating the project, there's no ask for a gulp. When it will be accessible or how can I use master version of generator?

**Comment by arthurvr** [comment]
@abdulklarapl Notice the timestamp of the commit and the date of the latest release. Gulp support landed, it simply wasn't released yet. We'd really appreciate it if you could try the feature though. That's possible by cloning the repo and `npm link`ing the generator :)

**Comment by abdulklarapl** [comment]
That's why I'm asking "when it will be accessible" not "why it's not working" :).
Thank you for advice about linking the generator!

**Comment by eddiemonge** [comment]
Its accessible now. I was waiting on a few other big changes before I released a beta
