### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by perqa** [yeoman/generator-angular#1026]
Could not install according to instructions:
```
npm install -g generator-angular
npm ERR! peerinvalid The package generator-karma does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer generator-angular@0.11.1 wants generator-karma@>=0.9.0
```
Had to first install generator-karma separately:
```
npm install -g generator-karma
```
After that installation worked as described.

**Comment by eddiemonge** [comment]
Known issue thats documented in the readme: https://github.com/yeoman/generator-angular#usage

**Comment by weber-cd** [comment]
npm install -g generator-karma@0.9.0
