### ISSUE TITLE
Cannot find module 'browserslist'...

### ISSUE THREAD

**Issue by ArnoldM-webdev** [yeoman/generator-angular#1028]
I've got this error 'Cannot find module 'browserslist' during loading "autoprefixer.js" tasks.
It seems that the module 'browserslist' increased to 0.3.1 version while the expected version is 2.0.1.
I solved the problem by performing the following actions...

npm install --save-dev browserslist@'~0.2.0' 
npm install --save-dev postcss
npm install --save-dev num2fraction
npm install --save-dev caniuse-db

Update the generator ?

**Comment by sindresorhus** [comment]
Anything regarding installing is a problem with npm, not the module you want to install.

https://github.com/npm/npm/issues
