### ISSUE TITLE
use `controller as` syntax

### ISSUE THREAD

**Issue by marcin-wosinek** [yeoman/generator-angular#1033]
What do you think about switching all routes & directives to use `controller as` syntax? Looks that it's generally recommended & future-proof:
https://github.com/johnpapa/angular-styleguide
https://www.youtube.com/watch?feature=player_detailpage&v=pai1ZdFI2dg#t=763

**Comment by pensierinmusica** [comment]
+1

**Comment by eddiemonge** [comment]
I wouldn't be opposed to it

**Comment by alcachi** [comment]
I would really appreciate this change. I am new to angular and the old $scope syntax is the only thing that stops me from using yeoman.

**Comment by dancancro** [comment]
@alcachi, @pensierinmusica, @marcin-wosinek  

Have a look [here](https://docs.google.com/spreadsheets/d/1r8rJy2Q5p5QORYKcye93UECwOlSgFL24c5fyF7dqhaM/edit#gid=1607194899).  "Uses Controller As" is on row 221.  To the best of my knowledge, the following starters use Controller As:

* generator- ng-poly
* generator- bangular
* John Papa's Angular Breeze Course
* Deborah Kurata's Course
* Gocardless's Way
* John Papa's gulp-patterns repo
* Steve Michelotti's Course
* angular- demo

Your help filling this thing in is always welcome. Write me if you can help with it.

**Comment by alcachi** [comment]
Thanks for the link!

If you are interested in adding this functionality I offer my help.
