### ISSUE TITLE
When running grunt serve I can't find module browserslist

### ISSUE THREAD

**Issue by bautistaaa** [yeoman/generator-angular#1035]
Hi I just followed the directions for creating an angular app.

Here is my console output

```bash
Loading "autoprefixer.js" tasks...ERROR
>> Error: Cannot find module 'browserslist'

Running "serve" task

Running "clean:server" (clean) task
>> 0 paths cleaned.

Running "wiredep:app" (wiredep) task

Running "wiredep:test" (wiredep) task

Running "wiredep:sass" (wiredep) task

Running "concurrent:server" (concurrent) task
    Warning: Loading "autoprefixer.js" tasks...ERROR
    >> Error: Cannot find module 'browserslist'
    
    Running "compass:server" (compass) task
    Warning: Couldn't find the `compass` binary. Make sure it's installed and in your $PATH Use --force to continue.
    
    Aborted due to warnings.
    
    
    Execution Time (2015-03-13 01:52:11 UTC)
    loading tasks    3ms  ▇▇▇▇▇▇▇▇ 16%
    compass:server  15ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 79%
    Total 19ms Use --force to continue.
        
        Aborted due to warnings.
    

Execution Time (2015-03-13 01:52:09 UTC)
wiredep:app        103ms  ▇▇▇▇▇ 4%
concurrent:server   2.2s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 95%
Total 2.3s
```

i have ran npm install && bower install but nothing happens(I am assuming because all the dependencies have been installed already)

**Comment by sinelanguage** [comment]
so I had the same errors as well, and here's how I solved it.  I manually installed the following modules using sudo (I don't mind using it as its only my dev laptop):  browserslist, purecss, num2fractions, caniuse, and caniuse-db.  So
    $ sudo npm install [item from list above]
One at a time.  Once I did that I was able to run grunt serve no problem

**Comment by eddiemonge** [comment]
Don't use sudo for npm modules if you can avoid, which you can avoid 95% of the time. You also don't have compass installed. Try a `npm rebuild --force` for fun

**Comment by thomasturnbull** [comment]
`npm install [the missing modules] `

got this working for me (no sudo required)

**Comment by eddiemonge** [comment]
closing as it seems to be a npm issue
