### ISSUE TITLE
Angular 2.0

### ISSUE THREAD

**Issue by pensierinmusica** [yeoman/generator-angular#1036]
According to Brad Green at ng-conf 2015

> the first production Angular 2.0 app at Google will ship in May 2015.

Is there any timeline estimate to support Angular 2.0 in "generator-angular"?

Considering the breaking changes, will there be a separate generator, or a user option during the initialization process?

Thanks!

**Comment by eddiemonge** [comment]
When its fully ready, we will figure out what to do. Until then we are taking a wait and see approach.
