### ISSUE TITLE
ng-src get ignored to replace image source by grunt build

### ISSUE THREAD

**Issue by grrseguin** [yeoman/generator-angular#1038]
Hi,

I have an 404 HTTP Error with HTTP img tag using ng-src directive, after a grunt build. the minified images are renamed but not the path of those ones.

This is caused by the pattern used by grunt-usemin.

Is it possible to add the indicated configuration in this <a href="https://github.com/yeoman/grunt-usemin/issues/497#issuecomment-75400354">comment</a> ? So when the angular scaffolding is generated.

Moreover, if you use some curly brackets to the beginning of your ngSrc directive value. You must to use the regex above in your Gruntfile.
```javascript
/<img[^\>]*[^\>\S]+ng\-src=['"]\{*[^\}]*\}*([^'"\)#]+)(#.+)?["']/gm
```

**Comment by grrseguin** [comment]
see : http://stackoverflow.com/questions/29074894/dynamic-image-ng-src-doesnt-change-to-minified-image-name

**Comment by eddiemonge** [comment]
answered on so
