### ISSUE TITLE
Failed to install generator-angular with MacBook Air 

### ISSUE THREAD

**Issue by woaixiangbao** [yeoman/generator-angular#1039]
I am come from china, my english is very bad, I very sorry,sorry,please help me,

---------------MacBook Air---------OS10.10.2-------

I want to install angular with npm,so,I write this in terminal：sudo npm install -g generator-angular

and then the terminal show me this:

npm WARN peerDependencies The peer dependency generator-karma@>=0.9.0 included from generator-angular will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency yo@>=1.0.0 included from generator-angular will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

generator-angular@0.11.1 /opt/local/lib/node_modules/generator-angular[|
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── yosay@1.0.3 (string-length@1.0.0, ansi-styles@2.0.1, ansi-regex@1.1.1, word-wrap@1.0.2, strip-ansi@2.0.1, pad-component@0.0.1, minimist@1.1.1, taketalk@1.0.0, chalk@1.0.0)
├── wiredep@2.2.2 (propprop@0.3.0, minimist@1.1.1, lodash@2.4.1, glob@4.5.3, bower-config@0.5.2, through2@0.6.3)
└── yeoman-generator@0.16.0 (dargs@0.1.0, diff@1.0.8, debug@0.7.4, class-extend@0.1.1, rimraf@2.2.8, findup-sync@0.1.3, text-table@0.2.0, mime@1.2.11, async@0.2.10, mkdirp@0.3.5, isbinaryfile@2.0.3, shelljs@0.2.6, chalk@0.4.0, underscore.string@2.3.3, iconv-lite@0.2.11, lodash@2.4.1, glob@3.2.11, request@2.30.0, cheerio@0.13.1, file-utils@0.1.5, inquirer@0.4.1, download@0.1.19)

I think,may be the generatro-karma need to update,so,i write this in terminal:sudo npm install -g generator-karma

an then the terminal show me this:

npm WARN peerDependencies The peer dependency yo@>=1.0.0 included from generator-karma will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
generator-karma@0.9.0 /opt/local/lib/node_modules/generator-karma
├── underscore@1.8.2
└── yeoman-generator@0.17.7 (dargs@2.1.0, rimraf@2.3.2, diff@1.3.1, class-extend@0.1.1, text-table@0.2.0, mime@1.3.4, underscore.string@2.4.0, async@0.9.0, isbinaryfile@2.0.3, shelljs@0.3.0, iconv-lite@0.4.7, lodash@2.4.1, cross-spawn@0.2.6, grouped-queue@0.3.0, nopt@3.0.1, chalk@0.5.1, run-async@0.1.0, mkdirp@0.5.0, glob@4.5.3, debug@1.0.4, findup-sync@0.1.3, file-utils@0.2.2, github-username@1.1.1, cheerio@0.17.0, request@2.53.0, gruntfile-editor@0.2.0, download@1.0.7, inquirer@0.7.3)

Still show me error,what can i do?

please help me,i don't know what to do .

**Comment by woaixiangbao** [comment]
i google this issue,and had some links,but still can't resolve my error.

some links like this:

1,https://github.com/yeoman/generator-angular/issues/220

2,https://github.com/yeoman/generator-angular/issues/596

but these not same with my issue,so ,i still don't knew what to do.

**Comment by woaixiangbao** [comment]
My npm version is 2.7.1
My bower version is 1.3.12
My grunt version is 0.1.13
My node version is 0.12.0

**Comment by sindresorhus** [comment]
Those are only warnings. You can ignore them. It seems like it installed fine though.

You can try it by running `yo angular`.

**Comment by woaixiangbao** [comment]
@sindresorhus Thank you very much! This confuse me a very long time.

**Comment by poliveira89** [comment]
For this is not just a warning.

After installed a new generator for `yo` I started to get these errors and a bunch of `UNMET DEPENDENCY`.

I tried to install every global again with:

````bash
$ sudo npm update -g generator-mocha
npm WARN peerDependencies The peer dependency yo@>=1.0.0 included from generator-mocha will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! cb() never called!
````

And I still get a lot's of `UNMET DEPENDENCY` on `npm list -g`
