### ISSUE TITLE
Grunt contrib watch not found

### ISSUE THREAD

**Issue by mooru** [yeoman/generator-angular#1040]
When i run grunt serve after installing the angular generator i get this notice 
Local Npm module "grunt-contrib-watch" not found. Is it installed?

I am using nvm installed with homebrew and node 0.12.0. 

How can i rectify this?

**Comment by kevva** [comment]
Like the error message says: is it installed? `npm install grunt-contrib-watch`.

**Comment by mooru** [comment]
It is installed. I have checked node_modules and it is there

**Comment by kevva** [comment]
Try removing your `node_modules` and install again.

**Comment by mooru** [comment]
Done that and it's saying the same thing. Could it the version  of node i am using?
