### ISSUE TITLE
Provide dynamic page title out of the box

### ISSUE THREAD

**Issue by pensierinmusica** [yeoman/generator-angular#1044]
Hi,

I'd propose to modify "generator-angular", so that it provides dynamic page title interpolation right out of the box.

This method seems to gather pretty wide consense: http://stackoverflow.com/a/13407227/570016

Thoughts? Thanks!

**Comment by eddiemonge** [comment]
Thats not always wanted or needed and only works with a router so having even more split paths to maintain isn't fun :(  Plus its an easy enough change for people that want it.

**Comment by pensierinmusica** [comment]
I think it's actually more often wanted or needed than not. But anyways, you guys know best.
