### ISSUE TITLE
Error: invalid option: --import-path=./bower_components

### ISSUE THREAD

**Issue by TWry** [yeoman/generator-angular#1046]
Using a fresh install of npm under windows, I can't get the angular generator to work. It's always giving me this error:

Running "concurrent:test" (concurrent) task
    Warning: Running "compass:dist" (compass) task
Error: invalid option: --import-path=./bower_components

Any idea?

**Comment by sindresorhus** [comment]
Upgrade you Sass.

**Comment by danse** [comment]
Sorry, which version of Sass is expected to work with that option? I have got `Sass 3.4.13 (Selective Steve)`, but i still get the error above. I have Node 0.12, `grunt-contrib-compass` 1.0.3, `generator-angular` 0.11.1
