### ISSUE TITLE
yo fails to install on Windows 7 64 bit

### ISSUE THREAD

**Issue by mongonv** [yeoman/generator-angular#1050]
Hey all,
I have been trying to get nodejs and yeoman running on a Windows 7 64 bit system and cannot figure out why it will not install properly.

Here are all the steps I have been using to clear out previous install attempts and reinstall (I separated the yo, bower, and grunt into separate install calls to get the results of each item before installing yo):

----------------------------------------------------------------------------
Removed the following between installs:
  - Uninstall nodejs from menu option
  - Verified C:\Program Files\nodejs\ was gone
  - Removed npm and npm cache from C:\Users\<user>\AppData\Roaming
  - Verified nodejs and npm folders gone from C:\Users\Ed\AppData\Local and LocalLow
----------------------------------------------------------------------------
Installation Info:  
c:\downloads\node-v0.12.1-x64.msi
Install dir: C:\Program Files\nodejs\
Default options taken:
----------------------------------------------------------------------------
node --version
Result: v0.12.1
----------------------------------------------------------------------------
npm --version
Result: 2.5.1
----------------------------------------------------------------------------
npm install --global bower
Result:
C:\Users\Ed>npm install --global bower
C:\Users\Ed\AppData\Roaming\npm\bower -> C:\Users\Ed\AppData\Roaming\npm\node_modules\bower\bin\bower
bower@1.3.12 C:\Users\Ed\AppData\Roaming\npm\node_modules\bower
+-- is-root@1.0.0
+-- junk@1.0.1
+-- stringify-object@1.0.1
+-- abbrev@1.0.5
+-- chmodr@0.1.0
+-- which@1.0.9
+-- osenv@0.1.0
+-- archy@0.0.2
+-- rimraf@2.2.8
+-- opn@1.0.1
+-- bower-logger@0.2.2
+-- lru-cache@2.5.0
+-- graceful-fs@3.0.6
+-- bower-endpoint-parser@0.2.2
+-- lockfile@1.0.0
+-- nopt@3.0.1
+-- retry@0.6.0
+-- tmp@0.0.23
+-- q@1.0.1
+-- request-progress@0.3.0 (throttleit@0.0.2)
+-- semver@2.3.2
+-- fstream@1.0.4 (inherits@2.0.1)
+-- shell-quote@1.4.3 (array-filter@0.0.1, array-map@0.0.0, array-reduce@0.0.0, jsonify@0.0.0)
+-- bower-json@0.4.0 (intersect@0.0.3, deep-extend@0.2.11, graceful-fs@2.0.3)
+-- chalk@0.5.0 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
+-- p-throttler@0.1.0 (q@0.9.7)
+-- promptly@0.2.0 (read@1.0.5)
+-- mkdirp@0.5.0 (minimist@0.0.8)
+-- bower-config@0.5.2 (osenv@0.0.3, graceful-fs@2.0.3, optimist@0.6.1)
+-- fstream-ignore@1.0.2 (inherits@2.0.1, minimatch@2.0.4)
+-- tar-fs@0.5.2 (pump@0.3.5, tar-stream@0.4.7)
+-- decompress-zip@0.0.8 (nopt@2.2.1, mkpath@0.1.0, touch@0.0.2, readable-stream@1.1.13, binary@0.3.0)
+-- glob@4.0.6 (inherits@2.0.1, once@1.3.1, minimatch@1.0.0)
+-- request@2.42.0 (caseless@0.6.0, json-stringify-safe@5.0.0, aws-sign2@0.5.0, forever-agent@0.5.2, stringstream@0.0.4, oauth-sign@0.4.0, tunnel-agent@0.4.0, q
s@1.2.2, node-uuid@1.4.3, mime-types@1.0.2, form-data@0.1.4, bl@0.9.4, http-signature@0.10.1, tough-cookie@0.12.1, hawk@1.1.1)
+-- bower-registry-client@0.2.4 (graceful-fs@2.0.3, request-replay@0.2.0, lru-cache@2.3.1, mkdirp@0.3.5, async@0.2.10, request@2.51.0)
+-- cardinal@0.4.0 (redeyed@0.4.4)
+-- mout@0.9.1
+-- update-notifier@0.2.0 (semver-diff@0.1.0, string-length@0.1.2, latest-version@0.2.0, configstore@0.3.2)
+-- handlebars@2.0.0 (optimist@0.3.7, uglify-js@2.3.6)
+-- inquirer@0.7.1 (figures@1.3.5, mute-stream@0.0.4, through@2.3.6, readline2@0.1.1, lodash@2.4.1, rx@2.4.7, cli-color@0.3.3)
+-- insight@0.4.3 (object-assign@1.0.0, async@0.9.0, chalk@0.5.1, lodash.debounce@2.4.1, os-name@1.0.3, tough-cookie@0.12.1, configstore@0.3.2, inquirer@0.6.0)
----------------------------------------------------------------------------
bower --version 
Result: 1.3.12
----------------------------------------------------------------------------
npm install --global grunt-cli
Result:
C:\Users\Ed\AppData\Roaming\npm\grunt -> C:\Users\Ed\AppData\Roaming\npm\node_modules\grunt-cli\bin\grunt
grunt-cli@0.1.13 C:\Users\Ed\AppData\Roaming\npm\node_modules\grunt-cli
+-- resolve@0.3.1
+-- nopt@1.0.10 (abbrev@1.0.5)
+-- findup-sync@0.1.3 (lodash@2.4.1, glob@3.2.11)
----------------------------------------------------------------------------
grunt --version
Result: grunt-cli v0.1.13
----------------------------------------------------------------------------
npm install --global yo
Result:
C:\Users\Ed\AppData\Roaming\npm\yo -> C:\Users\Ed\AppData\Roaming\npm\node_modules\yo\lib\cli.js

> yo@1.4.6 postinstall C:\Users\Ed\AppData\Roaming\npm\node_modules\yo
> yodoctor

The system cannot find the path specified.

Yeoman Doctor
Running sanity checks on your system

√ Global configuration file is valid
√ NODE_PATH matches the npm root
√ No .bowerrc file in home directory
√ No .yo-rc.json file in home directory

Everything looks all right!
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global" "yo"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! yo@1.4.6 postinstall: `yodoctor`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yo@1.4.6 postinstall script 'yodoctor'.
npm ERR! This is most likely a problem with the yo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     yodoctor
npm ERR! You can get their info via:
npm ERR!     npm owner ls yo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Ed\npm-debug.log
----------------------------------------------------------------------------

I have tried installing node and yo on a second Windows 7 64 bit system and it installs, but when I try to generate a project, it hangs at a couple of different points in the generation process and never completes.

So I am pretty stuck on what could be wrong, not sure if there is some step I am missing, a problem in the deploy, or what.  

I have been using the steps listed at http://yeoman.io/codelab.html to do the installation and setup of the yo generator.
 
Any help in figuring this out would be greatly appreciated.

**Comment by eddiemonge** [comment]
Please open this issue at https://github.com/yeoman/yo/issues/new although it probably is a npm bug.
