### ISSUE TITLE
Need to correct link from bower_components/whateverResource to ../bower_components/whateverResource

### ISSUE THREAD

**Issue by singh-** [yeoman/generator-angular#1051]
1. yo angular
2. Run app/index.html
3. Check error in consoles. The node resources would not get loaded.
4. In app/index.html, rename all links from  bower_components/whateverResource to ../bower_components/whateverResource, and everything works fine.

Just need to correct all the "bower_components" links in app/index.html

**Comment by eddiemonge** [comment]
They are correct. You don't `run` app/index.html. You run `grunt serve`. Then everything is :smile:
