### ISSUE TITLE
Grunt build problem: space in value attr <option> using ng-repeat

### ISSUE THREAD

**Issue by pc3b3r** [yeoman/generator-angular#1052]
My controller has
```javascript
$scope.opts = [
		"opt1",
		"opt2",
		"opt3",
		"opt4",
		"opt5"
	];
$scope.opt = "opt1";
```
The view is like the following 
```html
<select ng-model="opt">
    <option value="">...</option>
    <option ng-repeat="option in opts">{{option}}</option>
</select>
```
Using `grunt serve` there are no problems and the result is:

![opt](https://cloud.githubusercontent.com/assets/3038109/6917049/69fe43fe-d7a1-11e4-8470-08b4c115e24c.png)

When I run `grunt build` the result is
```html
<select>
    <option value="">...</option>
    <option value="opt1 ">opt1 </option>
    <option value="opt2 ">opt2 </option>
    <option value="opt3 ">opt3 </option>
    <option value="opt4 ">opt4 </option>
    <option value="opt5 ">opt5 </option>
</select>
```
White spaces? Why?

**Comment by eddiemonge** [comment]
if this is valid, then its probably a bug with htmlmin from here https://github.com/yeoman/generator-angular/blob/master/templates/common/root/_Gruntfile.js#L381 
Maybe open an issue with grunt-htmlmin

**Comment by oliverjanik** [comment]
+1

**Comment by eddiemonge** [comment]
Closing since its been opened at htmlmin
