### ISSUE TITLE
Issue with Grunt Serve in my Bootstrap/Angular/Yeoman/Grunt project

### ISSUE THREAD

**Issue by DerekHoffman** [yeoman/generator-angular#1060]
Hi. I had created a Yo Bootstrap angular Less project. I got a new computer and tried copying the files over.

I installed Node / Bower / Grunt and have done a ton of updates and installs to my file path but I cannot seem to get "grunt serve" to pop up a localhost window. I get "Done, without errors".

The only thing I noticed is that it is not going into my "autoprefixer" and "connect:livereload" commands inside grunt serve. Where do I go from here?

grunt serve
Running "serve" task

Running "clean:server" (clean) task
Cleaning .tmp...OK

Running "wiredep:app" (wiredep) task

Running "concurrent:server" (concurrent) task

Running "copy:styles" (copy) task

Done, without errors.

Execution Time (2015-04-10 14:28:27 UTC)
loading tasks 4ms ■■■■■■■■■■■■■■■ 31%
copy:styles 8ms ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 62%
Total 13ms

Here is a Gist of my grunt.js

https://gist.github.com/DerekHoffman/31ca8c25fef564b19fbb

**Comment by eddiemonge** [comment]
It also does not seem to be running your less task either. This is probably a better question for stackoverflow.

**Comment by eddiemonge** [comment]
try running with `grunt serve --verbose` to see if that generates any additional info

**Comment by DerekHoffman** [comment]
Nothing went wrong with that command

**Comment by eddiemonge** [comment]
is your project hosted somewhere public or could you zip and send it?
