### ISSUE TITLE
Couldn't find 'compass' binary

### ISSUE THREAD

**Issue by bobbyziom** [yeoman/generator-angular#1062]
First try with this one. Generated standard project with yo. No alternative modifications. I get this when i run ´grunt serve´:

Running "concurrent:server" (concurrent) task
    Warning: Running "compass:server" (compass) task
    Warning: Couldn't find the compass binary. Make sure it's installed and in your $PATH Use --force to continue.
    
    Aborted due to warnings
  
What's the problem here?

**Comment by sindresorhus** [comment]
Exactly what the error message says:

> Warning: **Couldn't find the compass binary. Make sure it's installed and in your $PATH**
