### ISSUE TITLE
Yo angular

### ISSUE THREAD

**Issue by JRRN** [yeoman/generator-angular#1063]
JRRN commented 28 minutes ago
yo angular

 _-----_
|       |    .--------------------------.
|--(o)--|    |    Welcome to Yeoman,    |
---------´ | ladies and gentlemen! | ( _´U_ ) '--------------------------'
/A\

| ~ |

'._.'__

´ |° ´ Y

Out of the box I include Bootstrap and some AngularJS recommended modules.

? Would you like to use Sass (with Compass)? Yes
? Would you like to include Bootstrap? Yes
? Would you like to use the Sass version of Bootstrap? Yes
? Which modules would you like to include? angular-animate.js, angular-cookies.js, angular-resource.js, angular-route.js, angular-sanitize.js, angular-touch.js
create app/styles/main.scss
create app/index.html
create bower.json
identical .bowerrc
create package.json
create Gruntfile.js
create README.md
invoke angular:common:/usr/local/lib/node_modules/generator-angular/app/index.js
identical .editorconfig
identical .gitattributes
identical .jshintrc
identical .yo-rc.json
identical .gitignore
create test/.jshintrc
create app/.buildignore
create app/.htaccess
create app/404.html
create app/favicon.ico
create app/robots.txt
create app/views/main.html
create app/images/yeoman.png
invoke angular:main:/usr/local/lib/node_modules/generator-angular/app/index.js
create app/scripts/app.js
invoke angular:controller:/usr/local/lib/node_modules/generator-angular/app/index.js
create app/scripts/controllers/main.js
create test/spec/controllers/main.js
module.js:338
throw err;
^
Error: Cannot find module 'lodash'
at Function.Module._resolveFilename (module.js:336:15)
at Function.Module._load (module.js:278:25)
at Module.require (module.js:365:17)
at require (module.js:384:17)
at Object. (/usr/local/lib/node_modules/generator-karma/node_modules/yeoman-generator/lib/env/index.js:6:9)
at Module._compile (module.js:460:26)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Module.require (module.js:365:17)
at require (module.js:384:17)

**Comment by geschwendt** [comment]
try deleting the node_modules folder and running npm install again.

**Comment by sindresorhus** [comment]
Upgrade npm, reinstall the generator.
