### ISSUE TITLE
Generator-angular won't generate.

### ISSUE THREAD

**Issue by dweremeichik** [yeoman/generator-angular#1066]
I receive the following errors when trying to generate a new app. To me it looks like a dependency issue, any ideas?

```
$ yo angular test
(!) #_ is deprecated. Require your own version of Lodash or underscore.string
(!) #_ is deprecated. Require your own version of Lodash or underscore.string
(!) #_ is deprecated. Require your own version of Lodash or underscore.string

C:\Users\Dylan\AppData\Roaming\npm\node_modules\generator-angular\app\index.js:1
5
  this.appname = this._.camelize(this._.slugify(this._.humanize(this.appname))
                                                       ^
TypeError: Cannot call method 'humanize' of undefined
    at new Generator (C:\Users\Dylan\AppData\Roaming\npm\node_modules\generator-
angular\app\index.js:15:56)
    at Environment.instantiate (c:\Users\Dylan\AppData\Roaming\npm\node_modules\
yo\node_modules\yeoman-environment\lib\environment.js:282:10)
    at Environment.create (c:\Users\Dylan\AppData\Roaming\npm\node_modules\yo\no
de_modules\yeoman-environment\lib\environment.js:259:15)
    at Environment.run (c:\Users\Dylan\AppData\Roaming\npm\node_modules\yo\node_
modules\yeoman-environment\lib\environment.js:318:24)
    at c:\Users\Dylan\AppData\Roaming\npm\node_modules\yo\lib\cli.js:86:9
    at Environment.resolver.lookup (c:\Users\Dylan\AppData\Roaming\npm\node_modu
les\yo\node_modules\yeoman-environment\lib\resolver.js:50:12)
    at init (c:\Users\Dylan\AppData\Roaming\npm\node_modules\yo\lib\cli.js:61:7)

    at pre (c:\Users\Dylan\AppData\Roaming\npm\node_modules\yo\lib\cli.js:48:3)
    at Object.<anonymous> (c:\Users\Dylan\AppData\Roaming\npm\node_modules\yo\li
b\cli.js:150:1)
    at Module._compile (module.js:456:26)
```

**Comment by eddiemonge** [comment]
I don't get this. Have you installed custom modules in the generator-angular or something else? Or installed a custom version of `yo`?

**Comment by dweremeichik** [comment]
No custom anything.
Here is my version of node.
```
$ node -v
v0.10.13
```
Now, that got me thinking, as it is outdated and I have another machine with a newer version that works; I decided to update my version on this machine.
With the following version:
```
$ node -v
v0.12.2
```
Perhaps the following needs to be tweaked?
```
  "engines": {
    "node": ">=0.10.0"
  },
```
I'm not sure if there is really any way to zero in on whether it was caused by the version or not.

**Comment by eddiemonge** [comment]
maybe you had something else messed up that upgrading fixed? Can I close this issue then?

**Comment by dweremeichik** [comment]
Yes, Thank you!

**Comment by qlikviewsense** [comment]
Hi, that's my first post.

I've installed yoman, bower etc from scratch :

  npm install -g yo bower grunt-cli gulp

and loaded a yoman angular generator

   npm install -g generator-angular

I've also updated node to v0.12.5 but if i try to install 

   yo angular

I get the same exact error you said it was fixed.
Could you please explain me how i can fix it? It seem the answer you got and lead to the closure of the issue isn't enough ( upgrade node )

Thank you and best regards
 Fabrizio

**Comment by qlikviewsense** [comment]
I got it working, you must install yoman karma generator, it was not stated
