### ISSUE TITLE
Default 'module' creation is deprecated

### ISSUE THREAD

**Issue by superghostmaster** [yeoman/generator-angular#1069]
Your format of creating, for example, a controller:
```
angular.module('angularProjectsApp')
  .controller('MainCtrl', function ($scope) {
    $scope.awesomeThings = [
      'HTML5 Boilerplate',
      'AngularJS',
      'Karma'
    ];
  });

```

... is effectively deprecated.

The current "cool" method is this:

```
var app = angular.module('myApp', []);
```

However, you have dependencies built into the pre-built scaffolding w/in the generator-angular that result in defining a global variable of 'var app....' as above unusable.

I suggest changing this as it makes creation of new controllers, directive, etc. more efficient.

I'm currently working on the latest version of Yeoman, and I'm refactoring my app before continuing so that I an use this method.

**Comment by eddiemonge** [comment]
> is effectively deprecated

How do you figure that? 

>  `var app = angular.module('myApp', []);` 

Only works if you make `app` global or have all your pages concatenated into one with them all having access to the same scope.

Both methods you have here are in use and acceptable.

Thank you for keeping this issue civil btw. Its a nice change.

**Comment by superghostmaster** [comment]
Np.  

But I guess I thought that the way I was trying to do this in Yeoman that all of my pages WOULD have access to the same scope.

The only thing I was trying to do is stay DRY and not rewrite too much; effectively separate the services/controllers/app in separate JS folders for organization.

It seems that when I do this my controller no longer has access to the scope.  When I do this in a raw nodejs/Angular build, it works fine.  Not clear why that is.
