### ISSUE TITLE
General Question --> grunt serve:[target]

### ISSUE THREAD

**Issue by Shawful** [yeoman/generator-angular#1070]
I have noticed that within the gruntfile.js file that there is a command that will accept a target which can be used to serve either the code locally from the distribution folder or the code in the app folder.  

I cannot get this to function with the command <code>grunt serve:app</code> or <code>grunt serve:dist</code>.

Is there a recommended way to accomplish serving each of these targets?  What am I doing incorrectly?  Is there a missing step somewhere?

Thanks!

**Comment by Shawful** [comment]
The reference to gruntfile.js is on lines 393 - 396 and 408 - 411.

**Comment by eddiemonge** [comment]
`grunt serve:dist` should work. What happens when you run it? `grunt serve:app` will not do anything since its either `grunt serve` to serve your app while in development mode or `grunt serve:dist` to serve up the built site.

**Comment by Shawful** [comment]
When I run the <code>grunt serve</code> command, I get the site to load correctly (as far as I can tell right now).  When I run <code>grunt serve:dist</code>, I get the following:

![image](https://cloud.githubusercontent.com/assets/5322272/7378350/66bd3c50-edb2-11e4-99af-8839870637a8.png)

**Comment by Shawful** [comment]
So at least grunt completing the minification step (as evidenced by generating an error in  scripts.78658e8c.js, the compressed file), but why would angular not be defined?  I haven't changed any code. :(

**Comment by eddiemonge** [comment]
You didnt change any code at all since generation?

**Comment by Shawful** [comment]
When I run the same process on a blank project, I see the following error:

![image](https://cloud.githubusercontent.com/assets/5322272/7380134/6c4440f8-edbf-11e4-8605-de8e6e3909ab.png)

The difference between the clean project and my project is that my project has had the original 'app' folder deleted and substituted with the 'app' folder from a previous project.

My confusion comes from when I experience the "angular is not defined" error only when running <code>grunt serve:dist</code> and somehow, running <code>grunt serve</code> does not produce the "angular is not defined" error.

**Comment by eddiemonge** [comment]
Is angular being included in the build?

**Comment by Shawful** [comment]
I checked within Chrome dev tools to find out if angular was being included in the build.  I assume that the compressed version of Angular would be in the scripts folder being served from the 'dist' folder. There are two files contained within my scripts folder: scripts.[randomNumbers].js and vendor.[randomNumbers].js.  

It turns out that vendor.[randomNumbers].js is completely empty, but I imagine that this file should contain compressed versions of dependencies (such as angular).

Do you know what might cause the vendor.[randomNumbers].js file to be empty?

**Comment by Shawful** [comment]
I think it may have something to do with this issue, posted below:

grunt build not populating vendor.js
https://github.com/DaftMonk/generator-angular-fullstack/issues/164

I'll look into it and post the result.

**Comment by Shawful** [comment]
dei79's comments on Jun 17, 2014 from the previously mentioned generator-angular-fullstack issues page resolved my issue!  I appreciate your patience and all of your help!
