### ISSUE TITLE
Facebook auth error when there is no email

### ISSUE THREAD

**Issue by balasan** [yeoman/generator-angular#1072]
I noticed some users are disable 'provide my email' when logging in with facebook.
This throws an error in the auth/facebook/passport.js because profile.emails is undefined
line 22
```javascript
email: profile.emails[0].value 
```
replacing it with
```javascript
email: profile.emails? profile.emails[0].value : profile.id,
```
solves the problem
*don't leave email blank or null because that will fail the user model validation in user.model.js

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/yeoman
Paste in the link to the question here so others can follow ;)
