### ISSUE TITLE
Problema with the $scope in Step 6

### ISSUE THREAD

**Issue by pmareke** [yeoman/generator-angular#1073]
Hi, first of all thanks for the generator! It's so awesome and for the beginners like me is quite helpful!

In refer to the error I had a problem with the $scope in the Step 6 because when I added item to the "todos" the $scope.todo was undefined.

So I had to change the position of the ng-controller="MainCrtl" to inside of the main.html instead of index.html container.

Thanks again!

**Comment by eddiemonge** [comment]
Is it the same as this issue https://github.com/yeoman/yeoman.io/pull/361  ? Also, closing this as its a Yeoman tutorial issue, not generator-angular issue.

**Comment by pmareke** [comment]
Ok thanks.
