### ISSUE TITLE
Modals from Mobile Angular UI are not shown after grunt build

### ISSUE THREAD

**Issue by tvanesse** [yeoman/generator-angular#1078]
I have got an angular project with both mobile and desktop views. The mobile templates heavily rely on [`mobile-angular-ui`](http://mobileangularui.com/) and it works just fine **in development**.

For some reason the [modals](http://mobileangularui.com/docs/#modals-and-overlays) are not displayed **after `grunt build`**. Instead, calling a modal would act as if a transparent component was added on top of the page (I mean, with the highest z-index), stealing the focus in the same way that a modal would do. As a consequence, the modal itself is not displayed and the page does not respond to any click event (assuming the fake modal is locking the focus).

The content of my modals is loaded via `ng-include` directives and it seems to work (from what I can see in the network tool of Chrome). There are no error message complaining about a missing resource in the console and the only thing I can think of is that the code responsible for toggling the modals visibility in `mobile-angular-ui` was somehow impacted by the build process. Sounds possible?

Any idea of what could cause this difference of behaviour between dev and production?

Here is my [Gruntfile.js](https://gist.github.com/tvanesse/3138ddb851b92a2c3538). I am using `mobile-angular-ui` 1.2.0-beta.11.

**Comment by arthurvr** [comment]
> Sounds possible?

This does sound possible although this might be just an issue with the way you included the dependency.  How did you include the dependency?

**Comment by tvanesse** [comment]
> How did you include the dependency?

Like this:

```javascript
angular
  .module('myApp', [
    ...,
    'mobile-angular-ui',
    ...
  ])
```

Not sure if it's what you are asking for though...

**Comment by eddiemonge** [comment]
This is more of a stackoverflow question. Are you installing that via bower?

**Comment by tvanesse** [comment]
I am indeed installing this via bower.

> This is more of a stackoverflow question.

As my app is working fine in development but fails only after `grunt build` (i.e., a task provided by this generator), I thought it *might* be a bug related to `generator-angular` and not `mobile-angular-ui`. That is why I opened an issue here.

If you can tell for sure that the problem arises from the way I installed `mobile-angular-ui`, then I apologize for asking the question at the wrong place. I will open a ticket SO anyway.

**Comment by tvanesse** [comment]
Just in case someone else lands here, the problem was finally solved. The issue actually came from **a clash between `mobile-angular-ui` and `bootstrap`**. For some reason the clash only appears after the build but yeoman should not be charged with any responsibility in this matter. More details in [this SO ticket](http://stackoverflow.com/questions/30123170/modals-do-not-show-up-after-grunt-build-in-a-yeoman-app/30124259#30124259).
