### ISSUE TITLE
Size of scaffolded project is massive

### ISSUE THREAD

**Issue by marcofaion** [yeoman/generator-angular#1089]
Hi,

i've generated a new application with the generator and found that a new project scaffolded this way is about 200Mb, most of the weight reside in the node_modules directory.

Is that normal? i'm asking cause i've some trouble importing such massive project inside eclipse ide.

Thanks for any info.

**Comment by sindresorhus** [comment]
Ouch. That's huge. I'm getting even worse *327 MB!*

I've looked into this for you and it seems like there's a few big offenders:

- https://github.com/btford/grunt-google-cdn/issues/62
- https://github.com/passy/google-cdn/issues/27
- https://github.com/karma-runner/karma/issues/1220#issuecomment-102367248
- https://github.com/imagemin/imagemin/issues/97

What might help a little bit is to run `$ npm dedupe` and it will deduplicate duplicate dependencies. It brought the size down to *190 MB* for me. Still way too much though.

**Comment by marcofaion** [comment]
thanks you, i've tried to run "npm dedupe" but the size has not changed :( it's still 196,9Mb

**Comment by sindresorhus** [comment]
@marcofaion Make sure you're running the latest version of node and npm.

**Comment by marcofaion** [comment]
@sindresorhus 

$ node -v
v0.10.36
$ npm -v
2.7.6

Maybe not the latest, anyway, if the size of the yeoman generated project is correct, maybe i've to use another ide to manage it.

**Comment by sindresorhus** [comment]
@marcofaion The size is not correct, but we'll have to wait on the referenced tickets to be fixed. That should get the size down 90%.

**Comment by eddiemonge** [comment]
This ticket is rather broad and the correct steps have been taken in the other projects.

**Comment by abhishek0589** [comment]
This issue still persists. 

Node- 4.4.3
npm- 3.8.6
grunt cli- 1.2
grunt-0.4.5

The size of simple todo app described in Yeoman tutorial is going to 190 MBs. I have also tried npm dedupe but it did change anything. Please refer attachment.

![image](https://cloud.githubusercontent.com/assets/10354376/14589360/8ecf1688-04fd-11e6-822a-c6c51af71e50.png)

**Comment by sindresorhus** [comment]
@abhishek0589 The linked issues btford/grunt-google-cdn#62, https://github.com/passy/google-cdn/issues/27, and https://github.com/imagemin/imagemin/issues/97, are still not fixed. Help out on them if you want to see this resolved.
