### ISSUE TITLE
error while generating angular project

### ISSUE THREAD

**Issue by zishanj** [yeoman/generator-angular#1093]
I am using latest 1.4.6 version of `yeoman` and my `npm` is 2.10.0 on Ubuntu 14.04 LTS (64bit). While generating angular project I am getting following error:

    events.js:72
        throw er; // Unhandled 'error' event
              ^
    Error: spawn ENOENT
        at errnoException (child_process.js:1011:11)
        at Process.ChildProcess._handle.onexit (child_process.js:802:34)

**Comment by eddiemonge** [comment]
Did you try again?

**Comment by zishanj** [comment]
yes... I re-install those packages but still no luck. Finally I gave up and now I am using `bower` and `gulp` with self-created config files. :(

**Comment by zishanj** [comment]
On a side note, this latest version of Yeoman as some other issues also. It was also showing `conflict issue with package.json` and I am also receiving following message:

    npm WARN optional dep failed, continuing imagemin-gifsicle@4.1.0
    npm WARN optional dep failed, continuing imagemin-jpegtran@4.1.0
    npm WARN optional dep failed, continuing imagemin-optipng@4.2.0

**Comment by kevva** [comment]
That's because of imagemin. It's looks like your system isn't supported, but it surprises me since I run Ubuntu too and it's working just fine. Anyway, not an issue for this project.

**Comment by zishanj** [comment]
What? Imagemin is a library to minimize the image. It's not a hardware related application.

**Comment by kevva** [comment]
I'm the author of imagemin. We are using binaries and some of them failed to install on your system.

**Comment by zishanj** [comment]
It only works if I degrade to some older version.

**Comment by jeonghwan-kim** [comment]
+1
