### ISSUE TITLE
Build of the app is too slow

### ISSUE THREAD

**Issue by bitliner** [yeoman/generator-angular#1094]
It is mainly an issue from uglify2, i described it [here](https://github.com/mishoo/UglifyJS2/issues/718) (tl;dr: uglify2 is too slow when files are too many. these files are not already minified).

But because you take care of how the build process runs (and you choose the module inside Gruntfile) I was thinking it is a good thing to notify this issue also here.

I was wondering: 

* how much do you consider it a big problem? 
* are you already working on something to speed the build process up?
* is there anything in the development roadmap related to this issue that I could take care of and anticipate its development?

**Comment by arthurvr** [comment]
> are you already working on something to speed the build process up?

I wonder how many we'll improve with the planned switch to gulp.  (https://github.com/yeoman/generator-angular/pull/837)

> are you already working on something to speed the build process up?

Gulp, I guess. Though other improvements are also welcome. https://github.com/yeoman/generator-angular/issues/1089 might also make sense to you.

> is there anything in the development roadmap related to this issue that I could take care of and anticipate its development?

All contributions are welcome! Check the open issues, but mainly https://github.com/yeoman/generator-angular/issues/553.

**Comment by eddiemonge** [comment]
>  planned switch to gulp

its not a switch but an option to choose either.

> 50 files doesn't seem like a big deal, but of course it depends on how much code is in each. We use UglifyJS2 on a pretty big codebase (over 200 files totaling around 5M; the minified file is 2M) and the speed is acceptable (~40 sec. to get the compressed file).

This is computing time here. To make minification faster would be up to uglify to optimize. There isn't much we can to improve that. Look at how long compiling C or Java things take. Whats fast to you might be slow to others so this is very subjective. Waiting a few seconds to me is acceptable when the end result is so nice

**Comment by bitliner** [comment]
@eddiemonge how are you sure that is computing time that causes my build lasting 5minutes?

From the comment you cited, it looks like it is the opposite (because of grunt). Indee the same number of files is much faster using only raw uglify2.

I would be really eager to help you switch to gulp or add integration (once I can prove that the slowness is because of it).
How could I understand at which point is the current support for gulp?

**Comment by eddiemonge** [comment]
Can you put together a test using grunt with only uglify and see you can reproduce the 'slowness'. This is probably better answered on grunt-contrib-uglify though. Switching to gulp won't really help in this situation. Either its a bug in gcu or uglify is slow and it won't matter because gulp will have the same issues.
