### ISSUE TITLE
Cannot find module 'ansi-regex' at Function.Module._resolveFilename (module.js:336:15)

### ISSUE THREAD

**Issue by mcpDESIGNS** [yeoman/generator-angular#1097]
![yoang](https://cloud.githubusercontent.com/assets/2574412/7820280/7a7a7b68-03b5-11e5-853f-dc2769c37973.png)

I've tried using the most recent generator and even 0.10.0 but it doesn't seem to be able to get past this line when creating everything.

Cannot find module 'ansi-regex' at Function.Module._resolveFilename (module.js:336:15)

Any ideas if this is known issue?
Windows 7, 32bit machine here.

It worked when I tried version 0.7.0 but that's a very dated one!

**Comment by eddiemonge** [comment]
Try `npm install ansi-regex`. Seems like maybe some of your modules didn't get installed. What verison of things are you using (npm, node)

**Comment by sindresorhus** [comment]
You seem to have suffered an npm install corruption. Upgrade to latest Node.js and npm (`$ npm install -g npm`) and reinstall.

npm support: https://github.com/npm/npm/issues
