### ISSUE TITLE
Grunt serve error with concurrent:server task

### ISSUE THREAD

**Issue by jamesla** [yeoman/generator-angular#1104]
When I run grunt serve I get this error message:
 
        Running "concurrent:server" (concurrent) task
            Verifying property concurrent.server exists in config...OK
                Files: [no src] -> server
                Options: limit=16
                   Warning:  Use --force to continue.
        
        Aborted due to warnings.
    
It works fine when I run grunt serve --force or if I run the task independently with grunt concurrent:server

I have updated NPM, gem packages, bower packages and can't seem to work out what is causing this or where to look to get a proper error message. Is anybody able to shed any light on where I could look into next?

**Comment by jamesla** [comment]
bump

**Comment by kevva** [comment]
https://github.com/yeoman/generator-angular/issues/660
