### ISSUE TITLE
Update to Angular 1.4

### ISSUE THREAD

**Issue by ADLR-es** [yeoman/generator-angular#1105]
I've been searching through the repo but I didn't find any issue to take care of this. I saw in the source that this generator installs Angular 1.3. Are there plans to upgrade Angular in this generator? Maybe to adopt the components folder structure to ease migration in the future?

If this is a new issue not talked about before, I could help with a pull request. But I prefer to hear from you to not overlap, just in case you are already thinking about how to tackle this.

Thanks!

**Comment by cebor** [comment]
`^1.3.0` will install 1.4

**Comment by ADLR-es** [comment]
Oh, I see. Do we know anything about the components folder structure to be able to easily migrate to ngNewRouter and Angular 2?

**Comment by eddiemonge** [comment]
No, not yet and it shouldn't be required for those at the moment.
