### ISSUE TITLE
When start generate yo angular its puts all generated files of app in wrong directories

### ISSUE THREAD

**Issue by vladymy** [yeoman/generator-angular#1106]
When start generate "yo angular" its puts all generated files of app in wrong directories.

What I did : 

    mkdir mvmNg && cd $_
    yo angular

the path to mvmNg folder is ~/Documents/mvmNG (Ubuntu) but when I run 

    yo angular 

all files puts in ~/Documents. so I get ~/Documents/app folder ~/Documents/node_modules etc.

**Comment by eddiemonge** [comment]
Check your ~/Documents folder for a .yo-rc.json file. The files will be created in whatever parent folder has that file in it.

**Comment by vladymy** [comment]
Yeahhh... thats help! Many Thanks! (y)
