### ISSUE TITLE
Dist version of app, does not restrict the direct folder access

### ISSUE THREAD

**Issue by deveshsinghal22** [yeoman/generator-angular#1107]
Hello all,
I am facing this issue for my angular app. 
Dist version of app, does not restrict the direct folder access. 
so www.mysite.com/scripts /images /styles folder are accessible.  This issue is not coming in development i.e.  grunt serve
this is coming in grunt serve:dist

**Comment by eddiemonge** [comment]
`grunt:serve` should not be a production server. Your actual server should restrict access. But anything in dist should be publicly available since that is all the built files and not the source files.

**Comment by deveshsinghal22** [comment]
Thanks @eddiemonge . I will use express for production server. 
Thanks for your response. :)
