### ISSUE TITLE
Error: [$injector:unpr] Unknown provider: $stateProvider

### ISSUE THREAD

**Issue by tamaghna91** [yeoman/generator-angular#1111]
Could you help me a little more,my problem is not persisted as i have written like this which throws the error:

angular.module('spBlogger.posts').config(['$stateProvider','$locationProvider',
function($stateProvider,$locationProvider){ 
$stateProvider.state('allPosts',{
url:'/posts',
templateUrl: 'modules/posts/views/posts.html',
controller: 'PostController'
});
$stateProvider.state('singlePost',{
url:'/posts/:id/:permalink',
templateUrl: 'modules/posts/views/singlePost.html',
controller: 'PostDetailsController'
});
}]);
![screenshot from 2015-06-12 14 56 47](https://cloud.githubusercontent.com/assets/8926058/8144232/833756ec-11f0-11e5-9761-078f83193b25.png)

**Comment by sindresorhus** [comment]
Support questions are better asked on http://stackoverflow.com/questions/ask
