### ISSUE TITLE
Drop CoffeeScript in favor of ES6 (Babel)

### ISSUE THREAD

**Issue by silvenon** [yeoman/generator-angular#1112]
Ref. https://github.com/yeoman/generator-webapp/pull/543#issuecomment-111724489.

**Comment by arthurvr** [comment]
@silvenon This should happen at the same time as we handle https://github.com/yeoman/generator-angular/issues/1091 so let's close this issue and handle it there?

**Comment by silvenon** [comment]
Whoops, didn't search.
