### ISSUE TITLE
views/main.html not working

### ISSUE THREAD

**Issue by aneeshjajodia** [yeoman/generator-angular#1113]
While I tried to get this this thing working using the specific commands from the website itself, I came across an error of nothing coming up on the *grunt serve* page, the splendid and stuff.

Would be glad if someone could help me through.

![screenshot 2015-06-15 01 47 41](https://cloud.githubusercontent.com/assets/1062704/8150261/8c0e850e-1300-11e5-904e-d1589877f103.png)

**Comment by arthurvr** [comment]
Tends to work fine for me.

Can you provide some more info please? Did you make any modifications to what the generator scaffolded? Did yo throw anything unusual while scaffolding? Are you seeing any errors in your console? What version of generator-angular were you using?

**Comment by ph3b** [comment]
I'm getting the same problem. The views doesn't seem to render inside the <div ng-view=""></div>. No errors in console. Generated angular-app using 2.5.1.

**Comment by eddiemonge** [comment]
Closing this as it doesnt seem to be reproduceable

**Comment by Abhinav2510** [comment]
when I add a dependency like angular.module('neveralonedashApp', ['ngMap']) ng-view let of work

**Comment by josco007** [comment]
angular.module('neveralonedashApp', ['ngMap'])

**Comment by josco007** [comment]
when I use a dependency like angular.module('neveralonedashApp', ['ngMap']) ng-view let of work
