### ISSUE TITLE
peerDependencies error

### ISSUE THREAD

**Issue by aneeshjajodia** [yeoman/generator-angular#1114]
Hello

What could be the reason behind the following errors?

![screenshot 2015-06-15 02 14 52](https://cloud.githubusercontent.com/assets/1062704/8150377/821539c2-1304-11e5-91d5-189d9fcef580.png)

**Comment by arthurvr** [comment]
This aren't errors, just warnings. We actually plan to fix all of these but are still discussing how: https://github.com/yeoman/yeoman/issues/1488.
