### ISSUE TITLE
Can NOT load jquery#2.1.4 bower_components/jquery while running "yo angular app-name"

### ISSUE THREAD

**Issue by inthra-onsap** [yeoman/generator-angular#1117]
As I said, I get stuck at starting project state.
After I run command "yo angular app-name". I can not download "jquery#2.1.4 bower_components/jquery". Could you let me know how to fix it?

**Comment by arthurvr** [comment]
So, the scaffolding completes but it fails while running the bower installation?

**Comment by inthra-onsap** [comment]
It work NOW. It was my own fault. I fixed by installing a new node & npm from scratch.
