### ISSUE TITLE
Angular filter not work after build

### ISSUE THREAD

**Issue by truongces** [yeoman/generator-angular#1123]
Hi,

I use yeoman to generate my angular project. 
I write the filter look like this http://plnkr.co/edit/auusXT5WXO71jzfm3kvb?p=preview
It work great. But if I run command `grunt build` to production build, the filter didn't work.

Please help me solve this issue.Thanks.

**Comment by eddiemonge** [comment]
Its because of htmlmin. Setting: `removeOptionalTags: false` fixes it. I think this is a bug in Angular though. For now you can set the option to false but you should open an issue with Angular.

**Comment by truongces** [comment]
It worked. Thanks so much :)
