### ISSUE TITLE
Tests do not create new $scope for controller

### ISSUE THREAD

**Issue by excentris** [yeoman/generator-angular#1130]
Running the `grunt` command on a clean install fails due to jshint errors:

```
test/spec/controllers/about.js
  line 11  col 44  '$rootScope' is defined but never used.

test/spec/controllers/main.js
  line 11  col 44  '$rootScope' is defined but never used.

  ⚠  2 warnings

Warning: Task "jshint:test" failed. Use --force to continue.

Aborted due to warnings.
```
The problem is straightforward to fix, but would be nice if a clean install would lead to a fully working example.

**Comment by arthurvr** [comment]
> The problem is straightforward to fix, but would be nice if a clean install would lead to a fully working example.

Isn't it normal that there are unused variables when you didn't develop your application yet? In generator-node we decided that it's okay: https://github.com/yeoman/generator-node/issues/121#issuecomment-116826438.

**Comment by excentris** [comment]
> Isn't it normal that there are unused variables when you didn't develop your application yet?

@arthurvr Yes, I agree. I just found it weird. I didn't expect anything to fail with a freshly generated app. Maybe something to mention on the documentation as some kind of guideline for what to do and what not to do when creating new generators?

**Comment by arthurvr** [comment]
I'm unsure myself. We could just stick in a JSHint ignore comment as well.

**Comment by eddiemonge** [comment]
It seems like the controller tests are missing the part to create a new scope for the controller. That should/could be added

**Comment by excentris** [comment]
I have submitted a PR (#1131) that I think is the right fix for this.
