### ISSUE TITLE
Why angular generator doesn't already upgrade to postcss?

### ISSUE THREAD

**Issue by 5amfung** [yeoman/generator-angular#1132]
Why angular generator doesn't already upgrade to postcss?  I would like to see get rid of this warning.  Should I upgrade to postcss?  Does anyone have any pointer to doing so?  Thanks in advance.

    Running "autoprefixer:server" (autoprefixer) task
    Autoprefixer's process() method is deprecated and will removed in next major release. Use   postcss([autoprefixer]).process() instead
    File .tmp/styles/main.css created.

I used angular generator 0.11.0

**Comment by eddiemonge** [comment]
Because it takes time to put something like that in and time is something we have in very short supply.

**Comment by 5amfung** [comment]
Sounds fair.  I thought it's something I messed up on my side.
