### ISSUE TITLE
vendor.js is empty after grunt build.

### ISSUE THREAD

**Issue by 5amfung** [yeoman/generator-angular#1133]
Using 0.12.0.

vendor.js is empty after grunt build.  So is vendor.css.

**Comment by 5amfung** [comment]
Looks like if I removed '(.)' from the line, it would work.  Should I submit a PR?

    

https://github.com/yeoman/generator-angular/blob/master/templates/common/app/index.html#L78

**Comment by arthurvr** [comment]
It's added in this commit: https://github.com/yeoman/generator-angular/commit/27dd848f58c45ba5536da502bfd5a147ced35572

**Comment by 5amfung** [comment]
@arthurvr I'm not sure if I understood your comment.  Are you just pointing out where '(.)' was added?  Or are you suggesting that because '(.)' was added for a reason in the past such that we should not fix the issue now by removing it?  Please clarify.  Thanks.

**Comment by arthurvr** [comment]
@5amfung Yep, if you look at the commit I linked, you'll see an explanation why the `(.)` is there and why we can't just remove it.

**Comment by 5amfung** [comment]
@arthurvr What would you suggest to resolve an empty vendor.js if I can't simply remove `(.)`?  I would imagine other users having the same issue.  I want to help if you could point me to the right direction.

**Comment by arthurvr** [comment]
If I would know how to fix this issue I would already have done that ;) I'm unable to reproduce this. On what version of generator-angular are you? What prompts have you enabled/disabled when running the generator? Does grunt throw any errors?

**Comment by eddiemonge** [comment]
Try updating to 0.12.1 and see if that fixes it

**Comment by eddiemonge** [comment]
@5amfung ^^

**Comment by 5amfung** [comment]
So I took the pain to regenerate the whole project using 0.12.0.  Empty vendor.js problem was resolved.  Thanks for the help.

**Comment by arthurvr** [comment]
Glad it's resolved.
