### ISSUE TITLE
No styles after creating initial project

### ISSUE THREAD

**Issue by wilsonbradleyc** [yeoman/generator-angular#1134]
I'm working through 'Professional AngularJS' (Wrox).

After creating the initial project using 'yo angular StockDog', the appropriate css is not found for the angular app.  I started this conversation [here](https://github.com/yeoman/generator-webapp/issues/211) but was told that this is a problem with generator-angular and not generator-webapp.

During set up, I did not include Sass w/Compass, but did select to use Bootstrap.

**Comment by arthurvr** [comment]
Are all other files there?

**Comment by wilsonbradleyc** [comment]
Sorry - not sure which other files you're looking for.  (complete newbie here)

**Comment by arthurvr** [comment]
@wilsonbradleyc Maybe show us the file tree of the generated files? I'd just like to see if all other files were scaffolded.

**Comment by wilsonbradleyc** [comment]
The entire tree is quite large (too large to paste here IMO).  Any specific folders you want me to show?
.
├── app
│   ├── 404.html
│   ├── .buildignore
│   ├── favicon.ico
│   ├── .htaccess
│   ├── images
│   │   └── yeoman.png
│   ├── index.html
│   ├── robots.txt
│   ├── scripts
│   │   ├── app.js
│   │   ├── controllers
│   │   ├── directives
│   │   │   └── stk-watchlist-panel.js
│   │   └── services
│   │       └── watchlist-service.js
│   ├── styles
│   │   └── main.css
│   └── views
│       └── templates
│           ├── addlist-modal.html
│           └── watchlist-panel.html

**Comment by arthurvr** [comment]
> │   ├── styles
│   │   └── main.css

Seems like it's there :)

**Comment by wilsonbradleyc** [comment]
There is also a directory in the root of the app named .tmp that looks like this:

├── .tmp
│       │   │   │   │   │   └── styles
│       │   │   │   │   │       └── main.css

**Comment by arthurvr** [comment]
What do you see in the browser console when doing `grunt serve`?

**Comment by eddiemonge** [comment]
What version did you install? Bootstrap had an issue we put a workaround in for in the latest

**Comment by wilsonbradleyc** [comment]
found this in angular.js:

`@import url(../../components/bootstrap-3.1.1/css/bootstrap.css);`

**Comment by wilsonbradleyc** [comment]
console after running grunt serve:

brad@brad-HP-EliteBook-Folio-9470m:~/StockDog$ grunt serve
Running "serve" task

Running "clean:server" (clean) task
>> 1 path cleaned.

Running "wiredep:app" (wiredep) task

Running "wiredep:test" (wiredep) task

Running "concurrent:server" (concurrent) task
    
    Running "copy:styles" (copy) task
    Copied 1 file
    
    Done, without errors.
    
    
    Execution Time (2015-07-05 22:07:03 UTC)
    loading tasks   4ms  ▇▇▇▇▇▇▇▇▇▇ 21%
    copy:styles    14ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 74%
    Total 19ms
    
Running "autoprefixer:server" (autoprefixer) task
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
File .tmp/styles/main.css created.

Running "connect:livereload" (connect) task
Started connect web server on http://localhost:9000

Running "watch" task
Waiting...

**Comment by silsha** [comment]
Have you seen this issue? #1116

**Comment by eddiemonge** [comment]
Again, what version are you using since this was fixed recently

**Comment by wilsonbradleyc** [comment]
I'm not sure which version you are asking for.  Let me which framework you're wanting the version of... here are a few from my machine:

node: v0.12.5
npm: 2.12.0
git: 1.9.1
yo: 1.4.7
bower: 1.4.1
grunt-cli: v0.1.13
grunt: v0.4.5

**Comment by arthurvr** [comment]
That's a bunch of version numbers but not the one we need :stuck_out_tongue_winking_eye: Can you give us the output of this command:

 ```
$ npm info generator-angular | grep 'version:'
```

**Comment by wilsonbradleyc** [comment]
:)

version: '0.12.0',

**Comment by eddiemonge** [comment]
can you post your project online somewhere so we can inspect it and try to reproduce this?

**Comment by eddiemonge** [comment]
Try updating to 0.12.1 and see if that fixes it

**Comment by wilsonbradleyc** [comment]
Updating to 0.12.1 didn't work.  Output from
`brad@brad-HP-EliteBook-Folio-9470m:~/StockDog$ npm info generator-angular | grep 'version:'`
  `version: '0.12.1',`

**Comment by wilsonbradleyc** [comment]
I uploaded the project as a zip to Dropbox.  It can be downloaded from here:

https://www.dropbox.com/s/cha6x70nnmkd6gc/StockDog.zip?dl=0

**Comment by wilsonbradleyc** [comment]
I just replaced bootstrap 3.3.5 with 3.3.4 and now the CSS is being applied.  

By replace, I mean I downloaded bootstrap 3.3.4 zip, extracted it, and replaced the /bower_components/bootstrap folder with the 3.3.4 version.

**Comment by eddiemonge** [comment]
You updated to 0.12.1 but you didnt generate a new project using that version. Your gruntfile says 0.11.1. Updated, generated a new site and then copied your site in. Works as expected.

**Comment by zaphinath** [comment]
I have the same problem. I have generator-angular 0.12.1 and created a new project. Then I look at the grunt file and it says 0.11.1 still. How do I get the newer version to be reflected in a new project?

**Comment by Gregerl01** [comment]
After initial grunt serve command, I didn't have any bootstrap styling until I replaced bootstrap original version with 3.3.4 manually, then it worked.
