### ISSUE TITLE
Plugin for the "ngtemplates" task not found in v0.12.0 

### ISSUE THREAD

**Issue by 5amfung** [yeoman/generator-angular#1135]
I got the following error from running `grunt build` immediately after creating a new project (no to compass, yes to bootstrap).  Should I use --force to ignore the error, or there's something I have to install and tweak?

    jit-grunt: Plugin for the "ngtemplates" task not found.
    If you have installed the plugin already, please setting the static mapping.
    See https://github.com/shootaroo/jit-grunt#static-mappings

    Warning: Task "ngtemplates" failed. Use --force to continue.

**Comment by 5amfung** [comment]
Looks like a few plugins don't work well.  I had to add the following to Gruntfile.js to make `grunt build` to get past the errors.  I know this generator is open source but I'm sad to see how buggy it is that it doesn't necessarily work right of the box.

require('jit-grunt')(grunt, {
    useminPrepare: 'grunt-usemin',
    ngtemplates: 'grunt-angular-templates',
    cdnify: 'grunt-google-cdn'
  });

**Comment by arthurvr** [comment]
This should have been fixed in https://github.com/yeoman/generator-angular/commit/3eb78fe9eea461fcb1b97eae49382657e6446370, isn't it?

**Comment by eddiemonge** [comment]
Yeah it looks like you dont have 0.12.0. Can you do `npm info generator-angular | grep 'version:'`

**Comment by 5amfung** [comment]
Pretty sure I had 0.12.0 when I got the error.  Because I ran `grunt build` right after I generated the project.

    $ npm info generator-angular | grep 'version:'
      version: '0.12.0',

**Comment by eddiemonge** [comment]
Your gruntfile should have had that at the top of it then

**Comment by eddiemonge** [comment]
ok it shouldn't have but if you update the generator now it should.

**Comment by ryan4888** [comment]
I am getting this error now. I'm running 0.12.1.

**Comment by javarch** [comment]
Ich werde ab  16.09.2015 nicht im B�ro sein. Ich kehre zur�ck am
12.10.2015.
Ich werde Ihre Nachricht nach meiner R�ckkehr beantworten.

Die R�ckmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [generator-angular] Plugin for the "ngtemplates" task not found in
v0.12.0  (#1135)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2015 Agent 'Abwesenheit'

Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
DVR: 0572934, UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angef�hrten Absender via E-Mail
dient ausschlie�lich Informationszwecken. Rechtsgesch�ftliche Erkl�rungen
d�rfen �ber dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
