### ISSUE TITLE
Cannot delete project folder created with generator on Windows

### ISSUE THREAD

**Issue by simonech** [yeoman/generator-angular#1137]
I wanted to delete a project folder I created with the angular generator, and on Windows it fails as some files exceed max path length.
Inside the node_modules there is module called "grunt-contrib-imagemin" which has another node_modules folder with a package "imagemin" with other 3 packages, one per file format, which are all like this
```
C:\Users\user\DOCUME~1\newtodo\NODE_M~1\GRE7EF~1\NODE_M~1\imagemin\NODE_M~1\IMAGEM~3\NODE_M~1\gifsicle\NODE_M~1\BIN-BU~1\NODE_M~1\download\NODE_M~1\GULP-D~1\NODE_M~1\GULP-U~1\NODE_M~1\MULTIP~1\NODE_M~1\DUPLEX~1\NODE_M~1\READAB~1\NODE_M~1\isarray\build
```

**Comment by arthurvr** [comment]
This is a [known](https://github.com/npm/npm/issues/5641) npm issue. It's a windows/npm bug, we can't really fix that, sorry.
