### ISSUE TITLE
When doing a grunt dist fontawesome icons are multiplied over the site

### ISSUE THREAD

**Issue by marcbosserhoff** [yeoman/generator-angular#1138]
I have the problem, when using font-awesome the i-tags were bloated/multiplied in the dist version with grunt. In chrome dev tools i can see that there are 3 tags where i just defined one.

![bildschirmfoto 2015-07-13 um 03 28 30](https://cloud.githubusercontent.com/assets/1201676/8641147/65cd58b4-290f-11e5-9b26-92d5934cca4c.png)

Why is that?

**Comment by eddiemonge** [comment]
Without knowing your code, couldn't tell you.

**Comment by marcbosserhoff** [comment]
Ok, i found it myself. I am not allowed to write self-closing tags (which seems to be ok at first look, as i have empty tags) but is also not allowed by w3c markup validation. Fixing that and everything went ok in the build. When developing in my "app"-folder the problem didn't occur.
