### ISSUE TITLE
The generator doesn't include bootstrap.css in index.html

### ISSUE THREAD

**Issue by thepulkitagarwal** [yeoman/generator-angular#1139]
The generator doesn't add `bootstrap.css` to the `index.html` page even after the scaffolding is complete, i.e., `<link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.css">` has to be added to the index.html page.

I followed the instructions on http://yeoman.io/codelab/preview-inbrowser.html

**Comment by eddiemonge** [comment]
You have to use the latest version of this as bootstrap changed their bower file.
