### ISSUE TITLE
Changing default folders locations ..?

### ISSUE THREAD

**Issue by fabm22** [yeoman/generator-angular#1141]
Hi, 
sorry if my question is stupid, but is it possible to change the defaults that the generator uses, : view under /views etc. ... ?

This promotes a separation of folders by "technical aspects" (controllers, views, services, directives etc.) where many might want to use a more by "feature area" approach ( for example that's the recommended one by the John Papa's Angular style guide : https://github.com/johnpapa/angular-styleguide#style-y163 )

Is it possible to specify them in the .yo-rc.json file ?

Thanks a lot.

**Comment by eddiemonge** [comment]
This is already a planned feature.

**Comment by fabm22** [comment]
Thanks for quick reply.
