### ISSUE TITLE
App doesn't run after building without errors

### ISSUE THREAD

**Issue by Forestdev** [yeoman/generator-angular#1143]
I've been having this odd issue lately. It first began by not being able to identify ngtamplates task, and cdnify asking for a base string.
I fixed it by adding the following to jit-grunt:

  `require('jit-grunt')(grunt, {
    useminPrepare: 'grunt-usemin',
    ngtemplates: 'grunt-angular-templates',
    cdnify: 'grunt-google-cdn'
  });`

Now the app builds, but I keep getting the error when I try to run it:

`Error: [$injector:nomod] Module 'golfscoresApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.1/$injector/nomod?p0=golfscoresApp`

Not quite sure where to even begin solving the issue at this point.

**Comment by Forestdev** [comment]
So far what I've found is that the grunt build task doesn't generate views folder. After manually pasting that in, it works, however, it still throws the same injector error. However, everything works.

**Comment by eddiemonge** [comment]
Are you loading all the files correctly? Is your module named `golfscoresApp`?

The latest release also already has the jit-grunt stuff: https://github.com/yeoman/generator-angular/blob/master/templates/common/root/_Gruntfile.js#L16-L19

**Comment by Forestdev** [comment]
Yeah, I got the latest release. It builds, fine, however, it doesn't generate views folder under /dist for some odd reason. The injector issue has disappeared.
