### ISSUE TITLE
npm test

### ISSUE THREAD

**Issue by favio41** [yeoman/generator-angular#1144]
Hi, I'm trying test the project in my local machine, but I have this error:

Uncaught Error: You don't seem to have a generator with the name angular:app installed.

and after use yo --help I get:

  angular
    common
    constant
    controller
    decorator
    directive
    factory
    filter
    main
    provider
    route
    service
    value
    view

I make a symbolic link between npm and my project.

There are instructions for configure travis CI? What are your toughs?

**Comment by eddiemonge** [comment]
What is the folder you checked out named?

**Comment by arthurvr** [comment]
Friendly ping @favio41.
