### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by Fynkymynky** [yeoman/generator-angular#1145]
For a number of days now I've tried to create a new project, but things just don't work. I'm building angular inside a VM, but when I try and run `yo angular app`, I get a load of `npm ERR! tar.unpack untar error` errors and

```
grunt-cli: The grunt command line interface. (v0.1.13)

Fatal error: Unable to find local grunt.

If you're seeing this message, either a Gruntfile wasn't found or grunt
hasn't been installed locally to your project. For more information about
installing and configuring grunt, please see the Getting Started guide:

http://gruntjs.com/getting-started
```

I've cleared the cache for npm and bower and ran everything with and without sudo.

My output can be found here https://gist.githubusercontent.com/Fynkymynky/95c518cd56589b2a12ef/raw/gistfile1.txt

**Comment by Fynkymynky** [comment]
Running a generator seems to work fine

```
yo angular:route myroute
   invoke   angular:controller:/usr/lib/node_modules/generator-angular/route/index.js
   create     app/scripts/controllers/myroute.js
   create     test/spec/controllers/myroute.js
   invoke   angular:view:/usr/lib/node_modules/generator-angular/route/index.js
   create     app/views/myroute.html
```
But there is no update to the index.html file
```
    <!-- build:js(.) scripts/vendor.js -->
    <!-- bower:js -->
    <!-- endbower -->
    <!-- endbuild -->
```

**Comment by eddiemonge** [comment]
This looks like a npm problem. You should open this ticket there since we can't really troubleshoot that part of the generation from here. The local grunt problem is because npm didn't install a local grunt.
