### ISSUE TITLE
It appears that Bootstrap (CSS) is not working

### ISSUE THREAD

**Issue by briviere** [yeoman/generator-angular#1152]
For some reason the CSS is not working.  I guess it can't find the CSS generated.

**Comment by calidion** [comment]
https://github.com/twbs/bootstrap/issues/16663

https://github.com/bower/bower.json-spec/pull/43

https://github.com/bower/bower.json-spec/issues/47


Hope will be fixed asap.

**Comment by cvrebert** [comment]
> Hope will be fixed asap.

Given Bower's low activity level, I wouldn't count on that.

**Comment by cvrebert** [comment]
Duplicate of #1116?

**Comment by arthurvr** [comment]
Yep, seems like a dupe.
