### ISSUE TITLE
$cookieStore is deprecated

### ISSUE THREAD

**Issue by mrmayfield** [yeoman/generator-angular#1156]
Just reading through the Angular docs:

https://docs.angularjs.org/api/ngCookies/service/$cookieStore

Looks like $cookieStore is deprecated and is now being used as $cookies

**Comment by eddiemonge** [comment]
We aren't using cookieStore in this.

**Comment by mrmayfield** [comment]
angularapp/client/components/auth/auth.service.js uses cookieStore .

And thus the Angular app uses cookieStore.

**Comment by eddiemonge** [comment]
This isn't angularapp.

**Comment by mrmayfield** [comment]
Sorry, that's just the name of the folder I have it stored in. Not sure what the default name is.

**Comment by eddiemonge** [comment]
Ok but this still doesn't use cookieStore. It lets use install `angular-cookies` but the actual implementation of that is up to you.
