### ISSUE TITLE
Error while running yo angular command

### ISSUE THREAD

**Issue by ui-ninja** [yeoman/generator-angular#1158]
I'm facing following issue while running yo angular command. Due to this in my directory i do not found bower_components folder.

Failed to execute "git ls-remote --tags --heads git://github.com/angular/bower-angular.git", exit code of #128 fatal: read error: Invalid argument

![yo_error](https://cloud.githubusercontent.com/assets/12812377/9244285/76a94ae2-41b7-11e5-9a10-a7e9c263ae62.png)

**Comment by eddiemonge** [comment]
This is a bower error. Did you try rerunning `bower install`?
