### ISSUE TITLE
npm ERR! tar.unpack untar error 

### ISSUE THREAD

**Issue by kdh6429** [yeoman/generator-angular#1160]
![tar](https://cloud.githubusercontent.com/assets/6263966/9279703/2b4cc144-42f4-11e5-93dd-e1681eba8e61.png)

this error comes not only generator-angular, but also any other generators..

vmware + ubuntu14 + nvm
I installed gulp package, and adjust my $PATH.
also tried 'npm cache clean'
BUT nothing works for me..
somehow I made good one but never made again..

**Comment by eddiemonge** [comment]
This looks like a npm issue. not really much we can do. have you tried asking on npm's repo?

**Comment by ajschmidt8** [comment]
i also consistently have this issue. i've never gotten a successful Yeoman build that didn't have these untar errors. i've used several different Vagrant boxes as well which is strange.
