### ISSUE TITLE
Issue with Python version for one of the commands

### ISSUE THREAD

**Issue by justsayno** [yeoman/generator-angular#1161]
I've noticed lately getting this error here:

![image](https://cloud.githubusercontent.com/assets/4713713/9287698/b9b3c342-4376-11e5-849c-9d5fc663d142.png)

Not sure what this command is trying to do any wondering if this is going to cause me any issues down the line?

I am using Win7, have no issues running Yeoman at all after this error, and it works fine. Just thought it worth bringing it to your attention if it wasn't already known.

**Comment by eddiemonge** [comment]
You should open this at the node-gyp issue tracker but you shouldn't have problems because of it.
