### ISSUE TITLE
Bower pointing ngVer 1.3.0 

### ISSUE THREAD

**Issue by judearasu** [yeoman/generator-angular#1162]
Is there any reasons for Bower pointing to angularjs 1.3.0 in generators by default.

**Comment by stevemao** [comment]
We need to update the deps.

**Comment by eddiemonge** [comment]
Its not. Its pointing at `^1.3.0` which means install the latest compatible version of the `1.x.x` line. Which means it will, as of right now, install version `1.4.4`

**Comment by judearasu** [comment]
@eddiemonge  Thanks
