### ISSUE TITLE
SEO integration

### ISSUE THREAD

**Issue by LunarDevelopment** [yeoman/generator-angular#1166]
Hello! 

I don't know how to make this a request/ suggestion / feature.. 

Anyway, I was reading the below tutorial and was wondering if anyone has the expertise to automate any kind of seo optomisation via the generator? 

http://www.doz.com/search-engine/angularjs-index-seo

Lewis

**Comment by eddiemonge** [comment]
Those are all server side options which the generator wouldn't be able to do.
