### ISSUE TITLE
Running `yo angular:directive noteList` fails

### ISSUE THREAD

**Issue by kylehayes** [yeoman/generator-angular#1167]
When attempting to use the directive generator, it fails with the following message:

    Error angular:directive noteList
    
    You don't seem to have a generator with the name angular:directive installed.
    You can see available generators with npm search yeoman-generator and then install them with npm     install [name].
    To see the 19 registered generators run yo with the `--help` option.

**Comment by eddiemonge** [comment]
What version of yo|generator-angular|node are you using?

**Comment by kylehayes** [comment]
Forgot to close this, evidently my environment was out of sync and was missing some core dependencies.
