### ISSUE TITLE
Grunt can't package project created by angular generator

### ISSUE THREAD

**Issue by damluar** [yeoman/generator-angular#1168]
I generated a new angular project using `yo angular` (I tried the latest version, but also 0.11.1) and try to package the app directly using `grunt`.
The `dist` folder contains no scripts or styles, so the application is completely broken.

P.S. `grunt` doesn't work at all if I don't specify `--force` option. It terminates with:
    
    Running "useminPrepare:html" (useminPrepare) task
    Warning: Cannot find module 'path/test/node_modules/grunt-usemin/lib/config/uglifyjs' Use --force to continue.

    Aborted due to warnings.

**Comment by arthurvr** [comment]
We're running into https://github.com/yeoman/grunt-usemin/issues/591. Let's wait if we can patch grunt-usemin quickly and if not we'll need to lock down the dependency.

**Comment by damluar** [comment]
But still the `dist` folder is missing all js files...

**Comment by cebor** [comment]
rename uglifyjs -> uglify in Gruntfile.js and it should work ...
