### ISSUE TITLE
A typo failing grunt build for a generated project

### ISSUE THREAD

**Issue by Ahimta** [yeoman/generator-angular#1169]
I'm not really sure but for some reason my build (grunt build) failed with an error message:

"Warning: Cannot find module '/home/abdullah/Documents/abdulwahed-alansari-frontend/node_modules/grunt-usemin/lib/config/uglifyjs' Use --force to continue."

I looked into it and noticed that "node_modules/grunt-usemin/lib/config/" includes:
1. concat.js
2. cssmin.js
3. requirejs.js
4. uglify.js

So i took a look at my Gruntfile.js and found something very similar to this [line](https://github.com/yeoman/generator-angular/blob/09d90f4486d12e0ef4d9283983329d171749297a/templates/common/root/_Gruntfile.js#L372).

I changed "uglifyjs" to "uglify" and everything worked just fine.
You can find my project here: https://github.com/Ahimta/abdulwahed-alansari-frontend/tree/14718835763c36794c0e7ecf4574fc693c94dbfe

I think it wouldn't be unreasonable to fail "grunt test" if "grunt build" could fail and maybe do the same thing for "grunt serve"

**Comment by arthurvr** [comment]
https://github.com/yeoman/grunt-usemin/issues/591 - grunt-usemin accidentally released with a breaking change. Should be fixed soon. Sorry for the troubles you're having.

**Comment by stephanebachelier** [comment]
@Ahimta I've released a new version 3.1.1 to fix this issue. Only available on github as I don't have the rights to publish on npm.

**Comment by rstormsf** [comment]
I've run into the same one. Please publish to npmjs asap

**Comment by Ahimta** [comment]
I just made my `npm test` fail if `grunt build` fails: https://github.com/Ahimta/abdulwahed-alansari-frontend/commit/e1d3ed8bd46ca8daeec39d4e0fd898a22919769e

It's really disappointing for the tests to pass on TravisCI when `grunt build` is failing.

One not so obvious with continuous integration (e.g: TravisCI) is to make sure that your code can run anywhere and not because you have some hack on your computer that makes it work.

This is very helpful when you are working alone and a requirement when you are working with a team (somewhat like Git and TravisCI)

@stephanebachelier I am not really sure but I think grunt-usmin may have to keep both files (uglify.js and uglifyjs.js) at least for now.

**Comment by arthurvr** [comment]
> @Ahimta I've released a new version 3.1.1 to fix this issue. Only available on github as I don't have the rights to publish on npm.

Was published a while ago so closing this now.
