### ISSUE TITLE
Error when install from Yeoman

### ISSUE THREAD

**Issue by J2TeaM** [yeoman/generator-angular#1171]
Hi!

I get an error in the image below.

![yo-angular](https://cloud.githubusercontent.com/assets/5250117/9523260/4c627554-4d03-11e5-96bc-123ffbd19748.PNG)

P/S: I have solved the problem by installing via npm: `npm install -g generator-angular`. I just wanted to report the issue to the developers!

**Comment by eddiemonge** [comment]
That looks like a network error.
