### ISSUE TITLE
font-awesome css is removed from index.html

### ISSUE THREAD

**Issue by danielabar** [yeoman/generator-angular#1173]
I'm trying to add font-awesome to my project. Started with:

```
bower install font-awesome --save
```

Then added css to index.html

```
    <!-- build:css(.) styles/vendor.css -->
    <!-- bower:css -->
    <link rel="stylesheet" href="bower_components/animate.css/animate.css" />
    <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="bower_components/font-awesome/css/font-awesome.css" />
    <!-- endbower -->
    <!-- endbuild -->
```

It works with `grunt watch`.

But when running `grunt build`, the font-awesome.css is removed from app/index.html.

It seems to be caused by the wiredep task.

Has anyone else been able to get font awesome working with generator-angular?

**Comment by danielabar** [comment]
Found the solution [here](https://github.com/stephenplusplus/grunt-wiredep/issues/25)

Turns out font-awesome from bower doesn't come with a bower.json file, so not handled by wiredep. Solution is to use

```
bower install components-font-awesome --save
```

**Comment by ryanburnett** [comment]
Thanks @danielabar

**Comment by devarajang** [comment]
Thanks it helped me
