### ISSUE TITLE
bootstrap styling ain't installed

### ISSUE THREAD

**Issue by ray1618** [yeoman/generator-angular#1174]
After running ```yo angular``` the bootstrap styling isn't active.
The bootstrap files are in the folder bower_components.

Still doesn't work after running bower install and grunt.

steps I took:
```$ yo angular```
```$ bower install```
```$ grunt```
```$ grunt serve```

**Comment by arthurvr** [comment]
What version of generator-angular do you have installed?

**Comment by ray1618** [comment]
I think it's my miss I'm using "version": "0.11.1", think it'll be fixed @ version "version": "0.12.1", Sorry I'm new at this :)

Though in the yeoman codelab tutorial it seems to work: http://yeoman.io/codelab/install-generators.html

I'm gonna reïnstall, thx
