### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by mukundha** [yeoman/generator-angular#1179]
Hi,

I am unable to install, i get this error
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "generator-angular"
npm ERR! node v0.10.26
npm ERR! npm  v2.1.4
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package generator-karma does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer generator-angular@0.12.1 wants generator-karma@>=0.9.0
npm ERR! peerinvalid Peer generator-angular-phonegap@0.5.6 wants generator-karma@~0.6.0

Thanks,

**Comment by arthurvr** [comment]
We should probably just get rid of the peer dependencies anyways. Ref: https://github.com/yeoman/yeoman/issues/1488.

**Comment by eddiemonge** [comment]
@mukundha `npm i -g generator-karma`

**Comment by javarch** [comment]
Ich werde ab  16.09.2015 nicht im B�ro sein. Ich kehre zur�ck am
12.10.2015.
Ich werde Ihre Nachricht nach meiner R�ckkehr beantworten.

Die R�ckmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [generator-angular] Install failed (#1179)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2015 Agent 'Abwesenheit'


Der Austausch von Nachrichten mit o.a. Absender via e-mail dient
ausschlie�lich Informationszwecken. Rechtsgesch�ftliche Erkl�rungen d�rfen
�ber dieses Medium nicht ausgetauscht werden.

Correspondence with a.m. sender via e-mail is only for information
purposes. This medium is not to be used for the exchange of legally-binding
communications.

**Comment by mukundha** [comment]
thx guys, i removed all the packages and did 'npm i -g generator-karma', it worked
