### ISSUE TITLE
Running grunt serve shows an unfinished app

### ISSUE THREAD

**Issue by V1cHu** [yeoman/generator-angular#1180]
I followed the tutorial in the Yo official website and created an angular app using the generator-angular. After everything is done confuguring, I did `grunt serve` and the webpage opens. But the whole page is not complete. The boostrap components are present but the page is not like how it is supposed to be. Opening the firefox console shows the following:

    SyntaxError: unterminated string literal angular.js:28826:87
    TypeError: angular is undefined angular-animate.js:9:4
    TypeError: angular is undefined angular-cookies.js:24:0
    TypeError: angular is undefined angular-resource.js:8:4
    TypeError: angular is undefined angular-route.js:24:4
    TypeError: angular is undefined angular-sanitize.js:19:4
    ReferenceError: angular is not defined app.js:11:0
    ReferenceError: angular is not defined main.js:10:0
    ReferenceError: angular is not defined about.js:10:0
    The connection to ws://localhost:35729/livereload was interrupted while the page was loading. livereload.js:191:0
    Firefox can't establish a connection to the server at ws://localhost:35729/livereload. livereload.js:191:0
    Firefox can't establish a connection to the server at ws://localhost:35729/livereload. livereload.js:191:0
    Firefox can't establish a connection to the server at ws://localhost:35729/livereload. livereload.js:191:0
    Firefox can't establish a connection to the server at ws://localhost:35729/livereload. livereload.js:191:0
    The connection to ws://localhost:35729/livereload was interrupted while the page was loading. livereload.js:191:0
    Firefox can't establish a connection to the server at ws://localhost:35729/livereload. livereload.js:191:0
    Firefox can't establish a connection to the server at ws://localhost:35729/livereload. livereload.js:191:0
     Firefox can't establish a connection to the server at ws://localhost:35729/livereload. livereload.js:191:0
     Firefox can't establish a connection to the server at ws://localhost:35729/livereload. livereload.js:191:0
     Firefox can't establish a connection to the server at ws://localhost:35729/livereload. livereload.js:191:0
     Firefox can't establish a connection to the server at ws://localhost:35729/livereload. livereload.js:191:0
     Firefox can't establish a connection to the server at ws://localhost:35729/livereload. livereload.js:191:0

I did `npm cache clean` and `bower install` but still could not get this to work.

I have attached the page preview as well.
![capture](https://cloud.githubusercontent.com/assets/10045752/9968876/ce7ab10c-5e68-11e5-8f09-7e982bf27d9b.PNG)

**Comment by javarch** [comment]
Ich werde ab  16.09.2015 nicht im B�ro sein. Ich kehre zur�ck am
12.10.2015.
Ich werde Ihre Nachricht nach meiner R�ckkehr beantworten.

Die R�ckmeldung bezieht sich auf ein Mail mit folgendem Thema:
[generator-angular] Running grunt serve shows an unfinished app (#1180)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2015 Agent 'Abwesenheit'


Der Austausch von Nachrichten mit o.a. Absender via e-mail dient
ausschlie�lich Informationszwecken. Rechtsgesch�ftliche Erkl�rungen d�rfen
�ber dieses Medium nicht ausgetauscht werden.

Correspondence with a.m. sender via e-mail is only for information
purposes. This medium is not to be used for the exchange of legally-binding
communications.

**Comment by eddiemonge** [comment]
What errors are in your terminal?

**Comment by javarch** [comment]
Ich werde ab  16.09.2015 nicht im B�ro sein. Ich kehre zur�ck am
12.10.2015.
Ich werde Ihre Nachricht nach meiner R�ckkehr beantworten.

Die R�ckmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [generator-angular] Running grunt serve shows an unfinished app (#1180)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2015 Agent 'Abwesenheit'


Der Austausch von Nachrichten mit o.a. Absender via e-mail dient
ausschlie�lich Informationszwecken. Rechtsgesch�ftliche Erkl�rungen d�rfen
�ber dieses Medium nicht ausgetauscht werden.

Correspondence with a.m. sender via e-mail is only for information
purposes. This medium is not to be used for the exchange of legally-binding
communications.

**Comment by V1cHu** [comment]
This is what is in the console : 
	PS E:\zookeeper\zeek> grunt serve
	Running "serve" task

	Running "clean:server" (clean) task
	>> 1 path cleaned.

	Running "wiredep:app" (wiredep) task

	Running "wiredep:test" (wiredep) task

	Running "concurrent:server" (concurrent) task

	Running "copy:styles" (copy) task
	Copied 1 file

	Done, without errors.


	Execution Time (2015-09-19 06:20:08 UTC)
	loading tasks               14ms  ████████ 22%
	loading grunt-contrib-copy  30ms  ████████████████ 46%
	copy:styles                 21ms  ███████████ 32%
	Total 65ms

	Running "autoprefixer:server" (autoprefixer) task
	Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
	File .tmp/styles/main.css created.

	Running "connect:livereload" (connect) task
	Started connect web server on http://localhost:9000

	Running "watch" task
	Waiting...

**Comment by eddiemonge** [comment]
what version of node, npm, yo and this generator are you using?

**Comment by V1cHu** [comment]
Hi,
These are the versions:
 ____________________________________

Regards,
Vishnu Ramana

**Comment by V1cHu** [comment]
These are the versions:

PS C:\Users\vishn> node --versionv0.12.7
PS C:\Users\vishn> npm --version
2.11.3
PS C:\Users\vishn> yo --version
1.4.8 ____________________________________

Regards,
Vishnu Ramana

**Comment by arthurvr** [comment]
What version of the generator are you using?

**Comment by javarch** [comment]
Ich werde ab  16.09.2015 nicht im B�ro sein. Ich kehre zur�ck am
12.10.2015.
Ich werde Ihre Nachricht nach meiner R�ckkehr beantworten.

Die R�ckmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [generator-angular] Running grunt serve shows an unfinished app (#1180)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2015 Agent 'Abwesenheit'

Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
DVR: 0572934, UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angef�hrten Absender via E-Mail
dient ausschlie�lich Informationszwecken. Rechtsgesch�ftliche Erkl�rungen
d�rfen �ber dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.

**Comment by arthurvr** [comment]
Going to close this for now, but ping us when you can give us the info we need and we can reopen :)
