### ISSUE TITLE
Yo angular creates incorrect file structure?

### ISSUE THREAD

**Issue by RKS213** [yeoman/generator-angular#1181]
Forgive me but today is my first time using Yeoman so I'm still learning. I tried my first app by running yo angular and I get:

app/
bower_components/
node_modules/

however when looking at the HTML that is generated it is looking for /app/bower_components/bootstrap/dist/css/bootstrap.css and this not in the app tree. If I manually move bower_components/ into app/ everything appears to work but I don't yet know what it's supposed to look like anyway but I know it's generating the wrong structure.

Side note: how do you edit the default HTML that is being generated with yo angular or is this something is in the script itself that require a fork of the project? I have a very specific HTML doc I start all projects with so I'd like to combine what I need from yo angular and what I normally use but this may cause issues updating later if it's not a file that's ignored.

**Comment by javarch** [comment]
Ich werde ab  16.09.2015 nicht im B�ro sein. Ich kehre zur�ck am
12.10.2015.
Ich werde Ihre Nachricht nach meiner R�ckkehr beantworten.

Die R�ckmeldung bezieht sich auf ein Mail mit folgendem Thema:
[generator-angular] Yo angular creates incorrect file structure? (#1181)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2015 Agent 'Abwesenheit'


Der Austausch von Nachrichten mit o.a. Absender via e-mail dient
ausschlie�lich Informationszwecken. Rechtsgesch�ftliche Erkl�rungen d�rfen
�ber dieses Medium nicht ausgetauscht werden.

Correspondence with a.m. sender via e-mail is only for information
purposes. This medium is not to be used for the exchange of legally-binding
communications.

**Comment by eddiemonge** [comment]
Try following this: http://yeoman.io/codelab/

**Comment by javarch** [comment]
Ich werde ab  16.09.2015 nicht im B�ro sein. Ich kehre zur�ck am
12.10.2015.
Ich werde Ihre Nachricht nach meiner R�ckkehr beantworten.

Die R�ckmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [generator-angular] Yo angular creates incorrect file structure?
(#1181)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2015 Agent 'Abwesenheit'


Der Austausch von Nachrichten mit o.a. Absender via e-mail dient
ausschlie�lich Informationszwecken. Rechtsgesch�ftliche Erkl�rungen d�rfen
�ber dieses Medium nicht ausgetauscht werden.

Correspondence with a.m. sender via e-mail is only for information
purposes. This medium is not to be used for the exchange of legally-binding
communications.
