### ISSUE TITLE
Directive with templateUrl 404

### ISSUE THREAD

**Issue by seemsindie** [yeoman/generator-angular#1184]
I have an issue with building a project. I created couple of directives and i have templateUrl pointing to html in /app/views/... Example: templateUrl: '../../views/topbar.html'

When i build i can see them put into $templateCache but when i fire up the server and go to the site i get:

GET http://localhost:8000/views/topbar.html 404 (File not found)
Error: [$compile:tpload] Failed to load template: ../../views/topbar.html (HTTP status: 404 File not found)...

I don't see what am i doing wrong, but can someone help me?

Thanks, Ivan

**Comment by javarch** [comment]
Ich werde ab  16.09.2015 nicht im B�ro sein. Ich kehre zur�ck am
12.10.2015.
Ich werde Ihre Nachricht nach meiner R�ckkehr beantworten.

Die R�ckmeldung bezieht sich auf ein Mail mit folgendem Thema:
[generator-angular] Directive with templateUrl 404 (#1184)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2015 Agent 'Abwesenheit'


Der Austausch von Nachrichten mit o.a. Absender via e-mail dient
ausschlie�lich Informationszwecken. Rechtsgesch�ftliche Erkl�rungen d�rfen
�ber dieses Medium nicht ausgetauscht werden.

Correspondence with a.m. sender via e-mail is only for information
purposes. This medium is not to be used for the exchange of legally-binding
communications.

**Comment by gaboesquivel** [comment]
@seemsindie  you need to remove "../../" 
use `templateUrl: 'views/topbar.html'`

**Comment by javarch** [comment]
Ich werde ab  16.09.2015 nicht im B�ro sein. Ich kehre zur�ck am
12.10.2015.
Ich werde Ihre Nachricht nach meiner R�ckkehr beantworten.

Die R�ckmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [generator-angular] Directive with templateUrl 404 (#1184)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2015 Agent 'Abwesenheit'


Der Austausch von Nachrichten mit o.a. Absender via e-mail dient
ausschlie�lich Informationszwecken. Rechtsgesch�ftliche Erkl�rungen d�rfen
�ber dieses Medium nicht ausgetauscht werden.

Correspondence with a.m. sender via e-mail is only for information
purposes. This medium is not to be used for the exchange of legally-binding
communications.
