### ISSUE TITLE
Subfolder-Support

### ISSUE THREAD

**Issue by koern82** [yeoman/generator-angular#1185]
I would like to generate all my controllers in my AngularJS-Project with the help of Yeoman. Unfortunately everything is thrown in the app/scripts/controllers -Folder. Is it possible to say yeoman that the source should be generated in a specific subfolder inside the controllers-folder?

Here is an example:
```javascript
+app
 +scripts
   +controllers
    +part1
       -controller1Ctrl
       -controller2Ctrl
    +part2
       -controller3Ctrl
       -controller4Ctrl
```
When i type 
```javascript
yo angular:controller part1/controller1Ctrl 
```
the Folder was created in the right way but name of the controller is 
```javascript
part1/controller1Ctrl
```

that should be 
```javascript
controller1Ctrl
```

Thanks for your help

-Micha

**Comment by eddiemonge** [comment]
Read the top of the Gruntfile

**Comment by javarch** [comment]
Ich werde ab  16.09.2015 nicht im B�ro sein. Ich kehre zur�ck am
12.10.2015.
Ich werde Ihre Nachricht nach meiner R�ckkehr beantworten.

Die R�ckmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [generator-angular] Subfolder-Support (#1185)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2015 Agent 'Abwesenheit'

Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
DVR: 0572934, UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angef�hrten Absender via E-Mail
dient ausschlie�lich Informationszwecken. Rechtsgesch�ftliche Erkl�rungen
d�rfen �ber dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.

**Comment by koern82** [comment]
Sorry im new to yeoman and angular- can you please send me an example on how to create a controller in a subdir with the help of yeoman? Thanks a lot!

**Comment by eddiemonge** [comment]
There are lots of tutorials around for that. But just read the those lines and see if you can figure it out from there. If not, try asking on stackoverflow, or even just searching there since I am sure its been answered there a few times.
