### ISSUE TITLE
Using browser sync

### ISSUE THREAD

**Issue by karneaud** [yeoman/generator-angular#1190]
Hey guys,

I saw you guys integrated browser sync which is cool but how do you now replace the server options in the grunt file config to use browser sync?

**Comment by eddiemonge** [comment]
uh we didn't switch. there is a PR for it but it hasn't been merged yet.

**Comment by karneaud** [comment]
sunnuva.....

I must say will i admire the concept go Yeoman. To class this as being able to "rapidly" develop application is far from its mantra. 

I've tried to use yeoman twice but find I spend more time debugging the packages than developing my applications. 

Can't yeoman be more modular than preset? e.g. 

Can't I "yo" optional packages and have yo generate the project based on these package modules i select without me having to use some or the unnecessary tasks being used. 

I say this because Browsersync has proven to be a very effect and reliable tool as opposed to the regular  serve/ connect stuff

**Comment by eddiemonge** [comment]
Its an ever evolving tool/process. Our long term goal is to be more composable so it will do like you said. yeoman-generator has the foundation built for that but getting to the generators there will take more time. in the meantime: http://yeoman.io/blog/generator-gulp-angular-v1.html

**Comment by karneaud** [comment]
I guess I am ahead of its time....*sigh* *heads back to dreamweaver*

**Comment by eddiemonge** [comment]
> sigh heads back to dreamweaver

Hopefully sarcasm...
