### ISSUE TITLE
Not detecting karma/jasmine-core/phantomjs + more issues

### ISSUE THREAD

**Issue by Elliot87** [yeoman/generator-angular#1191]
Alright, so my installation of yeoman appeared to go perfectly fine, but I'm having difficulty using this generator. When I first installed the generator, it told me it required karma, phantomjs and jasmine-core as peers, so I uninstalled the generator, installed all 3 of the dependencies it said I needed, and reinstalled the generator, yet it still said I didnt have them....I decided to just install them manually directly to my project folder rather than globally, and when I used `grunt serve` everything appeared to be scaffold out appropriately, I had the live preview on and everything looked how it should according to the codelab screenshots on yeoman.io...

I thought everything was working properly, I have been following along word-for-word on the codelab on the official website, and even tried copy and pasting their actual code when it wasn't working, but even so, the todo list wasn't showing up. The only thing I was able to get showing up on the page is the text field to add todos, and a broken button -- it wouldn't actually add anything to the list.

 I've been following along exactly with the codlab tutorial, and my edits aren't reflecting as they should, which leads me to believe it might be a problem with the generator?

**Comment by eddiemonge** [comment]
npm3 no longer auto installers peer deps so you have to install them manually. The lab hasn't been updated to npm3 as its not the official version yet.

**Comment by Elliot87** [comment]
Sorry for posting so much, I just really want to get this working. Is the 2.14 node version that ships with nodejs considered the 'official version'? I could always reinstall node and use the older version it ships with, if that will make things work better.

As I said, I DID install the dependencies manually, and it still says I don't have them.  Does saving them globally not work? Do I actually have to manually add them to each project before installing the generator? Didn't you also say these dependencies are only for testing purposes? If so that doesn't explain why I've followed word-for-word on the codelab, and even copy/pasted the code they said to use, and it doesn't show my todo lists, or even add todos, it only shows the text field to add todos with a broken button that doesn't actually do anything.

I've literally copy/pasted all of the code they said to use incase I was making a typo somewhere, and it still didn't work. I guess yeoman just doesn't want to work for me. I even switched to Linux for the sole purpose of hoping yeoman would install better-- since it just didn't want to happen on windows, I couldn't even get yo itself installed on windows. At least I've been able to get it installed here, but now I can't get the generator working properly. Are there any other resources out there for help with installing yeoman other than the documentation? Because following that isn't helping me. I've spent the past week trying to get yeoman working, and I don't want to give up now, but I'm running out of options to try.

**Comment by eddiemonge** [comment]
Run `node --version && npm --version` and tell me what the output is please

**Comment by Elliot87** [comment]
I've been using 4.2.1 node and 3.3.6 npm, both of them are latest versions....I don't really understand how `npm install npm -g`  would install 3.3.6  if it's not the official version. I always thought using the latest versions was best practice but seems I was wrong?

**Comment by eddiemonge** [comment]
Did you install npm@3 at some point?

**Comment by Elliot87** [comment]
I was always told whenever you install node you need to update your npm version, I never specified  what version to install specifically, I just did `npm install npm -g` and it gave me 3.3.6

**Comment by eddiemonge** [comment]
I missed that they switched to npm3 by default. so much docs to update now

**Comment by Elliot87** [comment]
is there a specific node/npm version that would be most friendly with yeoman? I'm using nvm, so I can easily switch node versions if necessary, and I can just give that version of node the appropriate nvm version to use with yeoman. I just want to get it working :(
