### ISSUE TITLE
UNMET PEER DEPENDENCY yo@>=1.0.0

### ISSUE THREAD

**Issue by TusharPandya** [yeoman/generator-angular#1192]
Getting this error while creating new AngularJs project using Yeoman using bellow command
---> npm install --global generator-angular@0.11.1

For which my requirement details are as bellow
node --version = v4.2.1
npm --version = 3.3.6

Which is perfect because I can install Yeoman toolset using : npm install --global yo bower grunt-cli command.But when I try to install an AngularJS generator it generates 2 errors
1) UNMET PEER DEPENDENCY generator-karma@>=0.9.0
2) UNMET PEER DEPENDENCY yo@>=1.0.0

**Comment by eddiemonge** [comment]
npm3 no longer auto installers peer deps so you have to install them manually.

**Comment by jaumesalatantinya** [comment]
And how can I install them manually?

**Comment by javarch** [comment]
Ich werde ab  19.10.2015 nicht im B�ro sein. Ich kehre zur�ck am
23.10.2015.
Ich werde Ihre Nachricht nach meiner R�ckkehr beantworten.

Die R�ckmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [generator-angular] UNMET PEER DEPENDENCY yo@>=1.0.0 (#1192)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2015 Agent 'Abwesenheit'

Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
DVR: 0572934, UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angef�hrten Absender via E-Mail
dient ausschlie�lich Informationszwecken. Rechtsgesch�ftliche Erkl�rungen
d�rfen �ber dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.

**Comment by eddiemonge** [comment]
`npm i -g yo generator-karma`

**Comment by Sheparzo** [comment]
even after installing the yo dependency manually it is still popping up as unmet peer dependency.  Could it be that yeoman is not satisfying sibling/peer dependencies in npm 3?

**Comment by jaumesalatantinya** [comment]
The same to me Sheparzo. At the end I just give up.
I fact, the only thing it's failing is karma. All the rest of scafolding is working fine, so I give up on karma.

**Comment by dkobozev** [comment]
I'm having exactly the same issue as described, not sure why this was closed. I'm new to this stack, so I can't do any serious debugging without some tips. 

```
node --version
v4.2.1

npm --version
3.3.9
```

**Comment by TusharPandya** [comment]
yes, I tried every possible solutions still its not working  : (
I don't know how to re-open this issue.

**Comment by jaumesalatantinya** [comment]
I share what works for me. I manually install all the modules at ones and then npm resolves the dependency problem.

sudo npm install grunt-karma jasmine jasmine-core karma phantomjs -g
sudo npm install grunt-karma jasmine jasmine-core karma phantomjs --save-dev

**Comment by eddiemonge** [comment]
you shouldn't be using sudo for npm installs. That may be part of your problem

**Comment by yuhongcheng2003** [comment]
This worked for me, thanks!

npm install -g grunt-cli bower yo generator-karma generator-angular

**Comment by LillaEli** [comment]
Yes, at least these three (yo, generator-karma and generator-angular) have to be installed in a one line command for the dependencies to get resolved, like this:
npm install -g yo generator-karma generator-angular

However I think it should not need to be like that, and this is an issue indeed.

**Comment by gregoryderner** [comment]
It worked for me
```console
npm i -g yo generator-karma
```

**Comment by metodribic** [comment]
Well I did everything as described above and nothing worked, but I've noticed that at the end of the installation yo says "Done,without errors" but it actually does not end installation and if I press any key yo asks me "Overwrite package.json?" and if I say yes I get UNMET PEER DEPENDENCY despite I have everything installed, but if I say no, it proceeds without errors. I don't know if this helps anyone but it's worth trying. Post-install screenshots attached.
![screenshot 2015-11-08 11 55 45](https://cloud.githubusercontent.com/assets/6840850/11044953/02966730-8725-11e5-9799-5945647e5171.jpg)
![screenshot 2015-11-08 12 48 53](https://cloud.githubusercontent.com/assets/6840850/11044954/0298e438-8725-11e5-85fb-a8c866c65ad3.jpg)

**Comment by stephen-cernota** [comment]
From my notes this worked for me couple days ago, just tested again now in new folder and it worked:
```
npm install npm@latest
npm install yo mem-fs grunt jasmine-core phantomjs grunt-cli bower karma generator-karma generator-angular@0.14.0
yo doctor
yo angular
grunt serve
grunt test
```

If you choose SASS with Compass you will also need:
```
npm install -g ruby compass
gem install compass
```

**Comment by alexey** [comment]
`npm install -g grunt-cli bower yo generator-karma generator-angular`
use with sudo if u need to :)

**Comment by janoist1** [comment]
forget that sudo thing - this helped me https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md
prior to that I fully busted out the npm and nodejs, reinstalled it to avoid things fixing accidentally
hope this helps

**Comment by jaydge** [comment]
alexey's comment worked - thank you!

**Comment by maheshstms** [comment]
npm i -g yo generator-karma 

Thanks, this command worked for me

**Comment by jaumesalatantinya** [comment]
Janoist1 is right. Sudo npm is evil :)

Remove all: node, npm and all node_modules.

Install node
Follow thus instructions https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md

npm install npm@latest -g

And for now one everthing you install global you will not encounter any permision issue because you install at the root of your home directory

**Comment by smaudet** [comment]
This is absolutely nuts. Props to @dkobozev for finding the solution, this is (I would say) a major bug with npm.

**Comment by BabyDiose** [comment]
npm install -g yo generator-karma  works for me

**Comment by alisuarez** [comment]
None of this has worked for me...

**Comment by usmanarif** [comment]
@yuhongcheng2003 thanks....the magical command works for me!!!

**Comment by javarch** [comment]
Ich werde ab  04.01.2016 nicht im B�ro sein. Ich kehre zur�ck am
07.01.2016.
Ich werde Ihre Nachricht nach meiner R�ckkehr beantworten.

Die R�ckmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [generator-angular] UNMET PEER DEPENDENCY yo@>=1.0.0 (#1192)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2016 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
DVR: 0572934, UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angef�hrten Absender via E-Mail
dient ausschlie�lich Informationszwecken. Rechtsgesch�ftliche Erkl�rungen
d�rfen �ber dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------

**Comment by djperezh** [comment]
alexey's comment worked as a charm !!! Thanks... you saved my day !!!
Just run:
npm install -g grunt-cli bower yo generator-karma generator-angular

**Comment by dkmin** [comment]
Thanks a lot alexey. you save my life.

**Comment by gurinderiitr** [comment]
thanks.. it helped

**Comment by uvwxy** [comment]
Worked for me, too. Maybe it should say in the `readme.md` that the generators *have* to be installed together?

**Comment by kkampardi** [comment]
npm install -g grunt-cli bower yo generator-karma generator-angular

.... with sudo
That worked for me! Thanx :)

**Comment by overmedia** [comment]
So, package.json keep traying to install all dependencies BUT installation keeps failing and we have to install all dependencies included in "devDependencies": {...} manually?

**Comment by Kamps-Duac** [comment]
To add the unmet peer dependencies to my `package.json` I ran `npm install phantomjs-prebuilt jasmine-core karma --save-dev`

**Comment by arakno** [comment]
alexey's magic works !!! Thanks mate!
Just run:
`npm install -g grunt-cli bower yo generator-karma generator-angular`
I'm on windows 7 btw.

**Comment by jpventura** [comment]
If you are using [NVM](https://www.npmjs.com/package/nvm) or exported more than one Node.js environment, double check if generator-angular dependencies are spread into different directories.

Probably you are installing `generator-angular` in one folder and npm is reading the dependencies from another one.
