### ISSUE TITLE
GH Changelog broken on releases

### ISSUE THREAD

**Issue by eddiemonge** [yeoman/generator-angular#1195]
@stevemao seems to be an issue with the changelog pushing. It keeps wanting to use the last non-chore message for a release instead of leaving it blank. It also didn't generate the 0.13.0 release properly because the tag was pushed and then the ghcr said it can't post because it exists.

**Comment by stevemao** [comment]
> It keeps wanting to use the last non-chore message for a release instead of leaving it blank.

If the release is blank GitHub auto use the last commit message. Can you verify this?

**Comment by eddiemonge** [comment]
Looks like it will use the tag message. Seem to have got things working now.
