### ISSUE TITLE
Yo Angular unmet peer dependancy Jasmine Karma 

### ISSUE THREAD

**Issue by PeterClough** [yeoman/generator-angular#1196]
I've install yo today with npm install -g yo bower grunt-cli gulp

Then I installed generator-angular with npm install -g grunt-cli bower yo generator-karma generator-angular

on running yo angular I get this, any ideas on whats going on?

├── UNMET PEER DEPENDENCY jasmine-core@*
├── UNMET PEER DEPENDENCY karma@^0.13.0 || >= 0.14.0-rc.0
├── karma-jasmine@0.3.6 
├─┬ karma-phantomjs-launcher@0.2.1 
│ └── lodash@3.10.1 
└── UNMET PEER DEPENDENCY phantomjs@>=1.9

npm WARN EPEERINVALID karma-jasmine@0.3.6 requires a peer of jasmine-core@* but none was installed.
npm WARN EPEERINVALID karma-phantomjs-launcher@0.2.1 requires a peer of karma@>=0.9 but none was installed.
npm WARN EPEERINVALID karma-phantomjs-launcher@0.2.1 requires a peer of phantomjs@>=1.9 but none was installed.
npm WARN EPEERINVALID grunt-karma@0.12.1 requires a peer of karma@^0.13.0 || >= 0.14.0-rc.0 but none was installed.

**Comment by eddiemonge** [comment]
Those are warnings because of peerDeps of generator-karma. Install them and it should work fine.

**Comment by sDaniel** [comment]
For the reference more infos at: https://github.com/yeoman/generator-angular/issues/1205

**Comment by mhamitdubey** [comment]
Use dependency manually for example - 
"devDependencies": {
   "jasmine-core": "^2.4.1",
    "karma": "^1.2.0",
    "karma-chrome-launcher": "^1.0.1",
    "karma-jasmine": "^1.0.2"
  }

add karma globally - 
npm install -g karma-cli
karma init to start karma and ask you to add dependency and create a file **karma.conf.js** locally.

**Comment by gildniy** [comment]
I found somewhere a suggestion that you have to run all dependences on the same line, like this:
`npm install -g grunt-cli bower yo generator-karma generator-angular`
