### ISSUE TITLE
Not working out of the box.

### ISSUE THREAD

**Issue by Tekkromancer** [yeoman/generator-angular#1201]
Hello,  

After running the generator  (`yo angular`), with the gulp option, it's not loading Angular when I run `gulp serve`. It looks like the bower_components are not being loaded.

Also, there appears to be no styling implemented.  There is a main.css file in the .tmp folder, but it's not being referenced.

I'm using version 3.3.10 of the generator.

I tried running `gulp bower` to see if that would do anything, but it throws `Error: Error: angular is not installed. Try running `bower install`.`

Angular *is* in the bower_components folder.

One would think that this generator would work right out of the box without issue. Am I missing something obvious?

**Comment by eddiemonge** [comment]
There is no version 3.3.10 of this generator

**Comment by zenix** [comment]
I'm having same issue. Not working with gulp currently. Bower components are not working.

**Comment by eddiemonge** [comment]
What version are you using?

**Comment by zenix** [comment]
Latest - installed same day. I have windows 10 and running everything from git bash.

**Comment by eddiemonge** [comment]
oh, Windows. Haven't tested on that recently. Do you get any npm errors or any other command line errors?

**Comment by LunarDevelopment** [comment]
He means npm v 3.3.10, 

I'm having some issues with it too, however mine seem to be to do with peer dependencies, not with yo angular.

**Comment by Gamaroff** [comment]
I'm running on a Mac.

Installed the generator and ran **grunt serve** fine on the generated project.

The problem happens when running **grunt build**.

The following error is returned:

    Warning: Running "imagemin:dist" (imagemin) task
    Fatal error: Cannot read property 'contents' of undefined

**Comment by LunarDevelopment** [comment]
Yeah, I second that: 

```sh
Running "wiredep:app" (wiredep) task

Running "wiredep:test" (wiredep) task

Running "wiredep:sass" (wiredep) task

Running "useminPrepare:html" (useminPrepare) task
Configuration changed for concat, uglify, cssmin

Running "concurrent:dist" (concurrent) task

Running "svgmin:dist" (svgmin) task
Total saved: 0 B

Done, without errors.


Execution Time (2015-11-10 11:45:17 UTC)
loading tasks          74ms  ███████ 16%
loading grunt-svgmin  236ms  ████████████████████ 50%
svgmin:dist           164ms  ██████████████ 35%
Total 475ms
    Warning: Running "imagemin:dist" (imagemin) task
Fatal error: Cannot read property 'contents' of undefined


Execution Time (2015-11-10 11:45:15 UTC)
loading tasks                   47ms  █ 2%
loading grunt-contrib-imagemin  1.3s  █████████████████ 54%
imagemin:dist                   1.1s  ██████████████ 44%
Total 2.5s Used --force, continuing.

Running "imagemin:dist" (imagemin) task
Fatal error: Cannot read property 'contents' of undefined

```

**Comment by maxrevilo** [comment]
@Gamaroff and @LunarDevelopment I had the same problem in OSX and Windows 8.1, but as [stated here](https://github.com/gruntjs/grunt-contrib-imagemin/issues/208) You can install the lastest grunt-contrib-imagemin and it should work.

What I did was to change the the imagemin line of the package.json from
```
"grunt-contrib-imagemin": "^0.9.2",
```
to
```
"grunt-contrib-imagemin": "^1.0.0",
```
And then run ```npm install``` and it worked. If it doesn't work first run ```npm uninstall grunt-contrib-imagemin``` and then ```npm install`` again.

Please let me know if it works for you.

**Comment by eddiemonge** [comment]
Yeah thats an issue with a dependency changing and breaking something. I'll update the version here anyway

**Comment by Gamaroff** [comment]
I updated **grunt-contrib-imagemin** to **1.0.0** and everything works well again.

Thanks!

**Comment by brownrw8** [comment]
I'm having a similar issue now.  Using gulp and it's 2016 tho

**Comment by danbachar** [comment]
@brownrw8  second that. Fresh, out of the box yeoman angular generaotr, using gulp, sass and bootstrap.
