### ISSUE TITLE
Unable to execute grunt test in the YO tutorial

### ISSUE THREAD

**Issue by dematic-rodrigo-silveira** [yeoman/generator-angular#1210]
I'm an experienced software engineer, have been using AngularJS for a few years, mostly without any supporting development framework. Earlier this year I adopted [Lineman.js](http://linemanjs.com/) and, although I've enjoyed using it, it has a few shortcomings that warranted me to consider alternatives: a) it is not that simple to customize, it is written most in _coffee_, and I have no desired to learn _coffee_. 

A colleague suggested I give [Yeoman](http://yeoman.io/) another try, which I had overruled in favor of [Lineman.js](http://linemanjs.com/); unfortunately, I'm stuck on its tutorial [step 8](http://yeoman.io/codelab/write-unit-tests.html), whereby _karma_ is not found, as described below. Thanks in advance for any suggestions anyone might have to help me with this.

### STEPS to Reproduce
 * Execute the tutorial's steps 1-8
 * Resolve the peer dependencies manually
 * Execute _grunt test_ 

### Observed Behavior
The following output is shown:
```bash
[ mytodo ]$  grunt test
Running "clean:server" (clean) task
>> 1 path cleaned.

Running "wiredep:app" (wiredep) task

Running "wiredep:test" (wiredep) task

Running "concurrent:test" (concurrent) task
    
    Running "copy:styles" (copy) task
    Copied 1 file
    
    Done, without errors.
    
    
    Execution Time (2015-11-15 22:25:00 UTC)
    loading tasks               109ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 81%
    loading grunt-contrib-copy   12ms  ▇▇▇▇ 9%
    copy:styles                  13ms  ▇▇▇▇ 10%
    Total 134ms
    
Running "postcss:server" (postcss) task
>> 1 processed stylesheet created.

Running "postcss:dist" (postcss) task
>> 1 processed stylesheet created.

Running "connect:test" (connect) task
Started connect web server on http://localhost:9001
Loading "grunt-karma.js" tasks...ERROR
>> Error: Cannot find module 'karma'
Warning: Task "karma" failed. Use --force to continue.

Aborted due to warnings.


Execution Time (2015-11-15 22:25:00 UTC)
loading tasks                  110ms  ▇▇▇▇▇▇▇▇▇▇▇ 12%
wiredep:app                    107ms  ▇▇▇▇▇▇▇▇▇▇▇ 12%
wiredep:test                    12ms  ▇▇ 1%
concurrent:test                432ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 48%
loading grunt-postcss           37ms  ▇▇▇▇ 4%
postcss:server                 108ms  ▇▇▇▇▇▇▇▇▇▇▇ 12%
loading grunt-contrib-connect   48ms  ▇▇▇▇▇ 5%
connect:test                    19ms  ▇▇ 2%
Total 900ms
```
**Please observe the karma not found log entry above**.

### Note
In trying to solve this problem I found a SO reference [Cannot find module 'karma' while using grunt](http://stackoverflow.com/questions/19203051/cannot-find-module-karma-while-using-grunt). It recommends re-installing *yo generator-karma*, which I did; its output below, run immediately before running _grunt test_ suggests my YO installation is healthy:
```bash
[ mytodo ]$  sudo npm i -g yo generator-karma
/usr/local/bin/yo -> /usr/local/lib/node_modules/yo/lib/cli.js

> yo@1.5.0 postinstall /usr/local/lib/node_modules/yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version

Everything looks all right!
/usr/local/lib
├── generator-karma@1.0.0 
└── yo@1.5.0 

[ mytodo ]
```

### Expected Behavior
The _grunt test_ output must reflect what is shown in the tutorial:
<img width="830" alt="screen shot 2015-11-15 at 2 52 33 pm" src="https://cloud.githubusercontent.com/assets/10092790/11171576/a3f36d8a-8ba8-11e5-9eb8-fbf1f7f340d4.png">

**Comment by eddiemonge** [comment]
First off, excellent bug report!

If generator-karma wasn't installed when you generated the project, then the necessary things might not have been installed as well. Check you package.json for karma related things. I feel like they might not be there. If they aren't, try generating a new project and test that.

**Comment by dematic-rodrigo-silveira** [comment]
Hi Edd - The package.json file had a number of references to karma.

I saved the old project and created a new mytodo project; i got a number of peerDependency warnings at the end of the project installation - I suspect that there is something wrong with how I installed my node modules since the mentioned dependencies are all installed.

Next, after updating a few of the mytodo files and installing a couple of additional libraries, I ran the tests and got the same result as above.

**Comment by HeinzObran** [comment]
I think my post can help you. I also had problems with dependencies. Have a look in my article https://github.com/yeoman/generator-angular/issues/1215?

Sincerly Heinz

**Comment by dematic-rodrigo-silveira** [comment]
Applying the changes suggested in [#1215](https://github.com/yeoman/generator-angular/issues/1215) worked. Thanks!

**Comment by dematic-rodrigo-silveira** [comment]
Closing the issue, although I would hope to see the Tutorial work seamlessly.

**Comment by HeinzObran** [comment]
Dear Rodrigo,

 

Thank you for your feedback. I am glad that I could help you.

 

Sincerely Heinz

 

Von: Rodrigo Silveira [mailto:notifications@github.com] 
Gesendet: Montag, 23. November 2015 00:53
An: yeoman/generator-angular <generator-angular@noreply.github.com>
Cc: HeinzObran <heinz.obran@gmail.com>
Betreff: Re: [generator-angular] Unable to execute grunt test in the YO tutorial (#1210)

 

Applying the changes suggested in #1215 <https://github.com/yeoman/generator-angular/issues/1215>  worked. Thanks!
