### ISSUE TITLE
Changing folders structure

### ISSUE THREAD

**Issue by adampietrasiak** [yeoman/generator-angular#1211]
I'd like to use this generator with node Sails.js framework.

It requires that main html files like index.html are in `/views` folder of Sails and all loaded assets are in `/assets` folder so `/assets/somepath/file.js` is loaded as `localhost/somepath/file.js`

Is it possible to modify generator config easly so it'd adjust to such structure without loosing all features like generating or injecting etc?

**Comment by eddiemonge** [comment]
Not at the moment. And you could use Sails as a pure api server and this as a standalone static site.

**Comment by eddiemonge** [comment]
also see https://github.com/yeoman/generator-angular/issues/553
