### ISSUE TITLE
jit-grunt: Plugin for the "compass" task not found.

### ISSUE THREAD

**Issue by dhuyvetter** [yeoman/generator-angular#1212]
I get an error running `grunt build`: 

	Running "concurrent:dist" (concurrent) task
		Warning: 
		jit-grunt: Plugin for the "compass" task not found.
		If you have installed the plugin already, please setting the static mapping.
		See https://github.com/shootaroo/jit-grunt#static-mappings
		
		Warning: Task "compass:dist" failed. Use --force to continue.
		
		Aborted due to warnings.

In my Gruntfile.js hte static mapping is already present, which is the solution also proposed for almost identical issues #1129 and #1135 

	  require('jit-grunt')(grunt, {
		useminPrepare: 'grunt-usemin',
		ngtemplates: 'grunt-angular-templates',
		cdnify: 'grunt-google-cdn'
	  });

**Comment by FritzH321** [comment]
Make sure to install compass.

**Comment by dhuyvetter** [comment]
I have `Successfully installed compass-1.0.3` but stil get: 

	$ grunt buildRunning "clean:dist" (clean) task
	>> 0 paths cleaned.

	Running "wiredep:app" (wiredep) task

	Running "wiredep:test" (wiredep) task

	Running "wiredep:sass" (wiredep) task

	Running "useminPrepare:html" (useminPrepare) task
	Configuration changed for concat, uglify, cssmin

	Running "concurrent:dist" (concurrent) task
		Warning: 
		jit-grunt: Plugin for the "compass" task not found.
		If you have installed the plugin already, please setting the static mapping.
		See https://github.com/shootaroo/jit-grunt#static-mappings
		
		Warning: Task "compass:dist" failed. Use --force to continue.
		
		Aborted due to warnings.
		
		
		Execution Time (2015-11-17 11:36:12 UTC)
		loading tasks  209ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 99%
		Total 211ms Use --force to continue.
		    
		    Aborted due to warnings.
		

	Execution Time (2015-11-17 11:36:11 UTC)
	loading tasks         134ms  ▇▇▇▇▇ 12%
	wiredep:app           159ms  ▇▇▇▇▇▇ 14%
	wiredep:test           12ms  ▇ 1%
	wiredep:sass           12ms  ▇ 1%
	loading grunt-usemin   61ms  ▇▇▇ 6%
	useminPrepare:html     21ms  ▇ 2%
	concurrent:dist       687ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 62%
	Total 1.1s

Or is there a npm verwion of compass I need to install? I got it via `$ gem install compass`

**Comment by dhuyvetter** [comment]
OK, found the missing command: `npm install grunt-contrib-compass --save-dev`

**Comment by eddiemonge** [comment]
It should already have been installed if you selected the compass option: https://github.com/yeoman/generator-angular/blob/master/templates/common/root/_package.json#L37
