### ISSUE TITLE
imagemin issue

### ISSUE THREAD

**Issue by lianyi** [yeoman/generator-angular#1213]
Getting the following error when running *grunt build*

```javascript
 Warning: Running "imagemin:dist" (imagemin) task
Fatal error: Cannot read property 'contents' of undefined
```

Version information:
```bash
win7>yo --version
1.5.0
win7>npm --version
2.10.1
win7>node --version
v0.12.4

name: 'angular-generator',  'dist-tags': { latest: '0.0.5' }
```

**Comment by DatTran** [comment]
1+

**Comment by eddiemonge** [comment]
Use the github master version from this as there is a fix but I haven't released a version with that change in it yet

**Comment by eddiemonge** [comment]
see #1214

**Comment by lianyi** [comment]
thanks

**Comment by newls** [comment]
hey! thanks,
i wondered about already generated projects which have the bug

I suggest saying that project maintainer should replace in package.json

"grunt-contrib-imagemin": "^what.you.have", 
to 
"grunt-contrib-imagemin": "^1.0.0",

I changed on a already generated project :

"grunt-contrib-imagemin": "^0.9.2", 
to 
"grunt-contrib-imagemin": "^1.0.0",


But this is of course not related to the fact they must refresh their generator-angular via git, until 0.15.0,
for upcoming projects they want to generate.

I hope I'm not wrong on that.
