### ISSUE TITLE
yo angular needs updates

### ISSUE THREAD

**Issue by HeinzObran** [yeoman/generator-angular#1215]
Dear developers,
i resolved some problems, which occured during my yo angular process. So i will tell you what i done to resolve some problems. I am working on a Windows 10 System and develope with WebStorm 11.0.1.
I use the latest generator-angular 0.14.0. My greatest problem occured with grunt build. It aborts the routine with an error:

```
Warning: Running "imagemin:dist" (imagemin) task
Fatal error: Cannot read property 'contents' of undefined

```
Also a new project-setup with yo angular results in:
```
npm WARN EPEERINVALID karma-phantomjs-launcher@0.2.1 requires a peer of karma@>=0.9 but none was installed.
    npm WARN EPEERINVALID karma-phantomjs-launcher@0.2.1 requires a peer of phantomjs@>=1.9 but none was installed.
    npm WARN EPEERINVALID grunt-karma@0.12.1 requires a peer of karma@^0.13.0 || >= 0.14.0-rc.0 but none was installed.
    npm WARN EPEERINVALID karma-jasmine@0.3.6 requires a peer of jasmine-core@* but none was installed.
```

I resolved this with:
`npm install --save-dev karma grunt-karma phantomjs karma-phantomjs-launcher jasmine-core karma jasmine`

I analyzed that my greatest problem depends on the version of grunt-contrib-imagemin. A look in package.json shows:
`"grunt-contrib-imagemin": "^0.9.2"`

So i installed the new version with:
```
npm uninstall --save-dev grunt-contrib-imagemin
npm install --save-dev grunt-contrib-imagemin
```

This results in "grunt-contrib-imagemin": "^1.0.0"

Now i can use the grunt build successfully. Yo is realy a great thing.

Sincerly Heinz

**Comment by dematic-rodrigo-silveira** [comment]
Heinz - Thanks for the good work. I need a little help with your note. Does it suggest that the steps therein should be taken after I follow the recommended steps to install YO and create a project?

Regards
Rodrigo

**Comment by eddiemonge** [comment]
Right, this is well issued in the tracker. npm3 has changed things. Closing as a duplicate

**Comment by yuanzfy** [comment]
npm install --save-dev karma
this command will install karma and add it to the package.json

**Comment by umair-khanzada** [comment]
Great just update "grunt-contrib-imagemin" version
"grunt-contrib-imagemin": "^0.9.2"
to
 "grunt-contrib-imagemin": "^1.0.0"
and it's works good 
a big thanks to @HeinzObran

**Comment by umair-khanzada** [comment]
Great just update "grunt-contrib-imagemin" version
"grunt-contrib-imagemin": "^0.9.2"
to
 "grunt-contrib-imagemin": "^1.0.0"
and it's works good 
a big thanks to @HeinzObran
