### ISSUE TITLE
Error Unmet peer depedency

### ISSUE THREAD

**Issue by ColoArg93** [yeoman/generator-angular#1216]
Hello, i have a problem. 

First i execute: <code>npm install -g grunt-cli bower yo generator-karma generator-angular</code>

Then i execute <code>yo angular</code> inside my project folder. I choose the options:
- Use gulp instead of grunt? NO
- Include Bootstrap? YES
- Use sass version of bootstrap? NO
- Modules to include? (By default, i press enter)

 and i have this error:

```
module.js:339
    throw err;
    ^

Error: Cannot find module 'download'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\ivan\AppData\Roaming\npm\node_modules\generator-karma\node_modules\yeoman-generator\lib\actions\fetch.js:3:16)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

Well, so i manually install the module with <code>npm intall -g download</code>
It seems it's all right, so i execute <code>yo angular</code> and then, i have another error, cannot find another module, so i manually install it, and the process is repeated infinitely.

So, i newly try to download the angular generator but only with <code>npm install -g generator-angular</code> but i have the following error:

<code>c:\ProbandoGeneradorAngular>npm install -g generator-angular</code>
<code>npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'</code>
<code>npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'</code>
<code>C:\Users\ivan\AppData\Roaming\npm</code>
<code>├── generator-angular@0.14.0</code>
<code>└── UNMET PEER DEPENDENCY generator-karma@>=0.9.0</code>
<code>npm WARN EPEERINVALID generator-angular@0.14.0 requires a peer of generator-karma@>=0.9.0 but none was installed.</code>

Can anyone help me, please?

**Comment by eddiemonge** [comment]
The unmet peer deps are due to npm3. Take a look at the other issues here around npm3 for a solution. Basically you have to install those dependencies manually now.
