### ISSUE TITLE
Update grunt-contrib-imagemin to 1.0.0

### ISSUE THREAD

**Issue by jabaa** [yeoman/generator-angular#1217]
Ubuntu 15.10
npm@3.4.1

When I generate an angular project and try to build it with "grunt build" I get an error from imagemin. The file yeoman.png can't be minified (no content). After updating in "package.json" to "grunt-contrib-imagemin": "^1.0.0" build runs without error.

**Comment by eddiemonge** [comment]
Oh. It already is: https://github.com/yeoman/generator-angular/blob/master/templates/common/root/_package.json#L43
