### ISSUE TITLE
incompatibilities with angularjs material

### ISSUE THREAD

**Issue by pulkitnandan** [yeoman/generator-angular#1229]
I have been trying to not learn bootstrap from twitter but rather using my grey matter to dive into the world of UI design as presented by google here "https://www.google.co.in/design/spec/material-design/introduction.html" which seemed to me a more college books like comprehensive understanding the design of user interfaces which is certainly missing from bootstrap . I came across "https://material.angularjs.org/"  which is an implementation of Material Design in Angular.js. I built already some apps in a equivalent time which it take me to understand bootstrap with yeoman's jhipster generator. 

The problem I'm feeling now is been posted already here "https://github.com/angular/material/issues/6213" but I could not find solution. I was trying to downgrade or upgrade my angular generator dependencies but missed it completely, I shall post the problems I'm facing after an more careful attempt but having an option for angular-material as well as we currently have the option for bootstrap would have been nice. So its a feature request from you  guys, will be definitly try on my own again.while I'm open to know the pro and cons of using material design over bootstrap.

**Comment by eddiemonge** [comment]
You should be able to add that into your app after you generate using Bower. Try asking/looking on stackoverflow as I'm sure this has been solved there.
