### ISSUE TITLE
jit-grunt: Plugin for the "karma" task not found.

### ISSUE THREAD

**Issue by ryanburnett** [yeoman/generator-angular#1230]
I just downloaded generator-angular and created a new project:
* npm install -g grunt-cli bower yo generator-karma generator-angular
* mkdir my-new-project && cd $_
* yo angular

When I `grunt` I get this error:

```
jit-grunt: Plugin for the "karma" task not found.
If you have installed the plugin already, please setting the static mapping.
See https://github.com/shootaroo/jit-grunt#static-mappings

Warning: Task "karma" failed. Use --force to continue.

Aborted due to warnings.
```

When I follow the [static mappings](https://github.com/shootaroo/jit-grunt#static-mappings) and edit my Gruntfile.js to replace this:

```
  require('jit-grunt')(grunt, {
    useminPrepare: 'grunt-usemin',
    ngtemplates: 'grunt-angular-templates',
    cdnify: 'grunt-google-cdn'
  });
```

...with this:

```
require('jit-grunt')(grunt, {
  sprite: 'grunt-spritesmith',
  foo: '@abc/grunt-foo',        // for private modules.
  bar: 'custom/bar.js'          // for custom tasks.
});
```

...I get the same error.

I also ran:

```
$ npm install -g jit-grunt
npm WARN peerDependencies The peer dependency grunt@~0.4.0 included from jit-grunt will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```

...but the error persists.

Any ideas how I can avoid this error?

P.S. I'm running:
* Windows 7
* generator-angular 0.14.0
* npm 2.14.7
* bower 1.7.0
* grunt-cli v0.1.13
* grunt v0.4.5

**Comment by peterkwidjaja** [comment]
most probably karma is not installed due to the new npm installation policy.
try `npm install karma --save-dev`

**Comment by eddiemonge** [comment]
what peter said. If that doesn't fix your issue, let me know and I'll reopen this.

**Comment by ryanburnett** [comment]
Great thanks @peterkwidjaja and @eddiemonge - that worked perfectly.

**Comment by jaspersorrio** [comment]
Doing ````npm install grunt-karma karma karma-phantomjs-launcher karma-jasmine jasmine-core phantomjs --save-dev```` helped!

**Comment by ArtStepanyuk** [comment]
I can confirm jaspersorrio solutions worked for me

**Comment by MaxFlower** [comment]
@peterkwidjaja solution doesn't work for me, I tried npm install grunt-karma karma karma-phantomjs-launcher karma-jasmine jasmine-core phantomjs --save-dev and now all right/ Great thanks for  ArtStepanyuk.

**Comment by alirazagsyed** [comment]
Didn't work for me, "which removed message - deprecated phantomjs@2.1.3: Package renamed to phantomjs-prebuilt".

- npm install grunt-karma karma karma-phantomjs-launcher karma-jasmine jasmine-core phantomjs --save-dev

Did tweak,
- "npm install grunt-karma karma karma-phantomjs-launcher karma-jasmine jasmine-core phantomjs-prebuilt --save-dev".

change the phantomjs to phantomjs-prebuilt

**Comment by vollpo** [comment]
@alisyed-drupalmaze Thanks your tweak did the trick.

**Comment by EduardoAC** [comment]
@jaspersorrio I had to include all of these files when I deleted my node_modules. However the first time I installed "yo angular". it was working. What do you think it could be the problem here?

**Comment by Rana283** [comment]
ERROR [config]: Invalid config file!   SyntaxError: Unexpected identifie at exports.runInThisContext (vm.js:53:16)                    at Module._compile (module.js:387:25)                        at Object.Module._extensions..js (module.js:422:10)          at Module.load (module.js:357:32)                            at Function.Module._load (module.js:314:12)                  at Module.require (module.js:367:17)                         at require (internal/module.js:16:19)                    ...........
this issue am facing while am useing this command

**Comment by thekennysong** [comment]
+1 for @jaspersorrio thanks!

**Comment by webexninja** [comment]
Thanks  @jaspersorrio .
Lucky you updated it yesterday and i got the issue today :100:

**Comment by jaspersorrio** [comment]
@eduardoac It could be because phantomjs changed their name to phantomjs-prebuilt

Buts that's just a guess. Without the error messages it will be too hard to tell.

**Comment by EduardoAC** [comment]
@jaspersorrio good point, but it's solve adding the dependencies that you point it before so it's not big deal.

Thanks for your help

**Comment by afcosta-ibm** [comment]
+1 for @jaspersorrio thanks!

**Comment by kentoj** [comment]
I can also confirm that @jaspersorrio's solution worked for me. I am using a Mac and this command solved my problems when run from the root directory of my project: `npm install grunt-karma karma karma-phantomjs-launcher karma-jasmine jasmine-core phantomjs-prebuilt --save-dev`

**Comment by psahni** [comment]
Thanks @jaspersorrio

**Comment by talevskiigor** [comment]
+1 for @jaspersorrio

**Comment by Nek-** [comment]
@eddiemonge This still is an issue

**Comment by pod4g** [comment]
MARK

**Comment by astrapi69** [comment]
I can also confirm that @jaspersorrio's solution worked for me.

**Comment by ZaLiTHkA** [comment]
All of the `npm install` commands suggested by users include packages that are already installed by default, the only one I was missing from my generated project (using `0.15.1`) was `grunt-karma`.. After installing that, my tests ran just fine, no need to install or change anything else..

Looking at the master branch `/templates/common/root/_package.json` file, I see the template includes `gulp-karma` so that one is just fine. However, there's no `grunt-karma` listed there even though `Gruntfile.js` references a `karma` task, so is this not simply a missing `devDependancy` in the generated project?

**Comment by vivdev** [comment]
confirm this worked for me on windows 10 64 bit: 

> jaspersorrio commented on Dec 26, 2015
Doing npm install grunt-karma karma karma-phantomjs-launcher karma-jasmine jasmine-core phantomjs-prebuilt --save-dev helped!

> Edited on 21st Feb 2016 to point to the right solution.

**Comment by julianbei** [comment]
confirmed!

**Comment by FepAguilar** [comment]
What @jaspersorrio work perfect for me! +1

**Comment by HeshamAbdalla** [comment]
@MaxFlower Thanks man this one worked for me :+1:

**Comment by javierojeda** [comment]
@jaspersorrio thanks a lot, I've been looking for this for more than two weeks and your solutions finally fixed it!! Thanks a lot!!

**Comment by wellington1993** [comment]
Thanks @jaspersorrio

**Comment by ducin** [comment]
Would be nice if it was fixed in the generator :) For me, the whole difference was this:

```
diff --git a/package.json b/package.json
index 8d722db..adc9557 100644
--- a/package.json
+++ b/package.json
@@ -19,6 +19,7 @@
     "grunt-filerev": "^2.1.2",
     "grunt-google-cdn": "^0.4.3",
     "grunt-jscs": "^1.8.0",
+    "grunt-karma": "^1.0.0",
     "grunt-newer": "^1.1.0",
     "grunt-ng-annotate": "^0.9.2",
     "grunt-postcss": "^0.5.5",
```

and it made karma work.

**Comment by ytachi0026** [comment]
@jaspersorrio it works for me, thanks a bunch

**Comment by dreavega** [comment]
@jaspersorrio after running "npm install grunt-karma karma karma-phantomjs-launcher karma-jasmine jasmine-core phantomjs-prebuilt --save-dev"
I keep having Phontomjs failures when running grunt/ grunt test// grunt karma
Any suggestions to clean those up..?  
- no0b here

**Comment by harishkumar460** [comment]
Solution by @ZaLiTHkA works for me. Thanks alot

**Comment by jaspersorrio** [comment]
Hi @dreavega! Can you post the error msg so we can help you debug? (:

**Comment by YouriAckx** [comment]
@jaspersorrio The above suggested solution to manually install several dependencies may be too broad; see [this comment](https://github.com/yeoman/generator-angular/issues/1303#issuecomment-206858804). Only `grunt-karma` seems to be needed. BTW #1303 is closed, so the workaround won't be necessary for long anyway.

**Comment by jaspersorrio** [comment]
It was intended to be broad to catch all errors. For @ZaLiTHkA case, he only required grunt-karma because he already has the other dependencies but that may not be the case for other developers.

#1303 is not closed yet. And this workaround will stay as long as this generator is not updated by the developers.

It's been 5 months since the latest commit.

**Comment by ZaLiTHkA** [comment]
@YouriAckx, @jaspersorrio: My comment on the linked issue was specific to that case and for that user. The fact that my personal experience was the same issue doesn't have any bearing in that comment.

Although, as I mentioned further above in this thread, every time I have seen this issue reported with enough detail to debug, it's been missing just this one package. Note: there are some other reported issues (both open and closed) that are very similar, but not the exactly same.

I've asked for [some clarification](https://github.com/yeoman/generator-angular/pull/1308#issuecomment-217851335) on this behaviour, since this is something that is meant to be generated by the internal call to `generator-karma`, but I've had no response just yet. :/

**Comment by sergiodiezdepedro** [comment]
@jaspersorrio proposal worked quite fine here. Linux OS. Many thanks, pal.

**Comment by pixelbandito** [comment]
@eddiemonge So, there's a fix for this issue documented on this page, but... shouldn't this fix be integrated into the generator? Or at least the usage docs?

I tried using `yo angular` today, and my angular-generator version is 0.15.1 (looks up to date with the repo), and this problem still occurred.

**Comment by jaspersorrio** [comment]
@pixelbandito this repo has not been updated since 5th January.

As you can see from the image, the last commit was jan 5th.

<img width="1280" alt="screen shot 2016-08-17 at 10 40 35 pm" src="https://cloud.githubusercontent.com/assets/10573718/17740585/bec6092c-64cb-11e6-9248-7170cac2dcc8.png">

**Comment by pixelbandito** [comment]
@jaspersorrio Actually, as you can see from _this_ image, the last commit was January 4th. 

(Guess we're in different timezones. 😄 )

![image](https://cloud.githubusercontent.com/assets/304177/17740952/1c96a8d4-6460-11e6-8f45-d42938666cea.png)

**Comment by pixelbandito** [comment]
@jaspersorrio Actually, as you can see from _this_ image, the last commit was January 4th. 

(Guess we're in different timezones. 😄 )

![image](https://cloud.githubusercontent.com/assets/304177/17741025/641b89b8-6460-11e6-8638-356520e8aad2.png)

**Comment by m477r33d** [comment]
I ran the above npm install and it resolved the karma error, but now I'm seeing
`ReferenceError: Can't find variable: module in spec/controllers/main.js (line 6)`

**Comment by ZeroSunny** [comment]
Thanks @jaspersorrio 
I can also confirm that your solution worked for me.
npm install grunt-karma karma karma-phantomjs-launcher karma-jasmine jasmine-core phantomjs-prebuilt --save-dev

**Comment by hoangdangninh** [comment]
npm install grunt-karma --> works for me

**Comment by simonbuehler** [comment]
can this be true that this is so totally unmaintained? still not fixed after a year ...

**Comment by jbouclier** [comment]
@jaspersorrio 's [solution](https://github.com/yeoman/generator-angular/issues/1230#issuecomment-167261260) is still working.

**Comment by kedrovski** [comment]
@jaspersorrio thanks!
`npm install grunt-karma karma karma-phantomjs-launcher karma-jasmine jasmine-core phantomjs-prebuilt --save-dev`
Works great!

**Comment by enriquezrene** [comment]
For me works:
rm -r node_modules
npm install
bower install

**Comment by dalvarezsmiet** [comment]
@jaspersorrio solution still working as a charm. Thanks!
`npm install grunt-karma karma karma-phantomjs-launcher karma-jasmine jasmine-core phantomjs-prebuilt --save-dev`
