### ISSUE TITLE
Unclear of how to add external scss

### ISSUE THREAD

**Issue by stephenycchang** [yeoman/generator-angular#1234]
Similar to issue #897 , I'm still unclear of how to manually add additional stylesheets. 

I've added a scss file under app/styles where the main.scss is located, recompiled through grunt and when I view source, it's still not there. 

Based on the gruntfile.js
compass: {
        files: ['<%= yeoman.app %>/styles/{,*/}*.{scss,sass}'],
        tasks: ['compass:server', 'postcss:server']
      }

It should pick up any scss files in that folder? 

When I check the .tmp folder, it shows that it's there but when I check the dist folder, it's not. 

Other than manually adding it to the header, is there a better practice with this?

Thank you!

**Comment by tomasalmeida** [comment]
Hi @stephenycchang, how did you figure out to solve this problem?

**Comment by stephenycchang** [comment]
Hi @tomasalmeida , I ended up just using `@import '/stylesheetpath` on the main.scss file.

**Comment by tomasalmeida** [comment]
same thing from my side :) 

Thank you :)
