### ISSUE TITLE
npm WARN deprecated message for lodash@1.0.2 & npmconf@2.1.2

### ISSUE THREAD

**Issue by ryanburnett** [yeoman/generator-angular#1244]
Steps to reproduce:

`yo angular`

```
Would you like to use Gulp (experimental) instead of Grunt? N
Would you like to use Sass (with Compass)? Y
Would you like to include Bootstrap? Y
Would you like to use the Sass version of Bootstrap? Y
Which modules would you like to include? Enter
```

...

```
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN prefer global jshint@2.8.0 should be installed with -g
```

The installer hangs for a few minutes after it runs into the above messages. I tried `npm install -g lodash npmconf` but this issue persists. Any idea how to avoid these warnings? 

Thank you!

P.S. I'm running:

* Windows 7
* generator-angular 0.15.1
* npm 2.14.7
* bower 1.7.2
* grunt-cli v0.1.13
* grunt v0.4.5

**Comment by eddiemonge** [comment]
They are just warnings and can be ignored. When the generator is updated they should go away

**Comment by ryanburnett** [comment]
OK - thanks @eddiemonge
