### ISSUE TITLE
File index.html not updated vendor

### ISSUE THREAD

**Issue by bArraxas** [yeoman/generator-angular#1246]
Hi,

I'm under windows 7 and in all my projects the file index.html never updated when I install some packages after the project is created. Is it normal ?

Example : 
Suppose an existing webapp-angular project, I type "bower install fontawesome --save"

-> bower.json is updated correctly
-> index.html (vendors sections) not updated

Is it normal and is it possible to param it ?

Thanks very much,

**Comment by eddiemonge** [comment]
Yes that is normal. Bower does not insert those. Wiredep does. If you run `grunt wiredep` it should get updated.

**Comment by bArraxas** [comment]
Hi i'm beginer with those technologies, can you explain me how to set up "wiredep" with gulp ?
I haven't grunt. I have looking for wiredep in node_modules but i can't find "gulp-wiredep" or "wiredep"
Thank you

**Comment by arno-s** [comment]
hey bArraxas, there's an example at the wiredep repo located [here](https://github.com/taptapship/wiredep#build-chain-integration). 
Basically just install wiredep with `npm i --save wiredep` and edit your gulpfile.

**Comment by bArraxas** [comment]
Hi, thanks very much i'll try it this weekend ;-)
