### ISSUE TITLE
Unable to generate plain JavaScript files if TypeScript or CoffeeScript files are present

### ISSUE THREAD

**Issue by andrewsnewyyz** [yeoman/generator-angular#1249]
When dealing with a project that already contains *.coffee files:

- Using the command line argument --coffee=false does not generate plain JavaScript files.

When dealing with a project that already contains *.ts files:

- Using the command line argument --typescript=false does not generate plain JavaScript files.
- Using the command line argument --coffee creates TypeScript files.

Mac OS
Yo version 1.6.0
Generator-angular version 0.15.1
Node version 5.3.0

**Comment by eddiemonge** [comment]
Correct. You really shouldn't mix different things.

**Comment by andrewsnewyyz** [comment]
Well we are in the process of migrating an existing generator-based project from JavaScript to TypeScript and for legacy support purposes we require that both types of elements be able to be generated. Also, you should probably read the following section of your own Readme file before giving such a flippant answer:

"A project can mix TypeScript, CoffeScript, and JavaScript files.

To output JavaScript files, even if CoffeeScript (or TypeScript) files exist (the default is to output CoffeeScript files if the generator finds any in the project), use --coffee=false and/or --typescript=false."

Don't claim that a feature exists and then not support it when it is broken.

**Comment by eddiemonge** [comment]
I did not see that got added to the readme. That is incorrect since I think there is still the bug in the options that treats the false flag the same as undefined meaning it doesn't even see the option

**Comment by andrewsnewyyz** [comment]
Is that an options bug in yeoman itself? If that is the case, might I suggest adding a --javascript option instead of --coffee=false or --typescript=false to override the automatic file detection?
