### ISSUE TITLE
"yo angular" failed with error " Error: Cannot find module 'xtend' "

### ISSUE THREAD

**Issue by fabio-coolshop** [yeoman/generator-angular#1251]
I use

<pre>
$ npm -version
3.5.3
$ node -v
v4.2.5
</pre>

and after wizard...

<pre>
$ yo angular
     _-----_
    |       |    .--------------------------.
    |--(o)--|    |    Welcome to Yeoman,    |
   `---------´   |   ladies and gentlemen!  |
    ( _´U`_ )    '--------------------------'
    /___A___\    
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

Out of the box I include Bootstrap and some AngularJS recommended modules.

? Would you like to use Gulp (experimental) instead of Grunt? No
? Would you like to use Sass (with Compass)? Yes
? Would you like to include Bootstrap? Yes
? Would you like to use the Sass version of Bootstrap? Yes
? Which modules would you like to include? angular-animate.js, angular-cookies.js, angular-messages.js, angular-route.js, angular-sanitize.js, angular-touch.js
identical app/styles/main.scss
identical app/index.html
identical bower.json
identical .bowerrc
identical package.json
identical Gruntfile.js
identical README.md
   invoke   angular:common:/usr/lib/node_modules/generator-angular/app/index.js
identical     .editorconfig
identical     .gitattributes
identical     .jscsrc
identical     .jshintrc
identical     .yo-rc.json
identical     .gitignore
identical     test/.jshintrc
identical     app/404.html
identical     app/favicon.ico
identical     app/robots.txt
identical     app/views/main.html
identical     app/images/yeoman.png
   invoke   angular:main:/usr/lib/node_modules/generator-angular/app/index.js
identical     app/scripts/app.js
   invoke   angular:controller:/usr/lib/node_modules/generator-angular/app/index.js
identical     app/scripts/controllers/main.js
identical     test/spec/controllers/main.js
module.js:328
    throw err;
    ^

Error: Cannot find module 'xtend'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/generator-karma/node_modules/mem-fs/node_modules/through2/through2.js:3:17)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)

</pre>

thanks for your work!

**Comment by fabio-coolshop** [comment]
remove and reinstall generator-karma :)

**Comment by totallytotallyamazing** [comment]
Thanks @fabio-coolshop that worked for me too!
first `$ npm uninstall -g generator-karma`
then `$ npm install -g generator-karma`
