### ISSUE TITLE
Angula 2 with yeoman ?

### ISSUE THREAD

**Issue by beingsagir** [yeoman/generator-angular#1256]
I am in search for an Angular Generator for Angular 2 beta version. When are we thinking to incorporate this feature into current project ?

**Comment by TheDucc** [comment]
Also very curious about plans for Angular v2.  This was my first and current use case for all my angular work.  But I am starting to look at other generators.

**Comment by agalitsyn** [comment]
+1, and imho it should use gulp by default

**Comment by axetroy** [comment]
i didn't see the plan in yeoman official wesite。
i hope this project can incorporate  this feature

**Comment by aderbas** [comment]
+1 =D

**Comment by eddiemonge** [comment]
When its no longer beta it can be revisited. Also since its completely different, we are still deciding how to handle it
