### ISSUE TITLE
How to structuring a project with mulitple app ?

### ISSUE THREAD

**Issue by ningmo** [yeoman/generator-angular#1273]
I want structuring a project with 5 apps for using _generator-angular _ , 
directory struct like this
```
MyProjects
    apps
        app1
        app2
        app3
        app4
        app5
        common
        package.json
        Gruntfile.js
        common
        ...
```
but i don't know how to configure it , any idea for help?

**Comment by eddiemonge** [comment]
Why does it have to be 5 separate apps? This is also better asked on stackoverflow
