### ISSUE TITLE
File conflict and nothing created in the folder

### ISSUE THREAD

**Issue by victorleungtw** [yeoman/generator-angular#1274]
I'm using node version v4.3.0.

After running the command "yo angular [app-name]",

I got conflicts below:

> Which modules would you like to include? angular-animate.js, angular-cookies.js, angular-resource.j
s, angular-route.js, angular-sanitize.js, angular-touch.js
 conflict app/styles/main.scss
? Overwrite app/styles/main.scss? overwrite
    force app/styles/main.scss
 conflict app/index.html
? Overwrite app/index.html? overwrite
    force app/index.html
 conflict bower.json
? Overwrite bower.json? overwrite
    force bower.json
identical .bowerrc
 conflict package.json
? Overwrite package.json? overwrite
    force package.json
 conflict Gruntfile.js
? Overwrite Gruntfile.js? overwrite
    force Gruntfile.js
 conflict README.md
? Overwrite README.md? overwrite
    force README.md
   invoke   angular:common:/usr/local/lib/node_modules/generator-angular/app/index.js

Then nothing is created in the folder.

**Comment by eddiemonge** [comment]
Seems like you ran it twice. Also could be because the generator needs a serious update which is already documented
