### ISSUE TITLE
why not support the ES6 and typescript in building

### ISSUE THREAD

**Issue by axetroy** [yeoman/generator-angular#1277]
I had saw some issues;
the generator had support to generate the typescript fill and ES6.
but
# ES6
the ES6 just for server not for build.
that mean run `grunt serve` is OK but wrong in `grunt build`;
so,why not add babel to project to compile ES6 to ES5 or add a options to config use ES6 or ES5.

# typescript
like forward
it just generate the typescript file but not compile.

# suggestion
* add `babel` and `polyfill` and `typescript` in project.it can't take many space in your hard disk
* add a options to use `ES6/ES5/typescript` when we generate a app

even the generator is almost perfect.
it can make `generator-angular` perfect and perfect

**Comment by hakanozkaptan** [comment]
+1
