### ISSUE TITLE
Angular gives me Cannot GET / page_name While reloading

### ISSUE THREAD

**Issue by KalaiselvanMahendran** [yeoman/generator-angular#1280]
i did a application using MEAN Stack, while reloading page using browser an getting **Cannot Get / page**

**app.js**
```
var myApp = angular.module('Grunt', ['ngRoute']).
					config(['$routeProvider', '$locationProvider', function($routeProvider, $locationProvider) {

						$routeProvider.when('/home', {
							templateUrl : 'views/home.html', controller : 'homeController'
						});

						$routeProvider.otherwise({redirectTo: '/'});
						$locationProvider.html5Mode({enabled: true, requireBase: false});
					}]);
```

**server.js**
```
var express = require('express');

var app = express();
var port = process.env.PORT || 2323;

app.use(express.static(__dirname + '/server'));
app.use(express.static(__dirname + '/public'));

app.get('/', function(req, res){
	res.sendfile('./server/views/index.html');
});

app.listen(port, function(){
	console.log('server is running on ' + port);
});
```
**Gruntfile.js**
```
module.exports = function(grunt){

	grunt.initConfig({

		// configure nodemon
		nodemon: {
			dev: {
				script: 'server.js'
			}
		}

	});

	//load nodemon
	grunt.loadNpmTasks('grunt-nodemon');

	//register the nodemon task when we run grunt
	grunt.registerTask('default', ['nodemon']);

};
```

while reloading home page am getting error as **Cannot GET /home.**

Help me to sort out this problem am stuck with this....

**Comment by eddiemonge** [comment]
This is outside the scope of this project for now. Ask on stackoverflow or look at this ticket: https://github.com/yeoman/generator-angular/issues/433

**Comment by OskarKlintrot** [comment]
In case some one else is wondering you need to redirect all routes that Node is not using to Angular:
```Javascript
app.get('*', function(req, res) {
  res.sendfile('./server/views/index.html')
})
```
In the header of `index.html` you need to add `<base href="/">`.

**Comment by dgeyzonne** [comment]
Hello,
You should look at this answer that worked for me :
http://stackoverflow.com/a/20553608/4891724

**Comment by curtisnn** [comment]
In case someone else was struggling serving both an API and an angular app from the same Nodejs server, and also removing the '#' from the angular routes, I started at @OskarKlintrot's answer and modified it a little and put it right after serving the api routes.   
```javascript
app.use('/api', routesApi);
app.use(function(req, res) {
    res.sendFile(path.join(__dirname, '/public', 'index.html'));
});
```
