### ISSUE TITLE
Unmet dependency with generator-karma, but my version is up to date

### ISSUE THREAD

**Issue by marianatuma** [yeoman/generator-angular#1282]
I'm trying to install generator-angular with `npm install -g generator-angular`, but I get:

```
├── generator-angular@0.15.1 
└── UNMET PEER DEPENDENCY generator-karma@>=0.9.0

```
However when I try to install generator-karma, I get:

```
├── generator-karma@2.0.0 
└── yo@1.6.0 
```
Which means that my current version of karma is 2.0.0, correct? How can I solve this issue?

**Comment by marianatuma** [comment]
Solved it using `npm install -g grunt-cli bower yo generator-karma generator-angular`

**Comment by Pillman** [comment]
That's perfect

**Comment by khalidit** [comment]
i confirm this solution, thank you 👍
