### ISSUE TITLE
loading grunt-karma.js tasks...error cannot find module 'graceful-fs'

### ISSUE THREAD

**Issue by HalimZamal** [yeoman/generator-angular#1284]
Hello I'm halimzamal I tried to use yeoman and now I have a problem when I tried to compile grunt with `CHROME_BIN=chromium-browser grunt` ... This is an error that I got.. 

`Running "connect:test" (connect) task
Started connect web server on http://localhost:9001
Loading "grunt-karma.js" tasks...ERROR
>> Error: Cannot find module 'graceful-fs'
Warning: Task "karma" failed. Use --force to continue

Aborted due to warnings.`

How to fix it...?

**Comment by eddiemonge** [comment]
Did you try running `npm install`?

**Comment by HalimZamal** [comment]
I used `grunt --force` and works..
