### ISSUE TITLE
How To Get Image Names In JSON To Match Minimized Images in Dist

### ISSUE THREAD

**Issue by ryanburnett** [yeoman/generator-angular#1286]
Steps to reproduce:

`yo angular`

```
Would you like to use Gulp (experimental) instead of Grunt? N
Would you like to use Sass (with Compass)? Y
Would you like to include Bootstrap? Y
Would you like to use the Sass version of Bootstrap? Y
Which modules would you like to include? Enter
```

I have the following (simplified) JSON:

```
$scope.images = [
	{
		src: 'images/orange.jpg'
	},
	{
		src: 'images/cherry.jpg'
	},
	{
		src: 'images/watermelon.jpg'
	},
]
```

Used in this view:

```
<div ng-repeat="image in images">
	<img ng-src="images/{{image.src}}" />
</div>
```

When I run 'grunt build' I get broken images because the images are getting minmized to:

```
- /dist/images/orange.be6ef56b.jpg
- /dist/images/cherry.0ff11af7.jpg
- /dist/images/watermelon.0a68a98b.jpg
```

...however the image paths from the ng-repeat appear as:

```
- /dist/images/orange.jpg
- /dist/images/cherry.jpg
- /dist/images/watermelon.jpg
```
How can I get the image paths to match the minimized image names?

Thank you!

P.S. I'm running:

* Windows 7
* generator-angular 0.15.1
* npm 2.14.7
* bower 1.7.2
* grunt-cli v0.1.13
* grunt v0.4.5

**Comment by eddiemonge** [comment]
First, thats a JS object, not JSON.

Second, to solve this, you need to add a pattern for usemin: https://github.com/yeoman/grunt-usemin#patterns
