### ISSUE TITLE
npm WARN EPEERINVALID generator-angular@0.15.1 requires a peer of generator-karma@>=0.9.0 but none was installed.

### ISSUE THREAD

**Issue by CNliushuang** [yeoman/generator-angular#1290]
npm -v && node -v && yo --version
3.3.12
v5.1.0
1.7.0
npm install -g generator-angular

npm WARN EPEERINVALID generator-angular@0.15.1 requires a peer of generator-karma@>=0.9.0 but none was installed.

can anyone help me?

**Comment by eddiemonge** [comment]
`npm i -g generator-karma`

**Comment by eddiemonge** [comment]
https://github.com/yeoman/generator-angular#usage

**Comment by chitselb** [comment]
Even with generator-karma installed, I am getting the same error

$ npm i -g generator-karma
/home/chitselb/.npm-packages/lib
└── generator-karma@2.0.0 

$ npm install -g generator-angular
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v6.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v6.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@2.1.0: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
/home/chitselb/.npm-packages/lib
├── generator-angular@0.15.1 
└── UNMET PEER DEPENDENCY generator-karma@>=0.9.0

npm WARN generator-angular@0.15.1 requires a peer of generator-karma@>=0.9.0 but none was installed.

**Comment by kenmarshall** [comment]
I have the same exact issue.  I.m on Ubuntu 15.04

**Comment by skanel** [comment]
me too

**Comment by shuyu16** [comment]
I had the same issue, but when I installed them together then it worked `npm install -g generator-karma generator-angular`
