### ISSUE TITLE
yo angular  do not executes successfully 

### ISSUE THREAD

**Issue by pod4g** [yeoman/generator-angular#1294]
I execute the command ```yo angular``` under the directory ```/Users/liyanfeng/work/sku```

but nothing happened,the directory is still empty and no error throwed

what happened ?

**here is the screenshot:**
![First part](http://ww3.sinaimg.cn/large/6fd55a97jw1f1u4y793hvj21kw0taq8z.jpg)
![Second part](http://ww2.sinaimg.cn/large/6fd55a97jw1f1u4y7mfqrj21kw0tvn4a.jpg)
![Third part](http://ww1.sinaimg.cn/large/6fd55a97jw1f1u4y7yemgj21kw0ovafv.jpg)

**Comment by eddiemonge** [comment]
Its because you have a .yo-rc.json file in a parent directory so thats where its getting generated. Your second screenshot shows thats

**Comment by pod4g** [comment]
Thank you!
