### ISSUE TITLE
something wrong with css

### ISSUE THREAD

**Issue by THCloud** [yeoman/generator-angular#1296]
I'm a new learner of FE, and I'm trying to use Yeoman these days, and I just tried to use this generator.
I used gulp instead of grunt.

And after   npm install && bower install, everything is ok.
But when I try     gulp serve

I can't see any css or js of bootstrap and angular in browser.
Is there any problems in the gulpfile.js ?

**Comment by eddiemonge** [comment]
What version are you using? What OS do you have? What options did you select?

**Comment by THCloud** [comment]
yo:    1.7.0
generator-angular: 0.15.1
npm:  3.8.1
node: v5.8.0
OS:   mac
options:  default except the first one (gulp instead of grunt?   Y)

**Comment by eddiemonge** [comment]
Does your `gulp serve`'d index.html file have the references in it?

**Comment by THCloud** [comment]
wait a moment...

**Comment by THCloud** [comment]
No...

**Comment by THCloud** [comment]
Thing are OK if use Grunt.
Maybe the gulp should concat the js and css files?

**Comment by bumprat** [comment]
In every gulp-connect call `$.connect.server(...)`, add this middleware like:
``` javascript
  $.connect.server({
    root:['\.tmp', yeoman.app],
    livereload:true,
    port: 9000,
    middleware:function(connect, opt){
      return [['/bower_components', 
        connect["static"]('./bower_components')]]
    }
  });
```

**Comment by udkazi** [comment]
hello i think you had install sass and gem compass , try to install without sass , your problem will b solved .
npm install -g yo
npm install -g generator-angular
yo angular

when it ask to install sass :- no
when it ask to install gulp insteted to of grunt say:- no

after installtion of all module .

grunt .
grunt serve.
