### ISSUE TITLE
Problem Adding New Scss File

### ISSUE THREAD

**Issue by JimTheMan** [yeoman/generator-angular#1301]
Hello, I chose Sass in the generator's question, "What preprocessor do you want to use". However, when I create a new file and add styles to it nothing happens. Shouldn't gulp be picking up the scss files automatically and injecting them? Do I need to explicitly put a link tag to it somewhere? Thanks!

**Comment by eddiemonge** [comment]
Try restarting the gulp server. Where do you add the files to?

**Comment by JimTheMan** [comment]
I figured it out. I was adding folders in the _src_ directory when the gulp watch talk only looks for files within the _app_ directory.
