### ISSUE TITLE
npm issue out of date?

### ISSUE THREAD

**Issue by beginercoder** [yeoman/generator-angular#1302]
so i'm new here and im trying to learn to code via touchdevelop. Any I installed node and cordova but everytime i try to run a project it says it can't find cordova . I installed the latest version of node too.
![error](https://cloud.githubusercontent.com/assets/17966054/13905607/a72b0f6a-ee92-11e5-851a-66921cdc21ba.PNG)
![error 2](https://cloud.githubusercontent.com/assets/17966054/13905652/2f6aece6-ee94-11e5-8fdf-3661995a3da9.PNG)

**Comment by eddiemonge** [comment]
This isn't a cordova generator or have anything to do with cordova.
