### ISSUE TITLE
Show all generators from command line

### ISSUE THREAD

**Issue by k-funk** [yeoman/generator-angular#1304]
Is there a way to display all the available generators within generator-angular? I expected `yo angular --help` to do show me the list that's on the readme, but it just shows me the usage for the `app` generator. I end up returning to the github repo's readme to see that list every time I work on my project.

**Comment by eddiemonge** [comment]
Have you tried `yo --help`?

**Comment by k-funk** [comment]
That works.
...though, it seems like `yo angular --help` would be the logical place for that to be listed.

**Comment by eddiemonge** [comment]
It would help. But this needs some major upgrades first
