### ISSUE TITLE
grunt serve fail running

### ISSUE THREAD

**Issue by damanzano** [yeoman/generator-angular#1313]
I just installed the lastes version of generator-angular and use it in a empty project, when i executed the serve grunt task i got the following result, and therefore the server never started.

When I use the --force option it works but i want to know id there is step i haved missed

Running "serve" task

Running "clean:server" (clean) task
>> 0 paths cleaned.

Running "wiredep:app" (wiredep) task

Running "wiredep:test" (wiredep) task

Running "wiredep:sass" (wiredep) task

Running "concurrent:server" (concurrent) task
    Warning: Running "compass:server" (compass) task
Warning: not found: compass Use --force to continue.

Aborted due to warnings.

**Comment by eddiemonge** [comment]
`Warning: not found: compass Use --force to continue.`  Do you have compass installed?
