### ISSUE TITLE
yo angular is not working

### ISSUE THREAD

**Issue by strongant** [yeoman/generator-angular#1317]
angular.js:4587Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.5.5/$injector/modulerr?p0=pfApp&p1=Error%3A%2…pjhcpgcdbcibdhbngl%2Fbower_components%2Fangular%2Fangular.min.js%3A21%3A19)
9livereload.js?snipver=1:74 WebSocket connection to 'ws://localhost:35729/livereload' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by vpArth** [comment]
Can not to repeat this one. May be some firewall issue?

**Comment by eddiemonge** [comment]
Yeah i dont think this is a generator issue
