### ISSUE TITLE
Looking for an example project that uses generator-angular

### ISSUE THREAD

**Issue by jamesla** [yeoman/generator-angular#1319]
I am wanting to look over a project that has used this generator and scaffolding and in particular is unit tested properly with all necessary unit tests and mock services in the mock folder.

I am having a bit of trouble working out how the Jasmine unit test dependencies get injected and how to build up the repository of mock services that I think is happening here based on reading through the gruntfile in the style that this generator wants (which I think is quite good).

If somebody could link me a repo that would be greatly appreciated.

**Comment by eddiemonge** [comment]
Check on stackoverflow. the project generates out a basic angular project that you can build on. once its generated then its a normal angular app that most tutorials will apply to.
