### ISSUE TITLE
Error when running cssmin:generated

### ISSUE THREAD

**Issue by clement-escolano** [yeoman/generator-angular#1320]
Hello !

I created a new app (with `yo angular`) and then tried to build it with `grunt`. After installing the test related packages as mentioned here #1218 I encountered an other error which prevents the app from building : 

```
Running "cssmin:generated" (cssmin) task
Warning: Path must be a string. Received undefined Use --force to continue.
```

I am not sure what I need to do (I am very new to grunt and yo) in order to fix the issue.

Here is my configuration : 
generator-angular@0.15.1
npm@3.8.6
yo@1.8.1

Thank you !
Clement

PS : sorry if this is not a generator-angular related issue

**Comment by jangeador** [comment]
I have the same problem.
`Running "cssmin:generated" (cssmin) task
Warning: Path must be a string. Received undefined Use --force to continue.
TypeError: Path must be a string. Received undefined`

**Comment by eddiemonge** [comment]
Have you tried running npm update?

**Comment by clement-escolano** [comment]
Yes, did it again.
Updated npm, node, yo and generator-angular to latest available version.
I ran `yo angular` then `npm install grunt-karma karma karma-phantomjs-launcher karma-jasmine jasmine-core phantomjs-prebuilt --save-dev` then `grunt` and got the same error.

**Comment by eddiemonge** [comment]
did you change anything in the generated code before grunt or just ran it like that?

**Comment by datnordstrom** [comment]
I am also having the same error, with a new install.

**Comment by clement-escolano** [comment]
@eddiemonge 
I didn't change anything (neither the grunt file or any other file).
The commands in my message above are the only thing I did when in a new empty directory.
Also tried (after trying to run `grunt` on the untouched files) to add the cssmin command manually in the grunt file.
Although it works by running `grunt cssmin:generated` the error still remains.

**Comment by dpointk** [comment]
Also have the same issue

**Comment by jangeador** [comment]
Ok guys, I was finally able to run it without error. The problem for me was the node version. I was trying to run it using Node version 6.0.0. I installed a node version manager and started using ``v0.10.45`` and grunt ran just fine.

Hopefully someone who understands this better will shed light on which version of node we should be using.

**Comment by clement-escolano** [comment]
@jangeador Thank you for the solution, it works indeed :) 
What is very strange though, is that when I take the files generated with the node v0.10.45 and copy them in my regular computer, it still doesn't work ! This is crazy...

**Comment by dleangen** [comment]
Thanks! The solution worked for me, too.

**Comment by joshuapowell** [comment]
This worked for me too ... although I'm a little frustrated by that the solution is to downgrade the version of Node.

**Comment by datnordstrom** [comment]
Is this generator still being supported? It's been so long.

**Comment by peterkwidjaja** [comment]
The error is actually on grunt-contrib-cssmin dependency.
You can refer to [Link](https://github.com/gruntjs/grunt-contrib-cssmin/pull/271/commits/11e655873dfa58b6edcda0113cee612f7a6b2ab9?diff=split)
Go to node_modules/grunt-contrib-cssmin/tasks/cssmin.js and change as what the link states.
It works for me.

**Comment by kumarneb** [comment]
Thanks @peterkwidjaja !  That fixed it without downgrading node.  Hope that change is merged in soon.

**Comment by Reedyseth** [comment]
Cool, @peterkwidjaja advice also made it work for me on my node version `v6.2.2`, thanks for the note.

**Comment by dr-martin** [comment]
Thanks for this!, the update has fixed it

**Comment by thiagohmoreira** [comment]
I fixed this to my project simply updating grunt-contrib-cssmin dependency version on package.json:

From: "grunt-contrib-cssmin": `"^0.12.0"

To: "grunt-contrib-cssmin": "^1.0.2"

Probably good to have this updated on the generator too ;)

**Comment by antpowell** [comment]
THANKS @peterblazejewicz after hours of reading and trying to find a fix that worked.

**Comment by nouhouari** [comment]
Update the package.json works for me too

 "grunt-contrib-cssmin": "^1.0.0",

**Comment by abhisharkjangir** [comment]
@peterkwidjaja thnks for the solution

**Comment by Dagim12** [comment]
@peterkwidjaja Thanks. Modifying node_modules/grunt-contrib-cssmin/tasks/cssmin.js as shown in the link worked for.

**Comment by adminlr** [comment]
hello i am running grunt sass command it is giving following error
Warning: Path must be a string. Received undefined Use --force to continue.
please help me as soon as possible
