### ISSUE TITLE
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 0 of 0 ERROR (0.002 secs / 0 secs)

### ISSUE THREAD

**Issue by kuyoonjo** [yeoman/generator-angular#1324]
23 05 2016 00:06:25.711:INFO [karma]: Karma v0.13.22 server started at http://localhost:8080/
23 05 2016 00:06:25.717:INFO [launcher]: Starting browser PhantomJS
23 05 2016 00:06:26.284:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket /#VquRrLcmfpSLu1ljAAAA with id 75510930
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 0 of 0 ERROR (0.002 secs / 0 secs)
Warning: Task "karma:unit" failed. Use --force to continue.

Aborted due to warnings.

This only occurs when I use --typescript

**Comment by eddiemonge** [comment]
Do you have any tests to actually run?

**Comment by kuyoonjo** [comment]
solved by add `.tmp/spec/` to karma config file.
Thank you very much.


On May 23, 2016, at 8:26 PM, Eddie Monge <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you have any tests to actually run?

**Comment by JosephSKh** [comment]
@kuyoonjo can you point me where exactly to add it?
thx
