### ISSUE TITLE
Font-Awesome does not get injected with wiredep

### ISSUE THREAD

**Issue by engemasa** [yeoman/generator-angular#1325]
I included font-awesome into my project via bower. Initially I thought this issue was on the font-awesome project side but as it turns out, they are following specs as per bower. 

My pull-request to font-awesome: https://github.com/FortAwesome/Font-Awesome/pull/9262#issuecomment-220990190
Bower Specs (Response from Font-awesome): https://github.com/FortAwesome/Font-Awesome/pull/6227

**Comment by eddiemonge** [comment]
yeah the new bower spec is not great and has caused nothing but issues imo. which is why we are looking to get away from bower in yeoman projects

**Comment by engemasa** [comment]
For now I just added "css/font-awesome.css" to the "main" node and it works... Small and simple work-around.

**Comment by ryanburnett** [comment]
@engemasa I'm having the same issue - any chance you can post your `bower.json` file?

**Comment by engemasa** [comment]
This is the bower.json file that comes in the font-awesome when installed via bower

**File Location:** `bower_components/font-awesome/bower.json`

```JavaScript
{
  "name": "font-awesome",
  "description": "Font Awesome",
  "keywords": [],
  "homepage": "http://fontawesome.io",
  "dependencies": {},
  "devDependencies": {},
  "license": ["OFL-1.1", "MIT", "CC-BY-3.0"],
  "main": [
    "less/font-awesome.less",
    "scss/font-awesome.scss", // Add the comma at the end of this line
    "css/font-awesome.css" // I manually added this line
  ],
  "ignore": [
    "*/.*",
    "*.json",
    "src",
    "*.yml",
    "Gemfile",
    "Gemfile.lock",
    "*.md"
  ]
}

```

**Comment by stephenrust** [comment]
@engemasa Can you elaborate on where and how exactly you included it?

**Comment by engemasa** [comment]
See my previous post. I edited `bower.json` file for font-awesome which was located in the `bower_components/font_awesome/` folder.
