### ISSUE TITLE
not install karma in project

### ISSUE THREAD

**Issue by erluzi** [yeoman/generator-angular#1328]
├── UNMET PEER DEPENDENCY karma@>=0.10 <=0.13
├─┬ lazypipe@0.2.4 
│ └── stream-combiner@0.0.4 
├── open@0.0.5 
├─┬ rimraf@2.5.2 
│ └── glob@7.0.3 
├── run-sequence@1.2.1 
└─┬ wiredep@2.2.2 
  ├─┬ bower-config@0.5.2 
  │ ├── graceful-fs@2.0.3 
  │ ├── mout@0.9.1 
  │ └── osenv@0.0.3 
  ├─┬ chalk@0.5.1 
  │ ├── ansi-styles@1.1.0 
  │ ├─┬ has-ansi@0.1.0 
  │ │ └── ansi-regex@0.2.1 
  │ ├── strip-ansi@0.3.0 
  │ └── supports-color@0.2.0 
  ├─┬ glob@4.5.3 
  │ └── minimatch@2.0.10 
  ├── lodash@2.4.2 
  ├── propprop@0.3.0 
  └─┬ through2@0.6.5 
    └── readable-stream@1.0.34 

npm WARN gulp-karma@0.0.4 requires a peer of karma@>=0.10 <=0.13 but none was installed.

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn gulp ENOENT
    at exports._errnoException (util.js:953:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by mtree** [comment]
Same problem here.

**Comment by coreyc** [comment]
One solution is to add  `"karma": ">= 0.10 <= 0.13"` to package.json under the `"peerDependencies"` section.  Not sure if this is how the project team would like to handle this though, if anyone is even maintaining this project anymore.  If they're good with it, I'll submit  a PR.

**Comment by erluzi** [comment]
thanks

**Comment by tghelere** [comment]
try first
sudo npm update

**Comment by eddiemonge** [comment]
No, don't try `sudo npm` anything. You should not be using sudo with npm
