### ISSUE TITLE
Uncaught Error when using "grunt serve"

### ISSUE THREAD

**Issue by Philin-Anton** [yeoman/generator-angular#1330]
Hi, guys!

`Uncaught Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3`

Here is what, in the creation and launch of the project.
It's connected due to incorrect conditions dependency in bower.json. Fix is it, please.
Thunk you!

**Comment by tjwudi** [comment]
Also having this issue. 

In [bootstrap-sass official repo](https://github.com/twbs/bootstrap-sass/blob/master/bower.json#L33), it does require `"jquery": "1.9.1 - 2"`. Yet in **bower_components/bootstrap-sass-official**, it's `"jquery": ">= 1.9.0"`. Guess there is a problem with bootstrap-sass-official repo itself.

**Comment by Philin-Anton** [comment]
Thank you! I was resolved this problem, as you say me.

**Comment by eddiemonge** [comment]
Yeah thats in bootstrap and should be fixed there since that is where the dependency is coming from

**Comment by tjwudi** [comment]
May want to follow up here twbs/bootstrap-sass#1048
