### ISSUE TITLE
Erro accessing local JSON

### ISSUE THREAD

**Issue by yogieputra8** [yeoman/generator-angular#1334]
So, here is my app structure using yeoman:
<img width="263" alt="screen shot 2016-06-20 at 4 18 23 pm" src="https://cloud.githubusercontent.com/assets/6022596/16189116/fdb6b4b6-3702-11e6-93cf-511267e2ec71.png">

I have cred.json inside app/json folder.
In my scripts/controller/about.js, I want to access those local json.
My code to access it:
```
$http.get('cred.json').success(function(data){
        console.log(data);
});
```
But I've got the error message:
<img width="1111" alt="screen shot 2016-06-20 at 4 23 23 pm" src="https://cloud.githubusercontent.com/assets/6022596/16189202/561a2732-3703-11e6-963f-8790c25cca0f.png">

How to solve this issue?

**Comment by eddiemonge** [comment]
`'json/cred.json'`
