### ISSUE TITLE
i can't run "grunt serve"  

### ISSUE THREAD

**Issue by medabdellahi** [yeoman/generator-angular#1339]
i have used yo angular to generate my app but when try to run grunt serve i get this message 
C:\other>grunt serve
Running "serve" task

jit-grunt: Plugin for the "clean" task not found.
If you have installed the plugin already, please setting the static mapping.
See https://github.com/shootaroo/jit-grunt#static-mappings

Warning: Task "clean:server" failed. Use --force to continue.

Aborted due to warnings.

could you help me please.

**Comment by eddiemonge** [comment]
sounds like npm install didnt run correctly. try running that again

**Comment by ZihadD** [comment]
I'm having the same issue... any ideas ?

**Comment by medabdellahi** [comment]
try with npm install it was my solution
