### ISSUE TITLE
gulp karma warning

### ISSUE THREAD

**Issue by kdsingharneja** [yeoman/generator-angular#1349]
I am getting this error on npm install

`npm WARN gulp-karma@0.0.4 requires a peer of karma@>=0.10 <=0.13 but none was installed.`

any workaround?

**Comment by eddiemonge** [comment]
Did you try npm installing karma?

**Comment by udev** [comment]
Having the same problem. I tried installing karma directly per the readme and also [sudo npm update](https://github.com/yeoman/generator-angular/issues/1328#issuecomment-264244043).

Still getting the same error as the original comment.

**Comment by udev** [comment]
npm install -g karma

I later found that there's a new generator that I should have been using. Was using the really old angular generator as that was what I remembered from a year ago. I think the generator being out of date was to blame.
