### ISSUE TITLE
 installing  cordova with terminal  make a mistake

### ISSUE THREAD

**Issue by qicaizhuying** [yeoman/generator-angular#1351]
localhost:~ guigujinshan$ sudo npm install -g cordova
npm ERR! Darwin 13.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "cordova"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3

npm ERR! Hostname/IP doesn't match certificate's altnames: "Host: registry.npm.tao.org. is not in the cert's altnames: DNS:*.hspheredns.com, DNS:hspheredns.com"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/guigujinshan/npm-debug.log

**Comment by eddiemonge** [comment]
This isn't the cordova repo
