### ISSUE TITLE
Controler problem.

### ISSUE THREAD

**Issue by SLSJL** [yeoman/generator-angular#1353]
I just started learning angular.  I installed angular project. Then I follow the steps on this [website ](http://blog.jobbole.com/65399/)which demonstrated how to start. But with this sample project,  it cant place views as easily as angular-ui-router can do. After I use angular-ui-router to arrange my UI, this problme came out. There are still tree controler in my project, even though I try to create a new one, like this. for example in Mainctrl:

`<div ng-controler='testcontroler'></div>`

js code goes as follows:

`angular.module('angularApp')
  .controller('testCtrl', function () {
    this.awesomeThings = [
      'HTML5 Boilerplate',
      'AngularJS',
      'Karma'
    ];
  });`

it does work. this pic demonstrate what I really want to do. Could you tell to work with this sample project correctly? Thank you.
![-1](https://cloud.githubusercontent.com/assets/16145313/17760272/30bbc8fe-6531-11e6-92fc-07527cf75a91.jpg)

I try it again. I arrange my ui correctly by using angular-ui-router. but still cant create controller.
![qq 20160818161858](https://cloud.githubusercontent.com/assets/16145313/17766821/8785a3fc-655f-11e6-81b7-b28029ad63db.jpg)

**Comment by eddiemonge** [comment]
you should have 
```
{
  templateURL: '...',
  controller: 'YourControllerName'
}
```
 and not be using ng-controller.
