### ISSUE TITLE
Grunt watch do not check subfolder  in views folder

### ISSUE THREAD

**Issue by vaske** [yeoman/generator-angular#1357]
I'm running into issue when I put my html files under subfolders in views folder. Neither change of any subfolder html file has been detected; it detect only changes on files in root folder in my case it's views folder.

Any idea what should be glitch?

settings are same as they are original 

```
  htmlmin: {
      dist: {
        options: {
          collapseWhitespace: true,
          conservativeCollapse: true,
          collapseBooleanAttributes: true,
          removeCommentsFromCDATA: true,
          removeOptionalTags: true
        },
        files: [{
          expand: true,
          cwd: '<%= yeoman.dist %>',
          src: ['*.html', 'views/{,*/}*.html'],
          dest: '<%= yeoman.dist %>'
        }]
      }
    },
```

**Comment by danieljlist** [comment]
Try..

src: ['*.html', 'views/**/*.html'],

**Comment by eddiemonge** [comment]
what ^^ said

**Comment by Cracky5457** [comment]
Can we re-open this issue ? 

The answer above doesn't work

This is my "watch" ( it s the default generated by generator-angular )

    // Watches files for changes and runs tasks based on the changed files
    watch: {
      bower: {
        files: ['bower.json'],
        tasks: ['wiredep']
      },
      js: {
        files: ['<%= yeoman.app %>/scripts/{,*/}*.js'],
        tasks: [], //['newer:jshint:all', 'newer:jscs:all'],
        options: {
          livereload: '<%= connect.options.livereload %>'
        }
      },
      jsTest: {
        files: ['test/spec/{,*/}*.js'],
        tasks: ['newer:jshint:test', 'newer:jscs:test', 'karma']
      },
      compass: {
        files: ['<%= yeoman.app %>/styles/{,*/}*.{scss,sass}'],
        tasks: ['compass:server', 'postcss:server']
      },
      gruntfile: {
        files: ['Gruntfile.js']
      },
      livereload: {
        options: {
          livereload: '<%= connect.options.livereload %>'
        },
        files: [
          '<%= yeoman.app %>/{,*/}*.html',
          '.tmp/styles/{,*/}*.css',
          '<%= yeoman.app %>/images/{,*/}*.{png,jpg,jpeg,gif,webp,svg}'
        ]
      }
    },

But I have some subfolder into "views" like "views/modals/myModal.html" or "views/partials/myPartial.html"

Watch doesn't see anything about these files.
