### ISSUE TITLE
Grunt build doesn't copy scripts to dist directory

### ISSUE THREAD

**Issue by danieljlist** [yeoman/generator-angular#1359]
Hi all,

If I run yo angular and create a blank project, grunt build doesn't copy any of the bower_components, other scripts (controllers etc) or stylesheets to the dist directory.

Is this happening for anyone else?

**Comment by dominik42** [comment]
Yes, same here .... angular apps built with the yeoman generator seems to be only usable via grunt serve. It's not possible to build deployable artifacts (e.g. a /dist dir) with the default gruntfile. That means for me, yeoman generator can't be used for bootstrapping real world projects ;-(

**Comment by eddiemonge** [comment]
The files get concatened and minified. Does `grunt serve:dist` not have a working site?
