### ISSUE TITLE
generator-angular issue

### ISSUE THREAD

**Issue by kanajam** [yeoman/generator-angular#1361]
yo angular

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.4
npm ERR! npm v3.10.7

npm ERR! Hostname/IP doesn't match certificate's altnames: "Host: registry.nodejs.org. is not in the cert's altnames: DNS:a.sni.fastly.net, DNS:a.sni.global-ssl.fastly.net"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR! /Users/kanajam/angular-project/npm-debug.log

events.js:141
throw er; // Unhandled 'error' event
^

Error: spawn gulp ENOENT
at exports._errnoException (util.js:870:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
at onErrorNT (internal/child_process.js:344:16)
at doNTCallback2 (node.js:441:9)
at process._tickCallback (node.js:355:17)

Please reply ASAP.

Regards,
Vijay Kanajam

**Comment by sindresorhus** [comment]
> npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues
