### ISSUE TITLE
Stop using bower ?

### ISSUE THREAD

**Issue by Cracky5457** [yeoman/generator-angular#1367]
I wonder if generator-angular should still use bower in 2016.

Since version 3, npm support "flat dependency tree" and some voices tell that we shouldn't use bower anymore.

https://www.quora.com/Why-use-Bower-when-there-is-npm/answer/Mattias-Petter-Johansson

**Comment by eddiemonge** [comment]
Find a way to replace wiredep using npm and I'm all for it. I still don't think npm is a good replacement at the time.

**Comment by Cracky5457** [comment]
I never use "browserify" but it looks like an alternative. All is describe here https://gofore.com/stop-using-bower/. The generator-angular is very usefull and I think

**Comment by eddiemonge** [comment]
Exactly. Closing this until something better is proposed.

**Comment by ghost** [comment]
Sorry for bringing this issue up, but I've bower and grunt by only using npm and webpack. You have plugin that allow you to inject your bundles directly into your index.html.

Bower is dying : https://github.com/bower/bower/issues/2298
