### ISSUE TITLE
Fonts not building correctly

### ISSUE THREAD

**Issue by jmwierzbicki** [yeoman/generator-angular#1368]
Hello, i have build application with help of this generator, however when i compile application with grunt build command /fonts directory doesn't contain every font. I have installed Fonts awesome, roboto and bootstrap with bower command, it got saved to index.html correctly. but only bootstrap fonts are there.

**Comment by jmwierzbicki** [comment]
i had to add needed fonts manually to gruntfile copy resources section,, it would be nice if script could actually find all needed fonts and move them automatically.

**Comment by eddiemonge** [comment]
wiredep doesnt currently support adding fonts so it has to be done manually. See this issue for more info https://github.com/taptapship/wiredep/issues/200
