### ISSUE TITLE
New route not working

### ISSUE THREAD

**Issue by Golyo88** [yeoman/generator-angular#1369]
Hi,

I created a new route with `yo angular:route ads` command. Files are generated but after `gulp serve` the new path is not found. I get 

> Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
> 
> angular.js:13920 Error: [$compile:tpload] Failed to load template: views/ads.html (HTTP status: -1 )

If I go to localhost:9000/views/ads.html it is served correctly.

If I rename the new page to about.html it is working... (about.html is there after creating a new project)

What am I doing wrong?

thanks

**Comment by erichstark** [comment]
@Golyo88 Maybe you have to change name in routing app.js file.

**Comment by Golyo88** [comment]
Did that, not helped

**Comment by eddiemonge** [comment]
this sounds like you have an ad blocker running that is blocking that file. It is evidenced by:

> Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

Turn off the ad blocker for local sites and it should work. Further evidence is if you rename the file to not be ads it seems to work.

**Comment by Golyo88** [comment]
It was ad blocker! Thanks and sorry!
