### ISSUE TITLE
css files in styles folder are not getting included in the index.html

### ISSUE THREAD

**Issue by Sef1995** [yeoman/generator-angular#1377]
Hi,

When I add css files to the styles folder of my generated workspace and execute the grunt serve command the styles are not getting included. The only style that gets included is the main.css . How can I fix this? The settings and Gruntfile are just like how they came, did not change anything.

Thanks in advance.

**Comment by Sef1995** [comment]
@Khaleel What do you mean?

**Comment by Khaleel** [comment]
Are you place these between the bower elements too? Can I see the code structure and config files?

**Comment by Sef1995** [comment]
Code structure; https://www.dropbox.com/s/lz146kwdj7om9px/Screenshot%202016-12-07%2013.53.46.png?dl=0
Index: https://www.dropbox.com/s/jdrw5ez2nsn9vlz/Screenshot%202016-12-07%2013.54.18.png?dl=0
https://www.dropbox.com/s/sy0nes9pe78ger2/Screenshot%202016-12-07%2013.54.34.png?dl=0

**Comment by Sef1995** [comment]
I placed the login.css in my index.html manually. So my question is; why doesn't it get auto imported after running grunt serve?

**Comment by AndyTek** [comment]
@Sef1995 
You should have installed ruby and compass, try this:
`brew install ruby`
`sudo gem update --system`
`sudo gem install compass`
and then 
`grunt serve`

**Comment by Sef1995** [comment]
@AndyTek I tried it but doesn't fix the issue. The css still doesn't get auto imported by grunt into the index.html

**Comment by eddiemonge** [comment]
You need to change it to look in the app folder and not just the .tmp folder.
`<!-- build:css({.tmp,app}) styles/main.css -->`
