### ISSUE TITLE
grunt serve resolves in extra exclamation mark in link

### ISSUE THREAD

**Issue by eddieedease** [yeoman/generator-angular#1378]
With just the clean (grunt, bootstrap, sass) install `grunt serve` now resolves to: localhost:9000/#!

The **exclamation mark** is new for me here, never happenened before. However now it happends with every new generator-angular app I scaffold (Tries 2 machines). Note that I don't get this with already existing projects.

Because of this, the viewlinks resolve to localhost:9000/#!/#%2Fabout or something. Which is obviously not good.

**Comment by eddieedease** [comment]
#1379

**Comment by Nahiduzzaman** [comment]
Looks like the problem is with the latest angular version 1.6.0 , I had to downgrade to 1.5.8 to get things worked as before.

**Comment by dani-media** [comment]
es this is a bug. 1.5.8 works!

**Comment by reshadf** [comment]
How can I downgrade back to 1.5.8? it won't let me if I put it in bower. It only lets me keep 1.6.0 or go to 1.3.20 This is what I get from doing a bower update on 1.5.8.

>bower angular                              resolution Unsuitable resolution declared for angular: ~1.5.8
>Unable to find a suitable version for angular, please choose one by typing one of the numbers below:
>  1) angular#1.0 - 1.3 which resolved to 1.3.20 and is required by angular-flash#0.1.14
    2) angular#1.6.0 which resolved to 1.6.0 and is required by angular-animate#1.6.0, angular-aria#1.6.0, angular-cookies#1.6.0, angular-messages#1.6.0, angular-mocks#1.6.0, angular-resource#1.6.0, angular-route#1.6.0, angular-sanitize#1.6.0, angular-touch#1.6.0
    3) angular#^1.4.0 which resolved to 1.6.0 and is required by achilles
    4) angular#>=1.3.0 which resolved to 1.6.0 and is required by angular-bootstrap-calendar#0.27.1
    5) angular#>=1.0.8 which resolved to 1.6.0 and is required by ngstorage#0.3.11
    6) angular#^1.2.9 which resolved to 1.6.0 and is required by angular-loading-bar#0.9.0
    7) angular#>=1.4.8 which resolved to 1.6.0 and is required by angular-flash-alert#2.4.0
    8) angular#>= 1.0.8 which resolved to 1.6.0 and is required by angular-base64#2.0.5
    9) angular#>=1.4.0 which resolved to 1.6.0 and is required by angular-bootstrap#2.3.1

**Comment by Nahiduzzaman** [comment]
In bower json just use for angular version just use 1.5.8 only , exclude ^ or ~
