### ISSUE TITLE
route not working

### ISSUE THREAD

**Issue by summermick** [yeoman/generator-angular#1379]
my project wont open any link other than the landing page.
everything works out of box except the route. for example, when I click on about link, the url changed to "http://localhost:9000/#!/#%2Fabout", but, if I manually type "http://localhost:9000/#!/about", it works.

my environment:
angularjs 1.6.0
ubuntu 16.04
node v6.9.1
npm 3.10.8

**Comment by summermick** [comment]
ok, it's the html.
`
                    <li class="active"><a href="#/">Home</a></li>
                    <li class="active"><a href="#!/">Home</a></li>
                    <li class="active"><a href="#/">Home</a></li>
                    <li class="active"><a href="#!/">Home</a></li>`

**Comment by Nahiduzzaman** [comment]
I had to downgrade angular version to 1.5.8 to get things work as before. When a new project is generated it fetch latest Angular JS 1.6.0 version
