### ISSUE TITLE
route does not work 

### ISSUE THREAD

**Issue by AkbarAlam** [yeoman/generator-angular#1393]
I am having an issue with yo angular. It's generating the app, grunt serve is running locally. But when i click the **about** button it does not go to about page

Here is some code (these are generated by angular generator).

`div class="collapse navbar-collapse" id="js-navbar-collapse">

        <ul class="nav navbar-nav">
          <li class="active"><a href="#/">Home</a></li>
          <li><a ng-href="#/about">About</a></li>
          <li><a ng-href="#/">Contact</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>`

app.js file

`
'use strict';

angular
  .module('coolAppApp', [
    'ngAnimate',
    'ngCookies',
    'ngResource',
'ngRoute',
'ngSanitize',
'ngTouch'
])
  .config(function ($routeProvider) {
$routeProvider
  .when('/', {
    templateUrl: 'views/main.html',
    controller: 'MainCtrl',
    controllerAs: 'main'
  })
  .when('/about', {
    templateUrl: 'views/about.html',
    controller: 'AboutCtrl',
    controllerAs: 'about'
  })
  .otherwise({
    redirectTo: '/'
  });
  });
`

**Comment by AkbarAlam** [comment]
it works with putting ! before /

which means  `<li><a ng-href="#!/about">About</a></li>`

**Comment by amitntrivedi** [comment]
Yes This works for me as well.

**Comment by forsythedev** [comment]
thank you

**Comment by xtremebiker** [comment]
Same for me. Solved with your workaround, but why did you close it? Shouldn't it get fixed, better?
