### ISSUE TITLE
How does the scaffolding.less file is injected?

### ISSUE THREAD

**Issue by Reedyseth** [yeoman/generator-angular#1394]
As the tile says, I would like to know How does the scaffolding.less file is injected?

The reason for this is that I am working in a project where I want to change the background with an images,  but I noticed that the generator inserts a white background located in the `scaffolding.less` file under the body styling.

I have tried to comment the code under the `bower_component/bootstrap/less` path, but the change does not take effect, any advice on this will help a lot.

Regards.!!

**Comment by eddiemonge** [comment]
It doesn't use less. It uses the built bootstrap files
