### ISSUE TITLE
Unminified CSS

### ISSUE THREAD

**Issue by JoshuaNovak919** [yeoman/generator-angular#1395]
How can I have the build output unminified css instead of minified? I've been trying to figure it out, but the documentation for the plugins is all over the place.

**Comment by eddiemonge** [comment]
Why would you want to do that?

Look at this line https://github.com/yeoman/generator-angular/blob/master/templates/common/root/_Gruntfile.js#L373 or the comparable gulp one if you use that

**Comment by JoshuaNovak919** [comment]
@eddiemonge Thanks! Some of the clients I work for want to be able to edit the code and modify it on their end and only know basic html and css.

**Comment by eddiemonge** [comment]
They should be editing the source, not the built files.
