### ISSUE TITLE
Problem using NPM

### ISSUE THREAD

**Issue by abtx** [yeoman/generator-angular#1398]
I've added a module npm by going `npm install --save angular-bootstrap-datetimepicker` for local npm and installed successfully. The module is there, but the import with `<script type="text/javascript" src="node_modules/moment/moment.js"></script>` (moment.js is a dependency of the installd module) throws 404!
I should be able to include the script like shown above, right? Any clue as to why does it throw a 404? Am I missing some grunt configuration, perhaps?

**Comment by denis-andrikevich** [comment]
I had same problem, didnt find any answer, so i include it via cdn.

**Comment by eddiemonge** [comment]
Right now this supports automatic inclusion using bower only. Install with bower and itll do it
