### ISSUE TITLE
Angular yo - ControllerAs don't work

### ISSUE THREAD

**Issue by Nonsonostatoio** [yeoman/generator-angular#1402]
just set up Yeoman with angular, already launch yo-doctor, with no issue.
I have posted a question on stackoverflow, but nothing:

http://stackoverflow.com/questions/43608503/how-to-access-controller-vars-within-controlleras/43608644?noredirect=1#comment74267340_43608644

Seem that i can't access to propriety in the controller, have anybody get same problem?

**Comment by eddiemonge** [comment]
This is not a yeoman or generator question. Its was answered in that thread
