### ISSUE TITLE
npm install -g generator-angular bug

### ISSUE THREAD

**Issue by 392241868** [yeoman/generator-angular#1405]
├── generator-angular@0.16.0 
└── UNMET PEER DEPENDENCY generator-karma@>=0.9.0

npm WARN generator-angular@0.16.0 requires a peer of generator-karma@>=0.9.0 but none was installed.

**Comment by 392241868** [comment]
I have installed generator-karma@2.0.0,but bug still exist

**Comment by eddiemonge** [comment]
do `npm i -g generator-angular generator-karma`

**Comment by uneedwatadmin** [comment]
Hi,

I'm new to this but hoping to get some help too. 

So. to keep the thread going, if it helps, I got the same issue. Here's my output for the command requested for the error:
`npm WARN generator-angular@0.16.0 requires a peer of generator-karma@>=0.9.0 but none was installed.`

It's long. I'll attach a txt file instead.
[npm WARN generator-angular@0.16.0 requires a peer of generator-karma.txt](https://github.com/yeoman/generator-angular/files/1109962/npm.WARN.generator-angular.0.16.0.requires.a.peer.of.generator-karma.txt)

Thank you.
