### ISSUE TITLE
yo angular fails when creating package.json

### ISSUE THREAD

**Issue by arezd** [yeoman/generator-angular#1410]
After having done the command line "yo angular" and following the difference steps, I got this error :

? Overwrite package.json? (ynaxdH) ⸨░░░░░░░░░░░░░░░░░░⸩ ⠧ normalizeTree: sill install loadCnpm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! path /Users/arezkidji/.npm/caniuse-db/1.0.30000700
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/Users/arezkidji/.npm/caniuse-db/1.0.30000700'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, mkdir '/Users/arezkidji/.npm/caniuse-db/1.0.30000700'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/Users/arezkidji/.npm/caniuse-db/1.0.30000700',
npm ERR!   parent: 'autoprefixer-core' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/arezkidji/Desktop/Plotting Tool - Kacific/pl_v1/npm-debug.log

I tried to run it as "sudo yo angular" but it did not fix the issue. 

Any ideas of a solution ?
Thank you

**Comment by sindresorhus** [comment]
Try deleting `/Users/arezkidji/.npm` and try again. Seems like that folder got wrong permissions somehow. I would also recommend upgrading to latest Node.js and npm.

For npm support in the future, use https://github.com/npm/npm/issues

**Comment by arezd** [comment]
Great thank you
