### ISSUE TITLE
need to install angular 1.5 instead of 1.4

### ISSUE THREAD

**Issue by amodsy1989** [yeoman/generator-angular#1416]
i am new to angular as well as yeoman, can anybody please help me installing angular 1.5 rather than 1.4 which i am getting with this generator.

**Comment by eddiemonge** [comment]
`angular: ^1.4.0` means that angular 1.5.0, or whatever latest 1.x is, will get installed. Even though it says 1.4, if you check, you should see that the latest 1.x is installed. If its not, its a bug in Bower.
