### ISSUE TITLE
Grunt gets stuck on `htmlmin:dist` task

### ISSUE THREAD

**Issue by Siyfion** [yeoman/generator-angular#147]
Please see: https://gist.github.com/Siyfion/4e8f63d45b00178345ec

I'm not really sure what's going on here, any help to debug the issue would be great, as I'm a bit lost as to how to figure out what is going wrong!

**Comment by sameer-git-java-c1** [comment]
I was facing the same issue, and realized that there was an extra closing tag inside the div tag, in the html causing the problem

**Comment by molerat619** [comment]
How did you find that out? Sth like that is hard to find?

**Comment by sameer-git-java-c1** [comment]
checked all closing tags for different elements

**Comment by molerat619** [comment]
manually?

**Comment by sameer-git-java-c1** [comment]
yes.. i know it wasnt one of the most efficient methods , but it worked for me

**Comment by molerat619** [comment]
puuh..^^ can you tell me what i should look for except closing tags for different elements? i've checked all files with phpstorm and found one error (not warning) only

**Comment by frandevel** [comment]
@molerat619 also something you can do is commenting out or removing temporarily blocks of HTML to check if it works. Not efficient either but "a bit" faster than checking closing tags visually

**Comment by mohsinkerai** [comment]
In my case it was a " (quotation mark)

**Comment by tfvictorino** [comment]
In my case it was a missing = on ngBind directive: <... ng-bind"example">

**Comment by omer123456** [comment]
In my case I had  `<md-progress-circular   class="md-hue-3" ">`   < -----
