### ISSUE TITLE
Typescript support in generator-angular

### ISSUE THREAD

**Issue by anchann** [yeoman/generator-angular#184]
Hello!

I did a bunch of work to set up an angular+typescript stack on top of the yeoman angular scaffold. This involved figuring out a number of issues; some are typescript-specific, and others could be useful in generator-angular for any language.

I reached out to Brian about the possibility of contributing my work back to generator-angular, and he recommended that I open an issue here. So here goes. For now, I'll just post a link to the project; there's an extensive readme documenting stuff that I think is valuable.

https://github.com/anchann/angularjs-typescript-e2e

Thanks!

-a

**Comment by AbraaoAlves** [comment]
+1

**Comment by icaliman** [comment]
+1

**Comment by vboctor** [comment]
:+1:

**Comment by michaelkrog** [comment]
Great work @anchann

**Comment by eddiemonge** [comment]
https://github.com/yeoman/generator-angular/commit/e579df9d5d2133300f9fe0c3686bc9efbbb5260e

**Comment by AbraaoAlves** [comment]
thanks for work @anchann
