### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by wmertens** [yeoman/generator-angular#258]
Would be great if support for proxying could be added. That way, grunt server can pretend to be your website instead of just the frontend.

https://github.com/drewzboto/grunt-connect-proxy adds support to connect for it, and
https://github.com/drewzboto/grunt-connect-proxy/blob/master/examples/sample.yeoman.grunt.js gives an example of how to set it up.

**Comment by slavede** [comment]
I was just browsing around to see if there is something similar. So I wrote my own generator.

It will give you ability to proxy to remote backend server AND you can also mock the responses so they don't go to remote backend server.

Or just use backend server.

Here's the link https://github.com/slavede/generator-angular-proxy.
