### ISSUE TITLE
Directives using templateUrl can't be tested

### ISSUE THREAD

**Issue by wmill** [yeoman/generator-angular#272]
There's no support for creating a template cache and injecting it into unit tests.  There seem to be ways to do this using html2js and some configuration changes, but templateUrl is a basic angular feature and should be supported by default.

**Comment by domoritz** [comment]
:+1:

**Comment by ciccia** [comment]
+1

**Comment by roar** [comment]
+1

**Comment by tabalinas** [comment]
+1

**Comment by paulsheldrake** [comment]
I have a potentially patch for this problem but I need to update the karma.conf.js in the test folder.   Anyone know where that file is generated from as I can't seem to find it in the repo anywhere?

**Comment by marcdexet-cnrs** [comment]
+1 it's such a pain to test without native support

**Comment by edwardrf** [comment]
+1 inline directive template is so useless, 90% time you need a directive with external template, native support is strongly requested!!!

**Comment by davebeckett** [comment]
+1 for native support

**Comment by Elijen** [comment]
You can just use https://github.com/karma-runner/karma-ng-html2js-preprocessor

**Comment by slavomirvojacek** [comment]
+1 for native support

**Comment by bingomanatee** [comment]
+11

**Comment by steve-mcqs** [comment]
+1
