### ISSUE TITLE
htmlMin in Gruntfile for html files doesn't support folders under /views

### ISSUE THREAD

**Issue by iangregsondev** [yeoman/generator-angular#349]
Hi

I have my views under sub directories under /views for better maintenance the gruntfile doesn't copy these files.

After playing around, its a simple change but can we have this updated in generator-angular

The fix is -

under htmlmin, files, src

replace with this

```
      src: ['*.html', 'views/{,*/}*.html'],
```

This supports copying all required sub-directories.

All the best

**Comment by totallytotallyamazing** [comment]
Yes this is the fix: src: ['*.html', 'views/**/*.html'],
*Just be sure to change it in both the 'htmlmin" and "copy" sections of your grunt file.

**Comment by vaske** [comment]
I still have this issue, an idea what to do?

**Comment by mpielvitori** [comment]
You can use `src: ['**/**/*.html'],` in **htmlmin** -> dist -> files 
Then add the source in **copy** task too `'**/**/*.html',` in copy -> dist -> files -> src

**Comment by vaske** [comment]
@mpielvitori nope it didn't help, it's always standing watching... but never really notice and execute compilation on file in subfolder has been changed :(
