### ISSUE TITLE
Add dependency injection

### ISSUE THREAD

**Issue by laurent-le-graverend** [yeoman/generator-angular#364]
Using Yeoman generator always use the same module name, for example "myApp".

  yo angular:contoller myCtrl
  yo angular:directive myDir

  angular.module('myMod').controller('UserCtrl' ....
  angular.module('myMod').directive('myDir' ....

But if I need to add another module, for example ngResource, 

  angular.module('myMod').directive('myDir', ["ngResource"]

It doesn't work, probably because the module is already instanciated without ngResource (from the controller).

I think this should be:
a) documented
b) an option in the generators to add dependencies

**Comment by Kratos-SA** [comment]
did anything else come of this as I have a generic generator that add a lot of files and it would be a pain to have to go and inject them all.
