### ISSUE TITLE
"grunt server" Interferes with page reloads

### ISSUE THREAD

**Issue by wizardwerdna** [yeoman/generator-angular#393]
The `grunt server` command sets up a fine livereload static server.  However, for SPA applications that handle routing, the server does not recognize the SPA route URLs and returns a 404 error message, rather than sending the URL to the server.

This can be annoying while working on an internal page, say `/edit/3`.  If you change anything in the watchlist, then the browser will simply display the 404 message, and you will need to go to the root and work your way back to proceed.

This can be avoided by simply passing urls that do not render static code directly to the single page.  Assuming that app/index.html handles your routing, the following change to the Gruntfile solves the problem:

Gruntfile.js

``` grunt
...
fs = require('fs')
...
    connect: {
      options: {
        port: 9000,
        // Change this to '0.0.0.0' to access the server from outside.
        hostname: 'localhost'
      },
      livereload: {
        options: {
          middleware: function (connect) {
            return [
              lrSnippet,
              mountFolder(connect, '.tmp'),
              mountFolder(connect, yeomanConfig.app),
              // for angular apps, we send 404s back to the application
              function(req, res){
                res.end(fs.readFileSync(__dirname+'/app/index.html', {encoding:'utf8'}));
              }
            ];
          }
        }
      }
...
```

I would be happy to post a pull request, but I haven't been able to figure how the Gruntfile from my `yo angular` command is generated.  The template I found on this github project doesn't appear to be the one used to build `Gruntfile.js`.  Any thoughts?

**Comment by giantray** [comment]
@wizardwerdna 
good.I hava same problem.and I solve it by your example code.thank you
