### ISSUE TITLE
"Controller: MainCtrl should attach a list of awesomeThings to the scope FAILED"

### ISSUE THREAD

**Issue by ryanburnett** [yeoman/generator-angular#403]
I'm on OS X 10.8.5 with the following installed:
- Xcode and command line tools
- Homebrew
- Git `brew install git`
- node/npm (via the nodejs.org installer)
- Yeoman `npm install -g yo`
- Grunt `npm install -g grunt-cli`
- Bower `npm install -g bower`
- angular package `npm install -g generator-angular`

Here are the steps where I'm running into trouble:
1. `yo angular`
2. `grunt`
3. Terminal has a sad: https://gist.github.com/ryanburnett/7093835

How can I prevent this error from occurring?

**Comment by peter-atlanta** [comment]
they mean, ahem: mean, they have installed all dependencies via npm or bower. LOLZ
