### ISSUE TITLE
yo angular --coffee creates Gruntfile.js, not Gruntfile.coffee

### ISSUE THREAD

**Issue by zakdances** [yeoman/generator-angular#424]
I did a search for this issue and couldn't find anything, so I'd just like to inquire about this. Is this intentional? And if so, is there an option to create a Gruntfile.coffee instead of a Gruntfile.js when using the --coffee option?

**Comment by rodfersou** [comment]
@eddiemonge try just to use js2coffee and translate it to Gruntfile.coffee by yourself (it works for me)
