### ISSUE TITLE
Heroku Deploy

### ISSUE THREAD

**Issue by lifeiscontent** [yeoman/generator-angular#434]
is there any way to deploy an angular app to heroku.

I almost got it working... but when I moved everything that was a `devDepenency` in `package.json` to just a `dependency` things broke.

my post install command looked something like `bower install && grunt build`

but the grunt build task doesn't work when using all `devDepencencies` as `dependencies`

**Comment by francesco-carrella** [comment]
I'm at the same point with an app that I've to push on a dokku env. @intellix do you had some step advance on that? Thank you!

**Comment by intellix** [comment]
Actually, moved from this generator to https://github.com/Swiip/generator-gulp-angular long ago, which is extremely active and modern
