### ISSUE TITLE
index.html contains references to bower_components folder that is not installed during generation

### ISSUE THREAD

**Issue by mbielski** [yeoman/generator-angular#444]
When you create a new project with "yo angular projectname" the index.html file includes references to files in the "/app/bower_components/" folder, but that folder isn't created/populated in the generation process. The result is that angular is not defined when you try to build your project via "grunt".

WARN [watcher]: Pattern "C:/Dev/Yeoman/PrismWeb/app/bower_components/angular/angular.js" does not match any file.
WARN [watcher]: Pattern "C:/Dev/Yeoman/PrismWeb/app/bower_components/angular-mocks/angular-mocks.js" does not match any file.
WARN [watcher]: Pattern "C:/Dev/Yeoman/PrismWeb/app/bower_components/angular-resource/angular-resource.js" does not match any file.
WARN [watcher]: Pattern "C:/Dev/Yeoman/PrismWeb/app/bower_components/angular-cookies/angular-cookies.js" does not match any file.

Chrome 30.0.1599 (Windows 7) ERROR
        Uncaught ReferenceError: angular is not defined
        at C:/Dev/Yeoman/PrismWeb/app/scripts/app.js:3
Chrome 30.0.1599 (Windows 7) ERROR
        Uncaught ReferenceError: angular is not defined
        at C:/Dev/Yeoman/PrismWeb/app/scripts/controllers/main.js:3

Warning: Task "karma:unit" failed. Use --force to continue.

Aborted due to warnings.

I see issue #310 and wonder if perhaps this is fallout from that? If I've left anything out that you need to resolve this, please let me know and I'll post it as soon as I can.

**Comment by deepakkaithwas** [comment]
Fixed the issue in Windows.

Run following command.
git config --global url."https://".insteadOf git://
