### ISSUE TITLE
uglify:dist: not written because src files were empty

### ISSUE THREAD

**Issue by saamalik** [yeoman/generator-angular#455]
Hi, using the latest generator-angular 0.6.0-rc1. 
1. Create a new project (`yo angular`), say YES to all options.
2. `grunt build`

there is a warning in the middle:

> Running "uglify:dist" (uglify) task
> 
> > Destination (dist/scripts/scripts.js) not written because src files were empty.

It's not affecting the final dist, but either the uglify:dist target should be removed or fixed.

**Comment by yanchuan1990** [comment]
I've had the same problem.how do you solve it？
