### ISSUE TITLE
Angular Hangs

### ISSUE THREAD

**Issue by gojohnnygo** [yeoman/generator-angular#505]
yo v1.0.5
generator-angular v0.6.0

Looks like the angular generator is hanging at this block.  

```
grunt-contrib-imagemin@0.3.0 node_modules/grunt-contrib-imagemin
├── filesize@1.10.0
├── chalk@0.2.1 (has-color@0.1.1, ansi-styles@0.2.0)
├── pngquant-bin@0.1.5 (bin-wrapper@0.1.7)
├── gifsicle@0.1.4 (bin-wrapper@0.1.7)
├── jpegtran-bin@0.2.2 (bin-wrapper@0.1.7)
└── optipng-bin@0.3.1 (bin-wrapper@0.1.7)
```

Here's a gist from the output of 

`yo --version && echo $PATH $NODE_PATH && node -e 'console.log(process.platform, process.versions)' && cat Gruntfile.js`

https://gist.github.com/gojohnnygo/d5010f25f68a70385f67

Is this happening to anyone else?

**Comment by Alex-Werner** [comment]
Having the same problem now. Hitting enter and y made it continue.

**Comment by bengrunfeld** [comment]
Same here. Hitting enter works. Without it, `yo angular` hangs at the following

```
Execution Time (2015-10-22 04:48:40 UTC)
loading tasks    6ms  ▇ 3%
wiredep:app    185ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 93%
wiredep:test     8ms  ▇▇ 4%
Total 199ms
```
