### ISSUE TITLE
Error running yo angular

### ISSUE THREAD

**Issue by viktorlund** [yeoman/generator-angular#529]
[?] Would you like to use Sass (with Compass)? Yes
[?] Would you like to include Twitter Bootstrap? Yes
[?] Would you like to use the Sass version of Twitter Bootstrap? Yes
[?] Which modules would you like to include? angular-resource.js, angular-cookies.js, angular-sanitize.js, angular-route
.js
   create app/styles/main.scss
   create app\index.html
   create bower.json
   create package.json
   create Gruntfile.js
   create app\images\yeoman.png
   invoke   angular:common:C:\Users\vilu\AppData\Roaming\npm\node_modules\generator-angular\app\index.js
   create     .bowerrc
   create     .editorconfig
   create     .gitattributes
   create     .jshintrc
   create     app.buildignore
   create     app.htaccess
   create     app\404.html
   create     app\favicon.ico
   create     app\robots.txt
   create     app\views\main.html
   create     test.jshintrc
   create     test\runner.html
   create     .gitignore
   invoke   angular:main:C:\Users\vilu\AppData\Roaming\npm\node_modules\generator-angular\app\index.js
   create     app\scripts\app.js
   invoke   angular:controller:C:\Users\vilu\AppData\Roaming\npm\node_modules\generator-angular\app\index.js
   create     app\scripts\controllers\main.js
   create     test\spec\controllers\main.js

I'm all done. Running bower install & npm install for you to install the required dependencies. If this fails, try runni
ng the command yourself.

   invoke   karma:app
   create     karma.conf.js
   create     karma-e2e.conf.js

C:\Users\vilu\AppData\Roaming\npm\node_modules\generator-angular\node_modules\wiredep\lib\detect-dependencies.js:55
  if (_.isString(componentConfigFile.main)) {
                                    ^
TypeError: Cannot read property 'main' of undefined
    at findMainFiles (C:\Users\vilu\AppData\Roaming\npm\node_modules\generator-angular\node_modules\wiredep\lib\detect-d
ependencies.js:55:37)
    at C:\Users\vilu\AppData\Roaming\npm\node_modules\generator-angular\node_modules\wiredep\lib\detect-dependencies.js:
101:17
    at forOwn (C:\Users\vilu\AppData\Roaming\npm\node_modules\generator-angular\node_modules\wiredep\node_modules\lodash
\dist\lodash.js:1301:15)
    at Function.forEach (C:\Users\vilu\AppData\Roaming\npm\node_modules\generator-angular\node_modules\wiredep\node_modu
les\lodash\dist\lodash.js:2595:9)
    at detect (C:\Users\vilu\AppData\Roaming\npm\node_modules\generator-angular\node_modules\wiredep\lib\detect-dependen
cies.js:290:5)
    at module.exports (C:\Users\vilu\AppData\Roaming\npm\node_modules\generator-angular\node_modules\wiredep\bin\wiredep
:34:40)
    at Generator._injectDependencies (C:\Users\vilu\AppData\Roaming\npm\node_modules\generator-angular\app\index.js:286:
5)
    at C:\Users\vilu\AppData\Roaming\npm\node_modules\generator-angular\node_modules\yeoman-generator\node_modules\async
\lib\async.js:229:13
    at C:\Users\vilu\AppData\Roaming\npm\node_modules\generator-angular\node_modules\yeoman-generator\node_modules\async
\lib\async.js:110:21
    at C:\Users\vilu\AppData\Roaming\npm\node_modules\generator-angular\node_modules\yeoman-generator\node_modules\async
\lib\async.js:24:16

**Comment by shank318** [comment]
bower update works.
