### ISSUE TITLE
Use GitHub Releases instead of CHANGELOG.md

### ISSUE THREAD

**Issue by sindresorhus** [yeoman/generator-angular#549]
No need in duplicating.

Related https://github.com/ajoslin/conventional-changelog/issues/2

**Comment by stevemao** [comment]
Please try https://github.com/stevemao/conventional-github-releaser

**Comment by sindresorhus** [comment]
@stevemao PR welcome ;)

**Comment by stevemao** [comment]
Give me some time and I'll put together a PR :)

**Comment by arthurvr** [comment]
Thanks @stevemao :)
