### ISSUE TITLE
Add grunt-ngdocs and documentation

### ISSUE THREAD

**Issue by marcin-wosinek** [yeoman/generator-angular#550]
There is great [tool](https://npmjs.org/package/grunt-ngdoc) to generate a documentation. We start using it in our company, and I'm amazed who cool it can be setup and integrated with yeoman workflow.

The documentation produced by it looks just like [angular's one](http://docs.angularjs.org/api/):
![documentation](https://f.cloud.github.com/assets/1024920/1950936/f8cf31b6-8161-11e3-9d56-081c1f09eb0b.png)

It can work nicely with autoreload and stuff. PR on the way

**Comment by LunarDevelopment** [comment]
Hello! 

Can I ask how you use this? 

I've read a tutorial for how to integrate ng-docs from https://www.npmjs.com/package/grunt-ngdoc however because its to an existing project I want to add it, I wouldn't want to break anything..
