### ISSUE TITLE
yo angular hangs on app creation

### ISSUE THREAD

**Issue by rob-balfre** [yeoman/generator-angular#563]
yo angular hangs on app creation at this point on my OSX Mavericks. 

```
grunt-karma@0.6.2 node_modules/grunt-karma
└── optimist@0.6.0 (wordwrap@0.0.2, minimist@0.0.5)
```

If hit enter I get back to prompt.  Running grunt serve seems to work just not sure if yeoman had finished running or not.

**Comment by noahxtra** [comment]
I am still having this issue with the latest yeomon. Seems to happen with all generators for me on OSX (10.10.2). The prompt does show up after enter and allows me to continue normally.

**Comment by eddiemonge** [comment]
latest version of yo is 1.3.3, not 1.1.2
