### ISSUE TITLE
EPEERINVALID with new version of generator-karma

### ISSUE THREAD

**Issue by DaftMonk** [yeoman/generator-angular#596]
Hi, I just released the new version of my fullstack generator which depends on the latest version of generator-karma. The current build of generator-angular 0.7.1 is triggering a conflict in the peer dependencies, as its looking for ~0.6.0 of generator-karma, and not >=0.6.0. 

I see that the package.json on the repo has been updated to use >=0.6.0, but it hasn't been released yet. I don't want to rush you into releasing something if its not ready, just wanted you to be aware there's a conflict with the two generators until its updated.

```
npm ERR! peerinvalid The package generator-karma does not satisfy its siblings'
peerDependencies requirements!
npm ERR! peerinvalid Peer generator-angular@0.7.1 wants generator-karma@~0.6.0
npm ERR! peerinvalid Peer generator-angular-fullstack@1.3.0 wants generator-karm
a@>=0.6.0

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "update" "-g" "generator-angular"
npm ERR! cwd C:\Users\Tyler\JSworkspace
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! code EPEERINVALID
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\Tyler\JSworkspace\npm-debug.log
npm ERR! not ok code 0
```

**Comment by rainabba** [comment]
I had to use "npm rm" instead of uninstall, but even then, can't get past the EPEERINVALID error:

```
C:\....... [master]> npm rm -g generator-karma ; npm install -g generator-angular
unbuild generator-karma@0.9.0
npm WARN peerDependencies The peer dependency generator-karma@>=0.9.0 included from generator-angular will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency yo@>=1.0.0 included from generator-angular will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency yo@>=1.0.0 included from generator-karma will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "generator-angular"
npm ERR! node v0.10.36
npm ERR! npm  v2.6.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package generator-karma does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer generator-angular@0.11.1 wants generator-karma@>=0.9.0
npm ERR! peerinvalid Peer generator-angular-ui-router@0.5.3 wants generator-karma@~0.5.0
npm ERR! peerinvalid Peer generator-angular-xl@0.6.1 wants generator-karma@>=0.6.0

npm ERR! Please include the following file with any support request:
npm ERR!     C:\......\npm-debug.log
```

**Comment by daveball** [comment]
is there an actual soution to this other than removing karma

**Comment by javarch** [comment]
Ich werde ab  16.09.2015 nicht im B�ro sein. Ich kehre zur�ck am
12.10.2015.
Ich werde Ihre Nachricht nach meiner R�ckkehr beantworten.

Die R�ckmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [generator-angular] EPEERINVALID with new version of generator-karma
(#596)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2015 Agent 'Abwesenheit'

Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
DVR: 0572934, UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angef�hrten Absender via E-Mail
dient ausschlie�lich Informationszwecken. Rechtsgesch�ftliche Erkl�rungen
d�rfen �ber dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.

**Comment by eddiemonge** [comment]
stop using sudo with npm

**Comment by wahengchang** [comment]
any solution ???
