### ISSUE TITLE
Add an option to use Gulp instead of grunt

### ISSUE THREAD

**Issue by eranimo** [yeoman/generator-angular#623]
I think there should be an option to use the Gulp task runner instead of Grunt. They do mostly the same things, except Gulp uses streams. I do not know about the difference in the availability of tasks, that may be a point of trouble. I have begun to replaced it in my own project, but I'm wondering what other people think about adding it to this generator as another option. There's already [generator-gulp-webapp](https://github.com/yeoman/generator-gulp-webapp), maybe that could be a start.

**Comment by cereallarceny** [comment]
+1

**Comment by antonioreuter** [comment]
+1

**Comment by marinbgd** [comment]
+1

**Comment by Blueblau** [comment]
+1

**Comment by HTMLangdon** [comment]
+1 gulp! :D

**Comment by arthurvr** [comment]
I'm going to lock this as the +1's are too noisy and we added Gulp support in https://github.com/yeoman/generator-angular/commit/9ad4d74f40b91b891712ddf44eb35c278d1ecb61. For further thoughts should go to https://github.com/yeoman/generator-angular/pull/837.
