### ISSUE TITLE
set collapseBooleanAttributes to false in Gruntfile

### ISSUE THREAD

**Issue by jack-kerouac** [yeoman/generator-angular#651]
Hi,

I wrote a directive with isolated scope and attribute 'selected':

```
    .directive('selector', function () {
        return {
            ...
            scope: {
                selected: '='
            },
            ...
        };
    });
```

I use it like this:

```
<span selector selected="something"></span>
```

Due to htmlmin's option `collapseBooleanAttributes` this gets minified into `<span selector selected></span>` which breaks the functionality. I just spent two hours finding the reason for this. I thus would recommend to set `collapseBooleanAttributes` to `false` in the Gruntfile.

Maybe I should not have used the `selected` attribute though.

**Comment by aplocher** [comment]
Sorry to revive an old issue.  I just ran into this issue with my Gruntfile (from Yeoman) as well, with angular-bootstrap-checkbox from Bower.  They have an attribute called "indeterminate" that must be set to true to enable tri-state checkboxes (true, false, null).  I did the dist build and I have also just spent about 2 - 3 hours trying to figure out why it was broken.  I finally noticed in FF dev tools the DOM thinks it's indeterminate='' in my dist build.
