### ISSUE TITLE
concurrent:server hangs on grunt serve

### ISSUE THREAD

**Issue by eschaefer** [yeoman/generator-angular#660]
I am running a fresh installation of generator-angular on OS X Mavericks.

`grunt serve --verbose` hangs at:

```
Running "concurrent:server" (concurrent) task
Verifying property concurrent.server exists in config...OK
Files: [no src] -> server
Options: limit=2 
```

If I comment-out the concurrent:server line in the generated Gruntfile.js...

```
grunt.task.run([
      'clean:server',
      'bowerInstall',
      // 'concurrent:server',
      'autoprefixer',
      'connect:livereload',
      'watch'
    ]); 
```

Then the server gets a little further, but sticks here without serving any CSS assets:

```
Running "compass:server" (compass) task
Verifying property compass.server exists in config...OK
File: [no files]
Options: sassDir="app/styles", cssDir=".tmp/styles", generatedImagesDir=".tmp/images/generated", imagesDir="app/images", javascriptsDir="app/scripts", fontsDir="app/styles/fonts", importPath="app/bower_components", httpImagesPath="/images", httpGeneratedImagesPath="/images/generated", httpFontsPath="/styles/fonts", relativeAssets=false, assetCacheBuster=false, raw="Sass::Script::Number.precision = 10\n", debugInfo
```

**Comment by shwing** [comment]
Had the same problem, uninstall compass-rails did the trick.

**Comment by przbadu** [comment]
yep, worked for me as well

**Comment by bvaughn** [comment]
Uninstalling compass-rails also worked for me.

**Comment by SeyZ** [comment]
:+1: compass-rails was the issue :+1:

**Comment by 7Silvan** [comment]
Also there could be hided scss compilation error under this (if you have made changes without 'watch' task being running)

So check it with replacing 'concurrent:server' with 'compass:server', to look into.

**Comment by luigi7up** [comment]
Guys, I didn't uninstall __compass-rails__ but just updated it with `gem update compass-rails`.  cheers

**Comment by wallclockbuilder** [comment]
`gem uninstall compass-rails`
