### ISSUE TITLE
Fatal error: Port 35729 is already in use by another process

### ISSUE THREAD

**Issue by ryanburnett** [yeoman/generator-angular#707]
I just did a fresh install of generator-angular:

```
npm install -g generator-angular
mkdir my-new-project && cd $_
yo angular
```
- _Hit Yes for Sass, Bootstrap and Sass Bootstrap_
- _Included angular-resource.js and angular-route.js_

```
grunt
grunt serve
```

...then got this error:

```
Running "watch" task
Waiting...Fatal error: Port 35729 is already in use by another process.
```

I rebooted and still receive the error. Any idea how to prevent this?

P.S. I'm on OS 10.9.3 running LiveReload 2.3.62 with:

```
node -v
v0.10.26
npm -v
1.4.13
bower -v
1.3.4
```

**Comment by henvy** [comment]
看不懂！

**Comment by bendangelo** [comment]
你需要幫助嗎？

**Comment by almudenaguerras** [comment]
Great!
Thanks a lot

**Comment by javarch** [comment]
Ich werde ab  16.09.2015 nicht im B�ro sein. Ich kehre zur�ck am
12.10.2015.
Ich werde Ihre Nachricht nach meiner R�ckkehr beantworten.

Die R�ckmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [generator-angular] Fatal error: Port 35729 is already in use by
another process (#707)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2015 Agent 'Abwesenheit'


Der Austausch von Nachrichten mit o.a. Absender via e-mail dient
ausschlie�lich Informationszwecken. Rechtsgesch�ftliche Erkl�rungen d�rfen
�ber dieses Medium nicht ausgetauscht werden.

Correspondence with a.m. sender via e-mail is only for information
purposes. This medium is not to be used for the exchange of legally-binding
communications.

**Comment by ashuSvirus** [comment]
Thanks a lot

**Comment by e11world** [comment]
Thank you @QuantumField that fix worked for me. FINALLY!

**Comment by mosermanuel** [comment]
Ich werde ab  28.06.2017 nicht im Büro sein. Ich kehre zurück am
04.07.2017.
Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [yeoman/generator-angular] Fatal error: Port 35729 is already in use by
another process (#707)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2017 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
DVR: 0572934, UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------
