### ISSUE TITLE
Problems running grunt test with karma

### ISSUE THREAD

**Issue by soen** [yeoman/generator-angular#710]
Hi,

I'm currently having some problems running the out-of-the-box karma unit tests generated. After correcting the path of karma.conf.js in the grunt file, I am running into this problem:

---

Running "karma:unit" (karma) task
INFO [karma]: Karma v0.12.16 server started at http://localhost:8080/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.7 (Mac OS X)]: Connected on socket GNdLOWdbsgYsiDZWerC- with id 91286963
PhantomJS 1.9.7 (Mac OS X): Executed 0 of 0 ERROR (0.001 secs / 0 secs)
Warning: Task "karma:unit" failed. Use --force to continue.

Aborted due to warnings.

---

I am not entirely sure if this is related to the general problems addressed in other issues with regards to the karma generator.

Any kind of help is appreciated.

Thanks!

**Comment by jheyn** [comment]
try modifing test/karma.conf.js : replace bower_components by node_modules.
