### ISSUE TITLE
Fatal error: Unable to find local grunt.

### ISSUE THREAD

**Issue by stevemao** [yeoman/generator-angular#761]
I updated my generator-angular to 0.9.1 and I scaffold all my files. When I tried to use grunt it says: grunt-cli: The grunt command line interface. (v0.1.13)

Fatal error: Unable to find local grunt.

If you're seeing this message, either a Gruntfile wasn't found or grunt
hasn't been installed locally to your project. For more information about
installing and configuring grunt, please see the Getting Started guide:

My yo version is 1.2.0, grunt version 0.4.5.

My file structure:
![screen shot 2014-06-26 at 10 25 22 am](https://cloud.githubusercontent.com/assets/6316590/3393573/606bc7ee-fcc8-11e3-9fd5-39fea674c71d.png)
I do have gruntfile in my directory.

My choices for generator-angular
![screen shot 2014-06-26 at 10 21 20 am](https://cloud.githubusercontent.com/assets/6316590/3393549/d00764ec-fcc7-11e3-8956-a6eeda572915.png)

I noticed when I scaffolding, I got the following error:

> pngquant-bin@0.3.1 postinstall /Users/stevemao/Documents/test-grunt-angular/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin
> node index.js

✗ pre-build test failed, compiling from source...
libpng-dev is installed

{ [Error: Command failed: In file included from pngquant.c:59:
./rwpng.h:35:10: fatal error: 'png.h' file not found
# include "png.h"    /\* libpng header; includes zlib.h */

```
     ^
```

1 error generated.
make: **\* [pngquant.o] Error 1
] killed: false, code: 2, signal: null }

**Comment by aloaiza** [comment]
Thanks Mark!

**Comment by markthethomas** [comment]
:thumbsup:

**Comment by madhumc85** [comment]
Npm install i

**Comment by timposu** [comment]
try it... 
```
npm install grunt --save-dev
```
and you need run
```
npm install
```
