### ISSUE TITLE
grunt build not populating vendor.js & vendor.css

### ISSUE THREAD

**Issue by grooveymo** [yeoman/generator-angular#769]
Similar problem to https://github.com/DaftMonk/generator-angular-fullstack/issues/164.

The files vendor.js and vendor.css are generated empty when building with grunt. 

The cause appears to be the concat plugin which is expecting /bower_components to be a child folder of /app, whereas it is a sibling folder.

Some build output:

concat:
  { generated: 
   { files: 
      [ { dest: '.tmp/concat/scripts/vendor.js',
          src: 
           [ 'app/bower_components/jquery/dist/jquery.js',
             'app/bower_components/angular/angular.js',
             'app/bower_components/json3/lib/json3.js',
             'app/bower_components/bootstrap/dist/js/bootstrap.js',
             'app/bower_components/angular-resource/angular-resource.js',
             'app/bower_components/angular-cookies/angular-cookies.js',
             'app/bower_components/angular-sanitize/angular-sanitize.js',
             'app/bower_components/angular-animate/angular-animate.js',
             'app/bower_components/angular-touch/angular-touch.js',
             'app/bower_components/angular-route/angular-route.js' ] },

Workround is to modify the build tags e.g.

```
change 
       <!-- build:js scripts/vendor.js -->
to
       <!-- build:js(app/..) scripts/vendor.js -->
```

and similarly,

```
change 
        <!-- build:css styles/vendor.css -->
to
      <!-- build:css(app/..) styles/vendor.css -->
```

**Comment by vladyn** [comment]
Mine too - Thanks!

**Comment by david-meza** [comment]
This worked for me for both bower vendor files and local vendor files.

    
    
    <link rel="stylesheet" href="bower_components/angular-material/angular-material.css" />
    
    <link rel="stylesheet" href="styles/font-awesome.css">
    

Needless to say `<!-- build:css(.) styles/vendor.css -->` nor `<!-- build:css(app) styles/vendor.css -->` by themselves worked.

**Comment by hgillh** [comment]
Hi Guys,
I am facing same issue. My site is working fine when I run with Grunt Serve. But when I build it and load index.html, It does not load any css. 
I have tried both styles i.e  and but none works.

Can anyone help please ?

Thanks in advance.
