### ISSUE TITLE
Compass Server super slow

### ISSUE THREAD

**Issue by lulato** [yeoman/generator-angular#786]
Is anyone experiencing this problem with compass?

![screen shot 2014-07-18 at 4 29 56 pm](https://cloud.githubusercontent.com/assets/1007664/3631840/b6f04c48-0ebb-11e4-83f6-99b212105dad.png)

**Comment by abods** [comment]
Compass is slow but not that slow! **This is crazy slow!**
I have it running on other projects, massively larger than generator-angular boilerplate but with no issues!  
I wanted to solve it using grunt-sass but its not running on node 0.12!

**My ugly workaround was to**

- setup compass on the parent directory and make it work on a separate $$$.scss file which will generate $$$.css in the final build folder "client/.tem/styles/compass.css".
- referencing the new $$$.css in "client/app/index.html" on my local 'dev' only.
- on final build i merge the compass version of $$$.scss with the original "client/app/styles/main.scss"
Problem solved for now, the **slow crazy compass** is working on "grunt serve" and the **lovely fast compass** working from the parent directly like a 

# BOSS
