### ISSUE TITLE
How to delete a directive,controller with a simple command?

### ISSUE THREAD

**Issue by RyanAntenor** [yeoman/generator-angular#798]
Just wondering in the documentation, there's no delete option .
Is there any plans to includes this as extra feature ?

Something like : 'yo angular:directive rm myDirective" ?

**Comment by paulrandolph** [comment]
I delete a directive by deleting the directive's directory, then delete the new item in .yo-rc.json from the directives[] array:

    "directives": [
      {
        "name": "directivename"
      },

//delete this item
      {
        "name": "newdirective"
      }
    ]

it seems to work.
