### ISSUE TITLE
Preffered way of changing variables in Bootstrap

### ISSUE THREAD

**Issue by stinaq** [yeoman/generator-angular#812]
What is your preferred way of changing the SASS Bootstrap variables in a project? I'm looking to modify or modify some variables, mostly colors, which can be found in the _variables.scss file in the Bootratrap repo. Had I been compiling the .scss file myself I could just override it with my own variables on importing the bootstrap file into my own SASS file, but with Grunt doing it I'm not sure what the best way is. 

I suspect it has something to do with how the Gruntfile compiles the .scss files, but I'm having trouble navigating it.

**Comment by Kamps-Duac** [comment]
For Googlers, I have found that adding an `@import "_branding.scss";` before my `@import "bootstrap-sass-official/assets/stylesheets/_bootstrap.scss";` in `main.scss` and custom variables inside `styles/_branding.scss` to work well.
