### ISSUE TITLE
Vendor.js is empty when running a build

### ISSUE THREAD

**Issue by filipjohansson** [yeoman/generator-angular#813]
When I try to run my built app I get this error in Chrome.

`Uncaught ReferenceError: angular is not defined`

It seems that the vendor.js is empty when I do a build.
I looked into the log for the build and found this, could the `[no src]` be the issue?

```
Running "concat:generated" (concat) task
Verifying property concat.generated exists in config...OK
Files: [no src] -> .tmp/concat/scripts/vendor.js
...
Writing .tmp/concat/scripts/vendor.js...OK
File .tmp/concat/scripts/vendor.js created.
```

**Comment by kgcreative** [comment]
`rGrove commented on Aug 13, 2014'

'useminPrepare: {                                                                                                                                                      
       html: '<%= yeoman.app %>/index.html',                                    
       options: {                                                               
         dest: '<%= yeoman.dist %>',                                            
         root: './',                                                            
         flow: {                                                                
           html: {                                                              
             steps: {                                                           
               js:                                                              
                 [ 'concat'                                                     
                 , 'uglifyjs'                                                   
                 ],                                                             
               css:                                                             
                 [ 'cssmin'                                                     
                 ]                                                              
             },                                                                 
             post: {}                                                           
           }                                                                    
         }                                                                      
       }                                                                        
     },'

'If you set "./" as you root it will fix the issue'

I'm running generator-angular@0.12.1 /usr/local/lib/node_modules/generator-angular and was having the described problem as well. This is the only thing that fixed my issue.

**Comment by vladyn** [comment]
tha wasn't fix it unfortunately. I'm running the project with bower_components inside the app folder and in dist my vendor?xxx and styles are empty
