### ISSUE TITLE
Provide Sass option without compass

### ISSUE THREAD

**Issue by trevordmiller** [yeoman/generator-angular#819]
It would be wonderful to have the Sass option without compass right out of the box.

**Comment by pensierinmusica** [comment]
+1

**Comment by chemicalbr** [comment]
compass:server      3.8s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 88%
autoprefixer:dist  494ms  ▇▇▇ 11%

**Comment by dbertella** [comment]
+1 
sass + autoprefixer are doing everything you need already, I think nobody is still using compass, do you?

**Comment by pensierinmusica** [comment]
Agree

**Comment by AlJohri** [comment]
:+1:

**Comment by jzjzjzj** [comment]
:+1:

**Comment by obendt** [comment]
+1

**Comment by karbassi** [comment]
Here's what I followed to remove compass and use [libsass](https://github.com/sass/libsass).

Read: http://ravelantunes.com/blog/angular-generator-libsass/

## install libsass
Run `npm install --save-dev grunt-sass`

## Uninstall grunt-contrib-compass
Run `npm uninstall --save-dev grunt-contrib-compass`

## Update grunt file

Remove the compass configuration

```js
// Compiles Sass to CSS and generates necessary files if requested
compass: {
  options: {
    sassDir: '<%= yeoman.app %>/styles',
    cssDir: '.tmp/styles',
    generatedImagesDir: '.tmp/images/generated',
    imagesDir: '<%= yeoman.app %>/images',
    javascriptsDir: '<%= yeoman.app %>/scripts',
    fontsDir: '<%= yeoman.app %>/styles/fonts',
    importPath: './bower_components',
    httpImagesPath: '/images',
    httpGeneratedImagesPath: '/images/generated',
    httpFontsPath: '/styles/fonts',
    relativeAssets: false,
    assetCacheBuster: false,
    raw: 'Sass::Script::Number.precision = 10\n'
  },
  dist: {
    options: {
      generatedImagesDir: '<%= yeoman.dist %>/images/generated'
    }
  },
  server: {
    options: {
      debugInfo: true
    }
  }
},
```

and add the libsass configuration instead:

```js
    // Compiles Sass to CSS and generates necessary files if requested
    sass: {
        options: {
            includePaths: [
                'bower_components'
            ]
        },
        dist: {
            files: [{
                expand: true,
                cwd: '<%= yeoman.app %>/styles',
                src: ['*.scss'],
                dest: '.tmp/styles',
                ext: '.css'
            }]
        },
        server: {
            files: [{
                expand: true,
                cwd: '<%= yeoman.app %>/styles',
                src: ['*.scss'],
                dest: '.tmp/styles',
                ext: '.css'
            }]
        }
    },
```

## Watcher task Remove sass from the watcher task

```js
compass: {
    files: ['<%= yeoman.app %>/styles/{,*/}*.{scss,sass}'],
    tasks: ['compass:server', 'autoprefixer']
},
```

to

```js
sass: {
    files: ['<%= yeoman.app %>/styles/{,*/}*.{scss,sass}'],
    tasks: ['sass:server', 'autoprefixer']
},
```

## Update concurrent task

```js
// Run some tasks in parallel to speed up the build process
concurrent: {
    server: [
        'compass:server'
    ],
    test: [
        'compass'
    ],
    dist: [
        'compass:dist',
        'imagemin',
        'svgmin'
    ]
},
```
to
```js
// Run some tasks in parallel to speed up the build process
concurrent: {
    server: [
        'sass:server',
        'copy:styles'
    ],
    test: [
        'copy:styles'
    ],
    dist: [
        'sass',
        'copy:styles',
        'imagemin',
        'svgmin'
    ]
},
```

That should do the trick. If you are not using any unsupported libsass funcionality your project should be able to run serve and build without issues.

**Comment by johnymonster** [comment]
Thank you @karbassi !!!! I can't stand how slow compass is.

**Comment by manuelro** [comment]
I'm moving to libsass too. Compass runs extremely slow.

**Comment by mininao** [comment]
:+1: This would be extremely useful !

**Comment by javarch** [comment]
Ich werde ab  16.09.2015 nicht im B�ro sein. Ich kehre zur�ck am
12.10.2015.
Ich werde Ihre Nachricht nach meiner R�ckkehr beantworten.

Die R�ckmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [generator-angular] Provide Sass option without compass (#819)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2015 Agent 'Abwesenheit'

Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
DVR: 0572934, UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angef�hrten Absender via E-Mail
dient ausschlie�lich Informationszwecken. Rechtsgesch�ftliche Erkl�rungen
d�rfen �ber dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.

**Comment by MyDesignGit** [comment]
Thank you @karbassi , it saved a lot time.

**Comment by redfox05** [comment]
By the way, why is this closed. Its great that there are guides to move from compass to libsass, but surely the original ticket was about having this out of the box. Last time I ran generator-angular (10 minutes ago on 18th April 2016) this was still not available out of the box. So having this **open** and as **enhancement** must the be right state, rather than **closed**?

**Comment by eddiemonge** [comment]
no since there is already an issue with it open

**Comment by upuldi** [comment]
Thanks a lot, This saves me a lot of time, Really appreciate it.

**Comment by MacPike** [comment]
Finally the answer to all my problems. thx

**Comment by vishalkrv** [comment]
Thanks @karbassi, your post saved a lot of time..
