### ISSUE TITLE
grunt-connect-proxy -> how to overwrite 'middleware' in Gruntfile.js?

### ISSUE THREAD

**Issue by rowild** [yeoman/generator-angular#823]
The latest release of the yeoman angular generator adds some line into livereload.options.middleware in the Gruntfile.js.

How can these be combined, when grunt-connect-proxy is used, which requires add quite a bit of configuration to the middleware section, but does not respect the angular-generator return value?

Thanks for any hints!

**Comment by Extazystas** [comment]
@rowild great, works.

**Comment by doug7410** [comment]
@rowild Thank you! That's just what I was looking for. I was following a TutsPlus tutorial and it must of been recored before Yoman made this change.

**Comment by Stratus3D** [comment]
@rowild thanks for the example!
