### ISSUE TITLE
Remove superfluous .htaccess file

### ISSUE THREAD

**Issue by aendra-rininsland** [yeoman/generator-angular#849]
The app/ folder has a really bizarro .htaccess file, which totally had me and three IT folks scratching their heads about why stuff was redirecting to a different domain (It strips the "www" from domains or something).
1. How necessary is this .htaccess file to run AngularJS apps? My experience, from having run it via light webservers, Nginx, gh-pages, S3, etc.(i.e., "things that don't understand .htaccess files"), is not at all. 
2. If it is indeed superfluous, that file should be nuked from low-earth orbit. Seriously, realising that folder had a .htaccess file was a massive WTF moment.

**Comment by arthurvr** [comment]
I think we should reconsider this. We did it for both generator-webapp and gulp-webapp: https://github.com/yeoman/generator-webapp/pull/498 and https://github.com/yeoman/generator-gulp-webapp/pull/262.
