### ISSUE TITLE
Javascript dependencies are auto added to index.html, but not karma.conf.js

### ISSUE THREAD

**Issue by willhlaw** [yeoman/generator-angular#856]
My issues are the same as stated by @snicolai in [grunt-wiredep#35](https://github.com/stephenplusplus/grunt-wiredep/issues/35). 

Running ```grunt build``` or ```grunt serve``` or ```grunt wiredep``` does not automatically update karma.conf.js *files* array if bower.json has been updated with new javascript files, which would be nice since those files may be necessary when running the tests. That issue's solution *almost* solves the problem we have here for generator-angular.

Here is an improvement that should work on a clean, recent (as of today) version of generator-angular.

Add **// bower:js** and **// endbower** around the *bower_components* in the karma.conf.js file and above *app* and *test*.

**karma.conf.js**
```javascript
    // list of files / patterns to load in the browser
    files: [
      // bower:js
      'bower_components/angular/angular.js',
      'bower_components/angular-cookies/angular-cookies.js',
      'bower_components/angular-sanitize/angular-sanitize.js',
      'bower_components/angular-animate/angular-animate.js',
      'bower_components/angular-touch/angular-touch.js',
      'bower_components/angular-mocks/angular-mocks.js',
      // endbower
      'app/scripts/**/*.js',
      'test/mock/**/*.js',
      'test/spec/**/*.js'
    ],
```
Then, add the following *test* block to the *wiredep* task in Gruntfile.js.

**GruntFile.js**
```javascript
    // Automatically inject Bower components into the app
    wiredep: {
      app: {
        src: ['<%= yeoman.app %>/index.html'],
        ignorePath:  /\.\.\//
      },
      test: {
        devDependencies: true,
        src: 'test/karma.conf.js',
        ignorePath:  /\.\.\//,
        fileTypes: {
          js: {
            block: /(([\s\t]*)\/\/\s*bower:*(\S*))(\n|\r|.)*?(\/\/\s*endbower)/gi,
            detect: {
              js: /'(.*\.js)'/gi
            },
            replace: {
              js: '\'{{filePath}}\','
            }
          }
        }
      }
    },
```
The improvements on the solution that @stephenplusplus gave @snicolai are:
* added *devDependencies: true*, which is now a feature of wiredep and by extension, grunt-wiredep.
* added *ignorePath: /\.\.\//*, so that karma.conf.js does not have "../bower_components/" which cancels out *basePath* and broke ```grunt test```.
* improved the *detect* block by adding the parenthesis grouping: *js: /'(.*\.js)'/gi*, which is from [grunt-wiredep#86](https://github.com/stephenplusplus/grunt-wiredep/issues/86) so it allows us to keep *app* and *test* from being stomped over since those are not references found in bower.json.

**Comment by ddddave** [comment]
Thanks, @willhlaw this worked for me!
