### ISSUE TITLE
bower.json missing in app/ - or am I doing it wrong

### ISSUE THREAD

**Issue by rocco** [yeoman/generator-angular#885]
I create a fresh project with `yo angular [app-name]`, then do a `grunt` or `grunt serve` and get an error:

```
Running "wiredep:app" (wiredep) task
Warning: ENOENT, no such file or directory '/Users/Rocco/Develop/pavingways/it/webapp/public/app/bower.json' Use --force to continue.
```

I solve this by copying my bower.json into the app/ dir - not a great solution.
Wondering if I am missing something (just following docs/README here) or if it's a bug ...?

Yo version 1.3.0, same in 1.2.1.

Thanks!

**Comment by pabx06** [comment]
version 0.11.1 of the generator samethings here :
```
Running "wiredep:app" (wiredep) task
Warning: ENOENT, no such file or directory '/home/pbx06/mytodo/app/bower.json' Use --force to continue.

Aborted due to warnings.

```
so:

no such file or directory '/home/pbx06/mytodo/app/bower.json
while the bower.json is /home/pbx06/mytodo/bower.json
