### ISSUE TITLE
Bower component links point to wrong directory / are installed in wrong directory

### ISSUE THREAD

**Issue by kontur** [yeoman/generator-angular#907]
Hey,

after running the generator and visiting `/app/` you get missing resources, because all bower components seem to be linked to

```
/app/bower_components/angular/angular.js
/app/bower_components/...
```

However, the generator directory structure is:

```
/app/
/bower_components/
```

Am I missing something here or should there maybe a different path setting in the `.bowerrc`?

**Comment by Dashon** [comment]
@eddiemonge Im a YO,Grunt, bower & Node/NPM NOOB.

I completely understand and support the decision to move the bower_components out of the app directory, but what was your thoughts when it comes to deploying these files to a server other than one managed by grunt?  Are we expected to manually move the folder.

**Comment by eddiemonge** [comment]
@Dashon no, when you build the files, they get moved into the `dist` folder automatically.

**Comment by Dashon** [comment]
Gotcha, I had JSHint warnings that were aborting my build. Thanks a lot.

**Comment by bismark64** [comment]
I'm still having this "issue" using Gulp, index.html script tags generated by wiredep are like:

```html
<script src="/bower_components/jquery/dist/jquery.js"></script>
<script src="/bower_components/angular/angular.js"></script>
```

@eddiemonge said: "However, when the site is served using grunt serve, the bower_components folder is virtually under app so the script reference is correct."

Is this still true with Gulp? I mean, I run `gulp serve` but doesn't seem to make it work either. In the other hand, if I manually copy the bower_components folder inside the app folder it works perfectly. 

Sorry I know this is a very noob question but this makes no sense to me..

**Comment by eddiemonge** [comment]
Yes it should be true for gulp as well

**Comment by tetraquard** [comment]
@bismark64 I am also facing the same issue. Can you tell me how to deal with it?

**Comment by chrisjmccrum** [comment]
@bismark64 @eddiemonge @tetraquard  also having the same issue with gulp serve. there doesnt seem to be a virtual folder for bower_components when I run the app. im currently duplicating the folder as a workaround but it's an ugly fix imo

**Comment by silvster27** [comment]
See if this helps resolve the issue:  https://github.com/angular/angular-phonecat/issues/143
