### ISSUE TITLE
npm error while running yo angular

### ISSUE THREAD

**Issue by DikshantBhatia** [yeoman/generator-angular#919]
![error2](https://cloud.githubusercontent.com/assets/9398275/4957368/cbe8a3bc-66a3-11e4-8e6c-2cccf20e299b.PNG)
   Error code: EPERM      Error No: 50   stack: open 'C:\Users\windows 8\AppData\Roaming\npm-cache\7a285d9d-pm-cache-glob-3-2-11-package-tgz.lock'  . And i m also attaching the screenshot of what i got when i run the command grunt-serve.   How Should i proceed and use this generator?  Please help

Screenshot:
![error](https://cloud.githubusercontent.com/assets/9398275/4957291/1415821e-66a3-11e4-8bdd-6a1839935d76.PNG)

**Comment by unleashit** [comment]
Hi, I'm having the same issue except I'm on Windows so permissions usually aren't an issue right? In any case, I've Googled high and low to find an answer, but everyone blames it on either perms or a bad npm cache. I've cleared the cache and even reinstalled node (after wiping all node/npm folders) yet the problem still persists. So far I haven't had any issues with other projects besides generator-angular. Just tried installing yo webapp with no issues, and I run about a dozen apps using node/npm/grunt/bower etc.

**Comment by eddiemonge** [comment]
permissions could still be an issue with npm depending on how you installed it.
