### ISSUE TITLE
Cannot find where you keep your Bower packages.

### ISSUE THREAD

**Issue by asicfr** [yeoman/generator-angular#948]
On windows, with npm : 
{ http_parser: '1.0', node: '0.10.23', v8: '3.14.5.9', ares: '1.9.0-DEV', uv: '0.10.20',
  zlib: '1.2.3', modules: '11', openssl: '1.0.1e', npm: '1.3.17', clavierangularjs3: '0.0.0' }
and 

I install angular generator (npm install -g generator-angular)
I create a new folder and launch in this folder the following cmd : 
     yo angular
Without modify anything, i then launch the following cmd : 
    grunt serve
and i get : 
    Running "wiredep:app" (wiredep) task
    Cannot find where you keep your Bower packages.

I tried npm update, bower update and jesus update but it failed anyway.

What is the pb ? Thx for help ...

**Comment by ashrafatef** [comment]
I had the same problem but [this ](https://stackoverflow.com/questions/26182287/grunt-wiredepapp-cannot-find-bower-packages/44377842#44377842) helped me
