### ISSUE TITLE
No styles displayed and no .tmp folder on grunt build, "Destination not written... minified CSS was empty."

### ISSUE THREAD

**Issue by matt-mcdaniel** [yeoman/generator-angular#956]
I'm running a Virtual Node Server hosted through Digital Ocean on an Ubuntu machine.

I have a pretty standard <code>yo angular</code> install. I admittedly uninstalled <code>karma</code>, but otherwise it's clean.

When I run <code>grunt</code>, I get the following error, presumably as a part of the <code>build</code> task:

<pre><code>Running "cssmin:generated" (cssmin) task
>> Destination not written because minified CSS was empty.
</code></pre>

I found a <a href="https://github.com/yeoman/generator-webapp/issues/211">similar issue on generator-webapp (#211)</a> where the problem was ensuring ruby, sass, and compass were correctly installed on the machine. I have checked the versions for the three <code>ruby -v</code>, <code>compass -v</code> and <code>sudo compass version</code> (compass requires permission for <code>sudo compass version</code>). They all seem to be installed fine, although running <code>

In my <code>gem list</code> I have:
<pre><code>
compass (1.0.1, 0.12.2)
sass (3.4.9, 3.2.12)
</pre></code>

<code>ruby -v</code> outputs <code>ruby 1.9.3p484</code>, so it appears all three are installed correctly.

---

The problem appears to be related to the fact that no <code>.tmp</code> directory exists in <code>server/dist</code>.

The <code>styles</code> directory exists in <code>server/dist</code>, but there is no <code>.tmp</code> folder. I manually created a .tmp folder, but it was deleted after running grunt. Could this be the problem? 

Any help is appreciated.

**Comment by bramcordie** [comment]
I bumped into a similar problem but I'm not using sass. The concurrent:dist task that copies the main.css file that was running in parallel was not ready before minification started. Adding the copy:styles content to the copy:dist command fixed the problem for me.
