### ISSUE TITLE
using bootstrap but removing jquery to use bootstrap-ui

### ISSUE THREAD

**Issue by andyf625** [yeoman/generator-angular#968]
i first tried just deleting the jquery links in the index but theres a setting in grunt that automatically makes a link for any any bower component.
given that jquery is packaged with bootstrap.. it reinserts the link each restart of grunt.

- what would be the best way to remove jquery ?

- remove from index to edit the grunt file?

**Comment by eddiemonge** [comment]
Look at grunt-wiredep. You need to add jquery to the list of excluded files.
