### ISSUE TITLE
Grunt serve throws error

### ISSUE THREAD

**Issue by DavideMontersino** [yeoman/generator-angular#971]
When I use grunt serve, it looks like something is called recursively until everything crashes:

    (node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.

    util.js:35
      var str = String(f).replace(formatRegExp, function(x) {
                      ^
    RangeError: Maximum call stack size exceeded

The most similar issue I could find is this grunt related bug, but I can't actually apply the solution here:
http://stackoverflow.com/questions/22285942/grunt-throw-recursive-process-nexttick-detected

**Comment by eddiemonge** [comment]
I haven't seen this before. If I get more reports I'll investigate but at the moment I can't reproduce.

**Comment by DavideMontersino** [comment]
Ok, thank you. Actually looks a random behaviour to me: I tried the
generator a few times, and in about half of the cases the behaviour would
appear.
If I get more understanding of what's happening, I'll post it here.

Davide Orazio Montersino,

*Fundraising team leader*
*TEDxCrocetta*
*Skype: davide.orazio.montersino*
*Phone: 0039 348 480 6160*
*web: http://www.davidemontersino.com <http://www.davidemontersino.com>*

**Comment by precz** [comment]
I got the same: 

Many of:
```Running "watch" task
Waiting...
Warning: watch ENOSPC```
Then lots:
```(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.```
And at the end:
```util.js:35
  var str = String(f).replace(formatRegExp, function(x) {
                  ^
RangeError: Maximum call stack size exceeded
```

the solution that worked: 
http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc

**Comment by eddiemonge** [comment]
I still haven't been able to reproduce this. if its still happening, open an issue at grunt-contrib-watch.
