### ISSUE TITLE
grunt test: Task "karma" not found.

### ISSUE THREAD

**Issue by bmcorser** [yeoman/generator-angular#972]
Following the tutorial, when I run:

```
npm install -g yo bower grunt-cli gulp
npm install -g generator-angular
yo angular test-app
grunt test
```
I end up with:
```
Warning: Task "karma" not found. Use --force to continue.

Aborted due to warnings.


Execution Time (2015-01-13 16:26:10 UTC)
loading tasks  3ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 100%
Total 3ms
```
I do see a task called "karma" being registered in the `Gruntfile.js`. Confusion ensues.

Thankfully SO comes [to the rescue](http://stackoverflow.com/questions/16701987/yeoman-eacces-error-running-karma-unit-test-for-angularjs). I have shit running on `8080`, but the error message doesn't tell me that's a problem. Perhaps it could?

**Comment by bmcorser** [comment]
Ah wait, SO doesn't come to the rescue. It was a trick of my eyes. The "karma" task is still nowhere to be found (according to `grunt test`)

**Comment by bmcorser** [comment]
If I `npm install grunt-karma` and add
```
grunt.loadNpmTasks('grunt-karma'); 
```
to the Gruntfile, then it works

**Comment by eddiemonge** [comment]
This should not be necessary at all since its auto-loaded: `grunt.loadNpmTasks('grunt-karma');`

I'm betting you had npm problems when you ran the install. Thats the most common problem.

**Comment by viniciuspires** [comment]
@eddiemonge Karma and its friends are not included in the `devDependencies` section of the `package.json`.

I had to do a `npm install karma grunt-karma karma-phantomjs-launcher karma-jasmine`

**Comment by BrodaNoel** [comment]
This issue persists.
This is happening when you have no Python installed.

I did it:
`yo angular test` (with all be default)
and I can see that there is package related to karma into the package.json, that could be because while `yo` install the karma plugin is getting an error.

I remove all the files, installed Python, and re run `yo angular test`, and now I can see `grunt-karma`, `grunt-jasmine` and more.

**Comment by Kys3r** [comment]
The only solution for me that work is:

    sudo npm install grunt-karma karma karma-phantomjs-launcher karma-jasmine jasmine-core phantomjs-prebuilt --save-dev

    grunt test 
or: 
    grunt serve
, it's work !
