### ISSUE TITLE
grunt build is breaking index.html in dist folder

### ISSUE THREAD

**Issue by EdwinFLopez** [yeoman/generator-angular#974]
Hi. 
I'm starting a new project with "yo angular AngTest", no SASS, with Bootstrap and default angular modules (animate, cookies, resource, route, sanitize, touch). After the generator finishes, I run grunt build, the generated index.html in dist/ folder is corrupted (no closing tags for html, head, body):

``` html
<!doctype html> <html class="no-js"> <head> <meta charset="utf-8"> <title></title> <meta name="description" content=""> <meta name="viewport" content="width=device-width"> <!-- Place favicon.ico and apple-touch-icon.png in the root directory --> <link rel="stylesheet" href="styles/vendor.cabc70f2.css"> <link rel="stylesheet" href="styles/main.e0afbcbc.css">  <body ng-app="angTestApp"> <!--[if lt IE 7]>
      <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]--> <!-- Add your site or application content here --> <div class="container"> <div class="header"> <ul class="nav nav-pills pull-right"> <li class="active"><a ng-href="#">Home</a></li> <li><a ng-href="#/about">About</a></li> <li><a ng-href="#">Contact</a></li> </ul> <h3 class="text-muted">angTest</h3> </div> <div ng-view=""></div> <div class="footer"> <p><span class="glyphicon glyphicon-heart"></span> from the Yeoman team</p> </div> </div> <!-- Google Analytics: change UA-XXXXX-X to be your site's ID --> <script>(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
       (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
       m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
       })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

       ga('create', 'UA-XXXXX-X');
       ga('send', 'pageview');</script> <!--[if lt IE 9]>
    <script src="scripts/oldieshim.76f279db.js"></script>
    <![endif]--> <script src="scripts/vendor.3ae14b7d.js"></script> <script src="scripts/scripts.a3c495f8.js"></script>   
```

I'm using Windows 8 + Node (v0.10.33) + npm(2.1.18) + angular-generator(0.10.0). Dependencies for the generator: generator-angular@0.10.0 C:\Program Files\nodejs\node_modules\generator-angular
├── chalk@0.4.0 (ansi-styles@1.0.0, has-color@0.1.7, strip-ansi@0.1.1)
├── yosay@0.2.1 (pad-component@0.0.1, word-wrap@0.1.3, minimist@0.0.9)
├── yeoman-generator@0.16.0 (dargs@0.1.0, debug@0.7.4, diff@1.0.8, class-extend@0.1.1, rimraf@2.2.8, findup-sync@0.1.3, text-table@0.2.0, mkdirp@0.3.5, mime@1.2.11, async@0.2.10, isbinaryfile@2.0.3, shelljs@0.2.6, iconv-lite@0.2.11, glob@3.2.11, underscore.string@2.3.3, lodash@2.4.1, file-utils@0.1.5, request@2.30.0, download@0.1.19, inquirer@0.4.1, cheerio@0.13.1)
└── wiredep@1.8.6 (propprop@0.3.0, minimist@1.1.0, chalk@0.5.1, through2@0.6.3, lodash@2.4.1, glob@4.3.4, bower-config@0.5.2)

Thanks

**Comment by sindresorhus** [comment]
As intended. That's just the HTML minifier. Those tags are optional.

**Comment by EdwinFLopez** [comment]
Thank you. I had no idea about it. I reached the w3c specs at http://www.w3.org/TR/html5/syntax.html#syntax-tag-omission and learned about it.
