### ISSUE TITLE
error in the step 'CXX(target) Release/obj.target/fse/fsevents.o'

### ISSUE THREAD

**Issue by iShiZhi** [yeoman/generator-angular#977]
My environment is:

    system: OS X Yosemite 10.10.1
    node: 0.10.35
    npm: 2.1.18
    yo: 1.4.2
    generator-angular: 0.10.0

When I run 'yo angular', it reports:

    Out of the box I include Bootstrap and some AngularJS recommended modules.

    ? Would you like to use Sass (with Compass)? No
    ? Would you like to include Bootstrap? Yes
    ? Which modules would you like to include? angular-animate.js, angular-cookies.js, angular-resource.js, angular-route.js, angular-sanitize.js, angular-touch.js
       create app/styles/main.css
       create app/index.html
       create bower.json
       create .bowerrc
       create package.json
       create Gruntfile.js
       invoke   angular:common:/usr/local/lib/node_modules/generator-angular/app/index.js
       create     .editorconfig
       create     .gitattributes
       create     .jshintrc
       create     .gitignore
       create     test/.jshintrc
       create     app/.buildignore
       create     app/.htaccess
       create     app/404.html
       create     app/favicon.ico
       create     app/robots.txt
       create     app/views/main.html
       create     app/images/yeoman.png
       invoke   angular:main:/usr/local/lib/node_modules/generator-angular/app/index.js
       create     app/scripts/app.js
       invoke   angular:controller:/usr/local/lib/node_modules/generator-angular/app/index.js
       create     app/scripts/controllers/main.js
       create     test/spec/controllers/main.js
       invoke   karma:app

    I'm all done. Running bower install & npm install for you to install the required dependencies. If this fails, try running the command yourself.

       invoke       angular:route
       invoke           angular:controller:/usr/local/lib/node_modules/generator-angular/route/index.js
       create             app/scripts/controllers/about.js
       create             test/spec/controllers/about.js
       invoke           angular:view:/usr/local/lib/node_modules/generator-angular/route/index.js
       create             app/views/about.html
       create     test/karma.conf.js
       create     .travis.yml
    npm WARN package.json angular@0.0.0 No description
    npm npm WARN package.json angular@0.0.0 No description
    WARN package.json angular@0.0.0 No repository field.
    npm WARN package.jsonnpm  angular@0.0.0 No repository field.
    WARN package.json angular@0.0.0 No README data
    npm WARN package.json angular@0.0.0 No README data
    bower angular#^1.3.0            cached git://github.com/angular/bower-angular.git#1.3.9
    bower angular#^1.3.0          validate 1.3.9 against git://github.com/angular/bower-angular.git#^1.3.0
    bower es5-shim#^4.0.0           cached git://github.com/es-shims/es5-shim.git#4.0.5
    bower es5-shim#^4.0.0         validate 4.0.5 against git://github.com/es-shims/es5-shim.git#^4.0.0
    bower json3#^3.3.0              cached git://github.com/bestiejs/json3.git#3.3.2
    bower json3#^3.3.0            validate 3.3.2 against git://github.com/bestiejs/json3.git#^3.3.0
    bower bootstrap#^3.2.0          cached git://github.com/twbs/bootstrap.git#3.3.1
    bower bootstrap#^3.2.0        validate 3.3.1 against git://github.com/twbs/bootstrap.git#^3.2.0
    bower angular-resource#^1.3.0   cached git://github.com/angular/bower-angular-resource.git#1.3.9
    bower angular-resource#^1.3.0 validate 1.3.9 against git://github.com/angular/bower-angular-resource.git#^1.3.0
    bower angular-route#^1.3.0      cached git://github.com/angular/bower-angular-route.git#1.3.9
    bower angular-route#^1.3.0    validate 1.3.9 against git://github.com/angular/bower-angular-route.git#^1.3.0
    bower angular-cookies#^1.3.0    cached git://github.com/angular/bower-angular-cookies.git#1.3.9
    bower angular-cookies#^1.3.0  validate 1.3.9 against git://github.com/angular/bower-angular-cookies.git#^1.3.0
    bower angular-animate#^1.3.0    cached git://github.com/angular/bower-angular-animate.git#1.3.9
    bower angular-animate#^1.3.0  validate 1.3.9 against git://github.com/angular/bower-angular-animate.git#^1.3.0
    bower angular-mocks#~1.3.0      cached git://github.com/angular/bower-angular-mocks.git#1.3.9
    bower angular-mocks#~1.3.0    validate 1.3.9 against git://github.com/angular/bower-angular-mocks.git#~1.3.0
    bower angular-scenario#~1.3.0   cached git://github.com/angular/bower-angular-scenario.git#1.3.9
    bower angular-scenario#~1.3.0 validate 1.3.9 against git://github.com/angular/bower-angular-scenario.git#~1.3.0
    bower angular-sanitize#^1.3.0   cached git://github.com/angular/bower-angular-sanitize.git#1.3.9
    bower angular-sanitize#^1.3.0 validate 1.3.9 against git://github.com/angular/bower-angular-sanitize.git#^1.3.0
    bower angular-touch#^1.3.0      cached git://github.com/angular/bower-angular-touch.git#1.3.9
    bower angular-touch#^1.3.0    validate 1.3.9 against git://github.com/angular/bower-angular-touch.git#^1.3.0
    bower jquery#>= 1.9.1           cached git://github.com/jquery/jquery.git#2.1.3
    bower jquery#>= 1.9.1         validate 2.1.3 against git://github.com/jquery/jquery.git#>= 1.9.1
    npm WARN excluding symbolic link build/defs-config.json -> ../defs-config.json
    bower json3#^3.3.0             install json3#3.3.2
    bower es5-shim#^4.0.0          install es5-shim#4.0.5
    bower angular-resource#^1.3.0  install angular-resource#1.3.9
    bower angular#^1.3.0           install angular#1.3.9
    bower angular-cookies#^1.3.0   install angular-cookies#1.3.9
    bower angular-route#^1.3.0     install angular-route#1.3.9
    bower bootstrap#^3.2.0         install bootstrap#3.3.1
    bower angular-animate#^1.3.0   install angular-animate#1.3.9
    bower angular-mocks#~1.3.0     install angular-mocks#1.3.9
    bower angular-scenario#~1.3.0  install angular-scenario#1.3.9
    bower angular-touch#^1.3.0     install angular-touch#1.3.9
    bower angular-sanitize#^1.3.0  install angular-sanitize#1.3.9
    bower jquery#>= 1.9.1          install jquery#2.1.3
    -
    json3#3.3.2 bower_components/json3

    es5-shim#4.0.5 bower_components/es5-shim

    angular-resource#1.3.9 bower_components/angular-resource
    └── angular#1.3.9

    angular#1.3.9 bower_components/angular

    angular-cookies#1.3.9 bower_components/angular-cookies
    └── angular#1.3.9

    angular-route#1.3.9 bower_components/angular-route
    └── angular#1.3.9

    bootstrap#3.3.1 bower_components/bootstrap
    └── jquery#2.1.3

    angular-animate#1.3.9 bower_components/angular-animate
    └── angular#1.3.9

    angular-mocks#1.3.9 bower_components/angular-mocks
    └── angular#1.3.9

    angular-scenario#1.3.9 bower_components/angular-scenario
    └── angular#1.3.9

    angular-touch#1.3.9 bower_components/angular-touch
    └── angular#1.3.9

    angular-sanitize#1.3.9 bower_components/angular-sanitize
    └── angular#1.3.9

    jquery#2.1.3 bower_components/jquery

    > fsevents@0.3.4 install /Users/zhi.shi/Documents/projects/angular/node_modules/karma/node_modules/chokidar/node_modules/fsevents
    > node-gyp rebuild

      SOLINK_MODULE(target) Release/.node
      SOLINK_MODULE(target) Release/.node: Finished
      CXX(target) Release/obj.target/fse/fsevents.o
    In file included from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:55,
                     from ../fsevents.cc:11:
    /System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:262: error: expected `}' before ‘__attribute__’
    /System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:262: error: expected unqualified-id before ‘=’ token
    /System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:414: error: expected `}' before ‘__attribute__’
    /System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:414: error: expected unqualified-id before ‘=’ token
    /System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:481: error: expected declaration before ‘}’ token
    make: *** [Release/obj.target/fse/fsevents.o] Error 1
    gyp ERR! build error
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
    gyp ERR! System Darwin 14.0.0
    gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /Users/zhi.shi/Documents/projects/angular/node_modules/karma/node_modules/chokidar/node_modules/fsevents
    gyp ERR! node -v v0.10.35
    gyp ERR! node-gyp -v v1.0.2
    gyp ERR! not ok

    > phantomjs@1.9.13 install /Users/zhi.shi/Documents/projects/angular/node_modules/karma-phantomjs-launcher/node_modules/phantomjs
    > node install.js

    Download already available at /var/folders/jd/713zkyld3b51bdtrjmq80cm05mw4gy/T/phantomjs/phantomjs-1.9.8-macosx.zip
    Extracting zip contents
    Removing /Users/zhi.shi/Documents/projects/angular/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom
    Copying extracted folder /var/folders/jd/713zkyld3b51bdtrjmq80cm05mw4gy/T/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1421375523686/phantomjs-1.9.8-macosx -> /Users/zhi.shi/Documents/projects/angular/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom
    Removing /var/folders/jd/713zkyld3b51bdtrjmq80cm05mw4gy/T/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1421375523686
    Writing location.js file
    Done. Phantomjs binary available at /Users/zhi.shi/Documents/projects/angular/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom/bin/phantomjs
    npm WARN optional dep failed, continuing fsevents@0.3.4

    > ws@0.4.32 install /Users/zhi.shi/Documents/projects/angular/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
    > (node-gyp rebuild 2> builderror.log) || (exit 0)

      CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
      SOLINK_MODULE(target) Release/bufferutil.node
      SOLINK_MODULE(target) Release/bufferutil.node: Finished
      CXX(target) Release/obj.target/validation/src/validation.o
      SOLINK_MODULE(target) Release/validation.node
      SOLINK_MODULE(target) Release/validation.node: Finished
    npm WARN unmet dependency /Users/zhi.shi/Documents/projects/angular/node_modules/grunt-contrib-jshint/node_modules/jshint/node_modules/cli/node_modules/glob requires minimatch@'0.3' but will load
    npm WARN unmet dependency /Users/zhi.shi/Documents/projects/angular/node_modules/grunt-contrib-jshint/node_modules/jshint/node_modules/minimatch,
    npm WARN unmet dependency which is version 1.0.0
    npm WARN unmet dependency /Users/zhi.shi/Documents/projects/angular/node_modules/grunt/node_modules/js-yaml/node_modules/argparse requires underscore.string@'~2.4.0' but will load
    npm WARN unmet dependency /Users/zhi.shi/Documents/projects/angular/node_modules/grunt/node_modules/underscore.string,
    npm WARN unmet dependency which is version 2.2.1
    npm WARN unmet dependency /Users/zhi.shi/Documents/projects/angular/node_modules/grunt-google-cdn/node_modules/bower/node_modules/bower-registry-client requires graceful-fs@'~2.0.0' but will load
    npm WARN unmet dependency /Users/zhi.shi/Documents/projects/angular/node_modules/grunt-google-cdn/node_modules/bower/node_modules/graceful-fs,
    npm WARN unmet dependency which is version 3.0.5
    npm WARN unmet dependency /Users/zhi.shi/Documents/projects/angular/node_modules/grunt-google-cdn/node_modules/bower/node_modules/bower-registry-client requires lru-cache@'~2.3.0' but will load
    npm WARN unmet dependency /Users/zhi.shi/Documents/projects/angular/node_modules/grunt-google-cdn/node_modules/bower/node_modules/lru-cache,
    npm WARN unmet dependency which is version 2.5.0
    npm WARN unmet dependency /Users/zhi.shi/Documents/projects/angular/node_modules/grunt-google-cdn/node_modules/bower/node_modules/bower-registry-client requires request@'~2.27.0' but will load
    npm WARN unmet dependency /Users/zhi.shi/Documents/projects/angular/node_modules/grunt-google-cdn/node_modules/bower/node_modules/request,
    npm WARN unmet dependency which is version 2.42.0
    npm WARN unmet dependency /Users/zhi.shi/Documents/projects/angular/node_modules/grunt-google-cdn/node_modules/bower/node_modules/bower-registry-client requires mkdirp@'~0.3.5' but will load
    npm WARN unmet dependency /Users/zhi.shi/Documents/projects/angular/node_modules/grunt-google-cdn/node_modules/bower/node_modules/mkdirp,
    npm WARN unmet dependency which is version 0.5.0
    npm WARN unmet dependency /Users/zhi.shi/Documents/projects/angular/node_modules/grunt-google-cdn/node_modules/bower/node_modules/decompress-zip/node_modules/touch requires nopt@'~1.0.10' but will load
    npm WARN unmet dependency /Users/zhi.shi/Documents/projects/angular/node_modules/grunt-google-cdn/node_modules/bower/node_modules/decompress-zip/node_modules/nopt,
    npm WARN unmet dependency which is version 2.2.1
    npm WARN unmet dependency /Users/zhi.shi/Documents/projects/angular/node_modules/grunt-google-cdn/node_modules/bower/node_modules/insight/node_modules/configstore requires object-assign@'^2.0.0' but will load
    npm WARN unmet dependency /Users/zhi.shi/Documents/projects/angular/node_modules/grunt-google-cdn/node_modules/bower/node_modules/insight/node_modules/object-assign,
    npm WARN unmet dependency which is version 1.0.0
    grunt-karma@0.10.1 node_modules/grunt-karma
    └── lodash@2.4.1

    karma-phantomjs-launcher@0.1.4 node_modules/karma-phantomjs-launcher
    └── phantomjs@1.9.13 (which@1.0.8, progress@1.1.8, rimraf@2.2.8, kew@0.4.0, ncp@1.0.1, adm-zip@0.4.4, request-progress@0.3.1, mkdirp@0.5.0, npmconf@2.0.9, request@2.42.0)

    jasmine-core@2.1.3 node_modules/jasmine-core

    karma@0.12.31 node_modules/karma
    ├── di@0.0.1
    ├── graceful-fs@2.0.3
    ├── rimraf@2.2.8
    ├── colors@0.6.2
    ├── mime@1.2.11
    ├── q@0.9.7
    ├── minimatch@0.2.14 (sigmund@1.0.0, lru-cache@2.5.0)
    ├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
    ├── optimist@0.6.1 (wordwrap@0.0.2, minimist@0.0.10)
    ├── source-map@0.1.43 (amdefine@0.1.0)
    ├── lodash@2.4.1
    ├── useragent@2.0.10 (lru-cache@2.2.4)
    ├── log4js@0.6.22 (semver@1.1.4, async@0.2.10, readable-stream@1.0.33)
    ├── http-proxy@0.10.4 (pkginfo@0.3.0, utile@0.2.1)
    ├── connect@2.26.6 (cookie@0.1.2, fresh@0.2.4, pause@0.0.1, cookie-signature@1.0.5, response-time@2.0.1, vhost@3.0.0, basic-auth-connect@1.0.0, on-headers@1.0.0, bytes@1.0.0, media-typer@0.3.0, parseurl@1.3.0, cookie-parser@1.3.3, depd@0.4.5, qs@2.2.4, debug@2.0.0, connect-timeout@1.3.0, finalhandler@0.2.0, method-override@2.2.0, serve-favicon@2.1.7, type-is@1.5.5, multiparty@3.3.2, errorhandler@1.2.4, compression@1.1.2, serve-index@1.2.1, body-parser@1.8.4, morgan@1.3.2, serve-static@1.6.4, csurf@1.6.5, express-session@1.8.2)
    ├── chokidar@0.12.6 (async-each@0.1.6, readdirp@1.3.0)
    └── socket.io@0.9.16 (base64id@0.1.0, policyfile@0.0.4, redis@0.7.3, socket.io-client@0.9.16)

    karma-jasmine@0.3.4 node_modules/karma-jasmine
    \
    > optipng-bin@1.0.1 postinstall /Users/zhi.shi/Documents/projects/angular/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
    > node lib/install.js

         fetch : https://raw.github.com/imagemin/optipng-bin/v1.0.1/vendor/osx/optipng
      progress : [====================] 100% 0.0s

    ✔ pre-build test passed successfully!

    > gifsicle@1.0.3 postinstall /Users/zhi.shi/Documents/projects/angular/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
    > node lib/install.js

         fetch : https://raw.github.com/imagemin/gifsicle-bin/v1.0.3/vendor/osx/gifsicle
      progress : [====================] 100% 0.0s

    ✔ pre-build test passed successfully!

    > pngquant-bin@1.0.1 postinstall /Users/zhi.shi/Documents/projects/angular/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin
    > node lib/install.js

         fetch : https://raw.github.com/imagemin/pngquant-bin/v1.0.1/vendor/osx/pngquant
      progress : [====================] 100% 0.0s

    ✔ pre-build test passed successfully!

    > jpegtran-bin@1.0.2 postinstall /Users/zhi.shi/Documents/projects/angular/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
    > node lib/install.js

         fetch : https://raw.github.com/imagemin/jpegtran-bin/v1.0.2/vendor/osx/jpegtran
      progress : [====================] 100% 0.0s

    ✔ pre-build test passed successfully!
    grunt-contrib-copy@0.5.0 node_modules/grunt-contrib-copy

    grunt-contrib-clean@0.5.0 node_modules/grunt-contrib-clean
    └── rimraf@2.2.8

    grunt-newer@0.7.0 node_modules/grunt-newer
    ├── rimraf@2.2.6
    └── async@0.2.10

    grunt-contrib-concat@0.4.0 node_modules/grunt-contrib-concat
    └── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)

    jshint-stylish@0.2.0 node_modules/jshint-stylish
    ├── text-table@0.2.0
    └── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)

    grunt-filerev@0.2.1 node_modules/grunt-filerev
    ├── each-async@0.1.3
    └── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)

    time-grunt@0.3.2 node_modules/time-grunt
    ├── date-time@0.1.1
    ├── pretty-ms@0.1.0
    ├── text-table@0.2.0
    ├── hooker@0.2.3
    └── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)

    grunt-concurrent@0.5.0 node_modules/grunt-concurrent
    ├── async@0.2.10
    └── pad-stdio@0.1.1 (lpad@0.2.1)

    load-grunt-tasks@0.4.0 node_modules/load-grunt-tasks
    ├── multimatch@0.1.0 (lodash@2.4.1, minimatch@0.2.14)
    └── findup-sync@0.1.3 (lodash@2.4.1, glob@3.2.11)

    grunt-usemin@2.6.2 node_modules/grunt-usemin
    ├── lodash@2.4.1
    ├── debug@2.1.1 (ms@0.6.2)
    └── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)

    grunt-contrib-htmlmin@0.3.0 node_modules/grunt-contrib-htmlmin
    ├── pretty-bytes@0.1.2
    ├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
    └── html-minifier@0.6.9 (relateurl@0.2.6, clean-css@2.2.23, cli@0.6.5, change-case@2.1.6, uglify-js@2.4.16)

    grunt-contrib-watch@0.6.1 node_modules/grunt-contrib-watch
    ├── async@0.2.10
    ├── lodash@2.4.1
    ├── tiny-lr-fork@0.0.5 (debug@0.7.4, faye-websocket@0.4.4, noptify@0.0.3, qs@0.5.6)
    └── gaze@0.5.1 (globule@0.1.0)

    grunt-contrib-uglify@0.4.1 node_modules/grunt-contrib-uglify
    ├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
    ├── uglify-js@2.4.16 (uglify-to-browserify@1.0.2, async@0.2.10, optimist@0.3.7, source-map@0.1.34)
    └── maxmin@0.1.0 (pretty-bytes@0.1.2, gzip-size@0.1.1)

    grunt-contrib-cssmin@0.9.0 node_modules/grunt-contrib-cssmin
    ├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
    ├── clean-css@2.1.8 (commander@2.1.0)
    └── maxmin@0.1.0 (pretty-bytes@0.1.2, gzip-size@0.1.1)

    grunt-contrib-jshint@0.10.0 node_modules/grunt-contrib-jshint
    ├── hooker@0.2.3
    └── jshint@2.5.11 (strip-json-comments@1.0.2, underscore@1.6.0, exit@0.1.2, minimatch@1.0.0, shelljs@0.3.0, console-browserify@1.1.0, htmlparser2@3.8.2, cli@0.6.5)

    grunt@0.4.5 node_modules/grunt
    ├── which@1.0.8
    ├── dateformat@1.0.2-1.2.3
    ├── eventemitter2@0.4.14
    ├── getobject@0.1.0
    ├── rimraf@2.2.8
    ├── colors@0.6.2
    ├── async@0.1.22
    ├── hooker@0.2.3
    ├── grunt-legacy-util@0.2.0
    ├── exit@0.1.2
    ├── glob@3.1.21 (inherits@1.0.0, graceful-fs@1.2.3)
    ├── lodash@0.9.2
    ├── coffee-script@1.3.3
    ├── underscore.string@2.2.1
    ├── minimatch@0.2.14 (sigmund@1.0.0, lru-cache@2.5.0)
    ├── iconv-lite@0.2.11
    ├── findup-sync@0.1.3 (glob@3.2.11, lodash@2.4.1)
    ├── grunt-legacy-log@0.1.1 (underscore.string@2.3.3, lodash@2.4.1)
    ├── nopt@1.0.10 (abbrev@1.0.5)
    └── js-yaml@2.0.5 (argparse@0.1.16, esprima@1.0.4)

    grunt-svgmin@0.4.0 node_modules/grunt-svgmin
    ├── each-async@0.1.3
    ├── pretty-bytes@0.1.2
    ├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
    └── svgo@0.4.5 (colors@0.6.2, whet.extend@0.9.9, coa@0.4.1, sax@0.6.1, js-yaml@2.1.3)

    grunt-wiredep@1.9.0 node_modules/grunt-wiredep
    └── wiredep@1.8.6 (propprop@0.3.0, minimist@1.1.0, chalk@0.5.1, through2@0.6.3, lodash@2.4.1, glob@4.3.5, bower-config@0.5.2)

    grunt-ng-annotate@0.4.0 node_modules/grunt-ng-annotate
    └── ng-annotate@0.10.3 (tryor@0.1.2, alter@0.2.0, simple-fmt@0.1.0, simple-is@0.2.0, stringset@0.2.1, stringmap@0.2.2, stable@0.1.5, convert-source-map@0.4.1, optimist@0.6.1, source-map@0.1.43, ordered-ast-traverse@0.1.1, esprima@1.2.2, acorn@0.9.0)

    grunt-autoprefixer@0.7.6 node_modules/grunt-autoprefixer
    ├── diff@1.0.8
    ├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
    └── autoprefixer@1.3.1 (fs-extra@0.9.1, postcss@0.3.5, caniuse-db@1.0.30000047)

    grunt-contrib-connect@0.7.1 node_modules/grunt-contrib-connect
    ├── connect-livereload@0.3.2
    ├── open@0.0.4
    ├── async@0.2.10
    ├── portscanner@0.2.2 (async@0.1.15)
    └── connect@2.13.1 (uid2@0.0.3, methods@0.1.0, debug@0.8.1, pause@0.0.1, cookie-signature@1.0.1, fresh@0.2.0, qs@0.6.6, bytes@0.2.1, buffer-crc32@0.2.1, raw-body@1.1.3, batch@0.5.0, cookie@0.1.0, compressible@1.0.0, negotiator@0.3.0, send@0.1.4, multiparty@2.2.0)

    grunt-google-cdn@0.4.3 node_modules/grunt-google-cdn
    ├── google-cdn@0.7.0 (regexp-quote@0.0.0, google-cdn-data@0.1.15, async@0.9.0, semver@2.3.2, debug@1.0.4, cdnjs-cdn-data@0.1.1)
    ├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
    └── bower@1.3.12 (is-root@1.0.0, junk@1.0.0, stringify-object@1.0.0, which@1.0.8, abbrev@1.0.5, chmodr@0.1.0, osenv@0.1.0, archy@0.0.2, opn@1.0.1, rimraf@2.2.8, bower-logger@0.2.2, lru-cache@2.5.0, bower-endpoint-parser@0.2.2, graceful-fs@3.0.5, lockfile@1.0.0, nopt@3.0.1, retry@0.6.0, tmp@0.0.23, request-progress@0.3.0, q@1.0.1, semver@2.3.2, p-throttler@0.1.0, fstream@1.0.3, mkdirp@0.5.0, chalk@0.5.0, bower-config@0.5.2, shell-quote@1.4.2, bower-json@0.4.0, promptly@0.2.0, request@2.42.0, glob@4.0.6, fstream-ignore@1.0.2, tar-fs@0.5.2, decompress-zip@0.0.8, cardinal@0.4.0, bower-registry-client@0.2.2, update-notifier@0.2.0, mout@0.9.1, inquirer@0.7.1, insight@0.4.3, handlebars@2.0.0)

    grunt-contrib-imagemin@0.8.1 node_modules/grunt-contrib-imagemin
    ├── async@0.9.0
    ├── pretty-bytes@1.0.2 (get-stdin@1.0.0)
    ├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
    └── imagemin@1.0.5 (get-stdin@3.0.2, stat-mode@0.2.0, ware@0.3.0, nopt@3.0.1, tempfile@1.1.0, fs-extra@0.11.1, imagemin-svgo@1.0.2, imagemin-optipng@1.0.0, imagemin-gifsicle@1.0.0, imagemin-pngquant@1.0.2, imagemin-jpegtran@1.0.0)
    app/index.html modified.
    MACBOX-0FFD56:angular zhi.shi$ bower list
    bower check-new     Checking for new versions of the project dependencies..
    angular#0.0.0 /Users/zhi.shi/Documents/projects/angular
    ├── angular#1.3.9 (1.4.0-build.3787+sha.2b64f6e available)
    ├── angular-animate#1.3.9 (1.4.0-build.3787+sha.2b64f6e available)
    ├── angular-cookies#1.3.9 (1.4.0-build.3787+sha.2b64f6e available)
    ├── angular-mocks#1.3.9 (1.3.10-build.20+sha.5c2da38 available, latest is 1.4.0-build.3787+sha.2b64f6e)
    ├── angular-resource#1.3.9 (1.4.0-build.3787+sha.2b64f6e available)
    ├── angular-route#1.3.9 (1.4.0-build.3787+sha.2b64f6e available)
    ├── angular-sanitize#1.3.9 (1.4.0-build.3787+sha.2b64f6e available)
    ├── angular-scenario#1.3.9 (1.3.10-build.20+sha.5c2da38 available, latest is 1.4.0-build.3787+sha.2b64f6e)
    ├── angular-touch#1.3.9 (1.4.0-build.3787+sha.2b64f6e available)
    ├─┬ bootstrap#3.3.1
    │ └── jquery#2.1.3
    ├── es5-shim#4.0.5
    └── json3#3.3.2

After generation, 'grunt serve' and 'grunt test' both work. But I still wonder what happens in the process.

**Comment by sindresorhus** [comment]
Please include the full terminal output / npm log.

**Comment by iShiZhi** [comment]
@sindresorhus I have updated the issues, thanks for your tip.

**Comment by sindresorhus** [comment]
> npm WARN optional dep failed

It's just an optional dependency. Nothing is broken.
