### ISSUE TITLE
Use `jit-grunt` instead of `load-grunt-tasks`

### ISSUE THREAD

**Issue by hanfeisun** [yeoman/generator-angular#979]
I think that would be much faster...

**Comment by sindresorhus** [comment]
No, last time we tried it it turned out to be slower or equal. The main bottleneck isn't loading anyways. Happy to be proven wrong with some real benchmark numbers though.

**Comment by bmatto** [comment]
I am using angular generator and load times were around 5s, adding jit-grunt cut them down to 50ms.  This is compounded for machines/environments that have slower IO, machines using non SSD for example - also in the context of a mounted VM ala Vagrant.

**Comment by lambdatoast** [comment]
I can confirm that the difference is huge on my mac mini (which has a non SSD drive.) It went from several seconds to about 50ms with jit-grunt.
