### ISSUE TITLE
Altering grunt for mobile device web development (cordova/phonegap)

### ISSUE THREAD

**Issue by deostroll** [yeoman/generator-angular#982]
What are the options I have to speed up mobile development? Presently grunt runs everything (unit test, minification, etc) and copies those files to an external folder (so I am usually running with `grunt --force`).

Most of my debugging has to happen on the mobile with a series of alert statements littered in my code everywhere. There are many grunt tasks not really required for this style of working - minification, concatenation, etc.

Need some guidance of writing a grunt task suitable for mobile development

**Comment by eddiemonge** [comment]
This is better suited for stackoverflow and Im pretty sure I have seen solutions for this already there.

**Comment by OminStyle** [comment]
I combined Yeoman generator for angular and Ionic-cli: https://github.com/OminStyle/yo-angular-ionic-cli/. You can also use cordova commands.
