### ISSUE TITLE
Add `grunt-ng-constant` to enable different environment configuration..

### ISSUE THREAD

**Issue by hanfeisun** [yeoman/generator-angular#983]
I found this feature very useful to set different environments during development.

http://stackoverflow.com/questions/16339595/angular-js-configuration-for-different-enviroments

It would be great if generator-angular could have it...

**Comment by eddiemonge** [comment]
Seems like something that will add additional code to the final output. Is that not correct? In my code I have grunt write variables out to the index.html file and then angular reads those. I have different config files for the different environments so there is very little code added.

**Comment by hanfeisun** [comment]
Got it, use grunt to write variable to the index.html file may be a better solution
