### ISSUE TITLE
Error installing Angular Generator

### ISSUE THREAD

**Issue by geerzo** [yeoman/generator-angular#985]
I can't seem to get npm to install the generator. I keep getting the following error.

```
npm ERR! argv "node" "/Users/geerzo/.node/bin/npm" "install" "-g" "generator-angular"
npm ERR! node v0.10.35
npm ERR! npm  v2.2.0
npm ERR! path /Users/geerzo/.node/lib/node_modules/generator-karma/node_modules/yeoman-generator/node_modules/download/node_modules/fs-extra/node_modules/ncp/package.json
npm ERR! code ENOENT
npm ERR! errno 34
```

In digging further it seems as if it's ultimately caused when trying to install this package fs-extra@0.11.1 which is used by generator-karma >= 0.8.0. Newer versions of fs-extra seem to install (or older versions of generator-karma).

**Comment by eddiemonge** [comment]
please open this on the karma generator repo. https://github.com/yeoman/generator-karma/issues

**Comment by geerzo** [comment]
Here is the link to their issue. I'd argue this is still an Angular Generator issue since it can't install but clearly there is an external dependency.

https://github.com/yeoman/generator-karma/issues/71
