### ISSUE TITLE
Load JS file with dynamic query string parameter

### ISSUE THREAD

**Issue by dhirenipatel** [yeoman/generator-angular#989]
I am developing application with yeoman + grunt + angularJs with generator-angular.
To load the JS file whenever require I have added JS file path inside calendar.html using below code.

```html
<!-- build:js({.tmp,app}) scripts/fullcalendar.js -->
  <script src="scripts/plugins/fullcalendar/fullcalendar.js"></script>
<!-- endbuild -->
```

This solution is working properly. But now whenever I load my Calendar page a fresh request goes to fullcalenar.js with dynamic query string parameter like below. If I move above calendar.html code (along with comment) inside index.html file, application works properly and cache the file without combining with rest of the JS files. On doing that fullcalendar.js file will get loaded with first page itself. I don't want that. 

Example of the request with every page load. 

http://localhost/scripts/fullcalendar.a13f9b72f8.js?_=1422010995753

Grunt file code is

```javascript
compass: {
   options: {
             javascriptsDir: '<%= yeoman.app %>/scripts',
             fontsDir: '<%= yeoman.app %>/styles/fonts',
             importPath: './bower_components',
             relativeAssets: false,
             assetCacheBuster: false,
             raw: 'Sass::Script::Number.precision = 10\n'
  },
server: {
          options: {
                 debugInfo: false
           }
    }
}
```

I have also raised question in Stackoverflow.

http://stackoverflow.com/questions/28108792/angularjs-grunt-load-js-file-with-dynamic-query-string-parameter

Please help me. 
Thanks in advance.

**Comment by eddiemonge** [comment]
closing this as it doesnt look like a bug and it is open on stackoverflow. having one source place would be better than multiple
