### ISSUE TITLE
Getting a "Class not registered" error when running "grunt serve"

### ISSUE THREAD

**Issue by cmacdonnacha** [yeoman/generator-angular#990]
When I run "grunt serve" I get the following error:

![classnotreg](https://cloud.githubusercontent.com/assets/9777763/5992213/64c9dfa4-aa17-11e4-8ceb-6e71b39c6dbd.png)

I'm running Windows 8.1 64-bit. 

When I run "grunt serve" the browser does not launch but if I browse to "http://localhost:9000/#" the app is running so I was thinking that this error is thrown when it fails to launch the browser.

**Comment by sindresorhus** [comment]
http://bit.ly/168w77q
