### ISSUE TITLE
Change the way grunt tasks are organized

### ISSUE THREAD

**Issue by gkaimakas** [yeoman/generator-angular#993]
In sails.js there is a file called tasks that holds all the grunt task and is very organized and clean. Could some functionality of that sort be implemented in this generator?

It would make using grunt so much easier.

**Comment by sindresorhus** [comment]
You will need to be more comprehensive in your explanation on what you want.

**Comment by gkaimakas** [comment]
Well I was in a hurry so I didn't elaborate.

In sails.js when you scaffold an app, a Gruntfile is created and a folder called tasks with two subfolders, config and register. The structure is similar to:
     -Gruntfile.js
     -tasks
        -config
        -register

In the config folder there are configuration files for each task e.g autoprefixer.js.
In the register folder tasks are registered with grunt.

This approach produces much cleaner code than having all grunt related stuff in one place.

I have created a sample app so that you can see the code. It is located here https://github.com/gkaimakas/sails.example

**Comment by eddiemonge** [comment]
We have had this discussion before and each time decided not to do it since the added complexity outweighed the benefits. The compromise was commenting the the gruntfile to make it clear what is going on. The issue was on generator-webapp and I can't find it at the moment.
